Update F(E)VM FIP Status
filecoin-project/FIPs pull request #1067
Opened 2024-09-12 23:17 UTC by Stebalien

1. Move FIP-0030 to Final (already marked as Final in the README). I've also updated the text to btter reflect what was actually implemented.
2. Move FIP-0031 to Final (already marked as Final in the README).
3. Move FIP-0032 to Final (already marked as Final in the README).
4. Withdraw FIP-0037 (this FIP was replaced by FIP-0054 and FIP-0057).
5. Move FIP-0054 and FIP-0057 to Final (already marked as Final in the README).

2024-09-12 23:19 UTC, lanzafame approved these changes

2024-09-13 00:08 UTC, lanzafame requested changes

2024-09-13 00:08 UTC, lanzafame commented on FIPS/fip-0030.md
> +Users can deploy custom EVM-based smart contracts using FEVM (see [FIP-0054](https://github.com/filecoin-project/FIPs/blob/master/FRCs/frc-0042.md)).
```suggestion
Users can deploy custom EVM-based smart contracts using FEVM (see [FIP-0054](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0054.md)).
```

2024-09-14 11:43 UTC, jsoares approved these changes
I have mixed feelings on the substantive updates to FIP-0030, but am inclined to agree that reflecting the reality of what was implemented is more important than preserving what was proposed. Nevertheless, I think it's worth hearing from other editors.

2024-09-14 11:43 UTC, jsoares commented on FIPS/fip-0030.md
> +considerations, but they will likely be supported eventually.
```suggestion
considerations.
```

I think our practice has been to avoid forward-looking statements in FIP specs.

2024-09-14 11:43 UTC, jsoares commented on FIPS/fip-0030.md
> +Wasm actors to Filecoin mainnet. New wasm-based actors are deployed during network
```suggestion
For the time-being, all Wasm-based actors are built-in and users cannot deploy custom
Wasm actors to Filecoin mainnet. New Wasm-based actors are deployed during network
```

2024-09-14 22:53 UTC, anorth approved these changes

2024-09-18 03:56 UTC, jennijuju approved these changes

2024-09-18 08:43 UTC, merged