Add Support for EIP-1153 (Transient Storage) in the FEVM
filecoin-project/FIPs pull request #1084
Opened 2024-11-23 00:13 UTC by snissn

## Abstract
EIP-1153 defines transient storage as temporary data accessible only during the originating transaction, cleared automatically at the end of the transaction. This FIP adapts transient storage to the FEVM using `TLOAD` and `TSTORE` opcodes, ensuring compatibility with Ethereum contracts and libraries that rely on this feature. Lifecycle validation mechanisms enforce the transaction-scoped behavior of transient storage, achieving functional equivalence with Ethereum’s implementation and seamless integration with Filecoin’s architecture.

## Discussion:
- https://github.com/filecoin-project/FIPs/discussions/855

2024-11-25 00:35 UTC, rvagg commented on FIPS/fip-draft_transient_storage.md
> +EIP-1153 defines transient storage as temporary data accessible only during the originating transaction, cleared automatically at the end of the transaction. This FIP adapts transient storage to the
should probably same something about it also being scoped _to a contract_, such that nested contract calls don't have access to this memory space - scoped strictly to transaction + contract

2024-11-25 00:39 UTC, rvagg commented on FIPS/fip-draft_transient_storage.md
> +Transient storage offers developers temporary, transaction-scoped storage for managing intermediate states. One key benefit of this feature is its ability to improve the implementation of reentrancy
note about availability in Ethereum - I believe this went live in March with the Decun (Cancun) upgrade, so we're trailing already by 7 months

2024-11-25 00:42 UTC, rvagg commented on FIPS/fip-draft_transient_storage.md
> +The FEVM implements transient storage using a lifecycle validation mechanism to ensure data remains accessible only during the originating transaction. This validation enforces the same behavior as E
note about isolation between contracts that may get stacked during the transaction

2024-11-25 00:44 UTC, rvagg commented on FIPS/fip-draft_transient_storage.md
> +The addition of transient storage is fully backward-compatible. Existing contracts remain unaffected unless they utilize `TLOAD` and `TSTORE`. Contracts compiled with older Solidity versions will con
note about solidity compiler and mode in here at which point compatibility breaks -  v0.8.24 with "Cancun" I believe? Antyhing before that should remain unaffected but after that will support TLOAD and TSTORE once this goes live

2024-11-25 00:45 UTC, rvagg commented on FIPS/fip-draft_transient_storage.md
> +
```suggestion
   - Verify `TSTORE` writes data to the transient storage correctly.
   - Verify `TLOAD` from an unitialized location returns the zero value.

```

2024-11-25 00:46 UTC, rvagg commented on FIPS/fip-draft_transient_storage.md
> +
```suggestion
   - Verify that transient storage is properly cleared at the end of each transaction and any out-of-lifecycle data does not interfere with subsequent transaction operations.
   - Verify that nested contracts do not have access to shared memory spaces and can read and write independently.
   - Verify that memory remains accessible and stable after contract re-entry.

```

2024-11-25 00:47 UTC, rvagg commented on FIPS/fip-draft_transient_storage.md
> +
```suggestion
- Ensuring transient storage clears properly after a transaction ends.
- Ensuring nested contracts do not have access to eachother's memory spaces.

```

2024-11-25 00:49 UTC, rvagg requested changes
:+1: excellent; just some inline notes about some things I think are missing from here

2024-11-25 15:08 UTC, snissn commented on FIPS/fip-draft_transient_storage.md
> +EIP-1153 defines transient storage as temporary data accessible only during the originating transaction, cleared automatically at the end of the transaction. This FIP adapts transient storage to the
thanks! I added changes to e0f94d2 to reflect your comment. I think that they add helpful clarity!

2024-11-25 15:15 UTC, snissn commented on FIPS/fip-draft_transient_storage.md
> +Transient storage offers developers temporary, transaction-scoped storage for managing intermediate states. One key benefit of this feature is its ability to improve the implementation of reentrancy
c7d03e3

2024-11-25 15:28 UTC, snissn commented on FIPS/fip-draft_transient_storage.md
> +The addition of transient storage is fully backward-compatible. Existing contracts remain unaffected unless they utilize `TLOAD` and `TSTORE`. Contracts compiled with older Solidity versions will con
To add further clarity on transient storage and its integration with Solidity:

The implementation of transient storage in the Ethereum Virtual Machine (EVM), as introduced in EIP-1153, relies on two new opcodes: `TLOAD` and `TSTORE`. These opcodes enable direct interaction with transient storage slots, which are scoped to the transaction and the contract. Solidity supports these opcodes starting from version `v0.8.24`, introduced with the Cancun upgrade.

However, it’s important to note that Solidity's support for transient storage remains assembly-based. Developers must explicitly use inline assembly to interact with transient storage, as high-level abstractions (like mappings or arrays) are not currently available for transient data. For example, accessing transient storage in Solidity might look like this:

```solidity
uint256 val;
assembly {
    val := tload(slot) // Load value from transient storage at `slot`
    tstore(slot, 42)   // Store value 42 in transient storage at `slot`
}
```

A good example of how transient storage is currently being used can be found in [[Uniswap V4’s Lock implementation](https://github.com/Uniswap/v4-core/blob/b619b6718e31aa5b4fa0286520c455ceb950276d/src/libraries/Lock.sol)](https://github.com/Uniswap/v4-core/blob/b619b6718e31aa5b4fa0286520c455ceb950276d/src/libraries/Lock.sol). This demonstrates a lock implemented in assembly using `TLOAD` and `TSTORE`.

This means that while transient storage functionality is available in newer Solidity versions, its usage is not deeply integrated into the language's high-level constructs. Contracts compiled with older versions of Solidity (prior to `v0.8.24`) will remain unaffected unless they are explicitly updated to use `TLOAD` and `TSTORE`.

This reinforces the point that the introduction of transient storage does not break compatibility for existing contracts. The feature is optional and only affects contracts that are explicitly written to use it with newer Solidity versions.

2024-11-25 15:35 UTC, snissn commented on FIPS/fip-draft_transient_storage.md
> +The addition of transient storage is fully backward-compatible. Existing contracts remain unaffected unless they utilize `TLOAD` and `TSTORE`. Contracts compiled with older Solidity versions will con
To provide additional context, the notion of transient storage compatibility being closely tied to specific Solidity versions, such as `v0.8.24`, may not fully capture the broader picture. While Solidity added support for the `TLOAD` and `TSTORE` opcodes in `v0.8.24` following the Cancun upgrade, these opcodes are fundamentally EVM-level features. Developers can interact with them directly at the opcode level, independent of the Solidity version, as long as the underlying EVM implementation supports these opcodes.

For instance, transient storage can be accessed in assembly using the raw opcodes for `TLOAD` (`0x5c`) and `TSTORE` (`0x5d`), even with Solidity versions earlier than `v0.8.24`:

```solidity
uint256 val;
assembly {
    // Load value from transient storage at `slot`
    mstore(0x00, slot)      // Prepare the slot address
    pop(staticcall(gas(), 0x5c, 0x00, 0x20, 0x00, 0x20)) // Raw opcode for TLOAD
    val := mload(0x00)      // Retrieve the value from memory

    // Store value 42 into transient storage at `slot`
    mstore(0x00, slot)      // Prepare the slot address
    mstore(0x20, 42)        // Prepare the value
    pop(staticcall(gas(), 0x5d, 0x00, 0x40, 0x00, 0x00)) // Raw opcode for TSTORE
}
```

This shows that while Solidity `v0.8.24` introduces a more streamlined way to use `TLOAD` and `TSTORE` opcodes, the underlying functionality is an EVM feature and not strictly tied to the compiler version. This means developers could theoretically use transient storage with older Solidity versions by working directly with these opcodes, as long as the runtime environment supports them.

That said, this approach comes with some challenges:
- **Readability and Maintenance**: Using raw opcodes makes code harder to read and maintain compared to the cleaner `TLOAD` and `TSTORE` mnemonics introduced in Solidity.
- **Version Interpretation**: Associating transient storage solely with Solidity `v0.8.24` might create confusion, as its implementation is ultimately dependent on the EVM rather than the compiler version.
- **Risk of Errors**: Directly handling opcodes increases the risk of bugs and introduces additional complexity, particularly if the EVM evolves in the future.

To summarize, while Solidity `v0.8.24` provides high-level support for transient storage, the functionality itself exists at the EVM level. Discussions of compatibility should focus on the EVM’s support for `TLOAD` and `TSTORE` opcodes rather than being solely tied to specific Solidity compiler versions.

2024-11-25 15:35 UTC, snissn commented on FIPS/fip-draft_transient_storage.md
> +The addition of transient storage is fully backward-compatible. Existing contracts remain unaffected unless they utilize `TLOAD` and `TSTORE`. Contracts compiled with older Solidity versions will con
To add to the discussion, the backwards compatibility section as written is accurate—contracts compiled with older Solidity versions (pre-`v0.8.24`) will remain unaffected, as they do not include `TLOAD` and `TSTORE`. These opcodes, introduced in the EVM with the Cancun upgrade, are supported in Solidity starting with `v0.8.24`. However, it’s a fun idea to explore that the compatibility of transient storage is fundamentally an EVM-level feature and not strictly tied to a specific Solidity version.

For example, developers can interact with transient storage directly using the raw opcodes (`TLOAD = 0x5c` and `TSTORE = 0x5d`) in assembly, regardless of the Solidity version used, as long as the underlying EVM supports these opcodes. The cancun Ethereum hardfork definitely itroduces the two opcodes associated with transient storage, but these can be accessed by developers working with different versions of Solidity:

```solidity
uint256 val;
assembly {
    // Load value from transient storage at `slot`
    mstore(0x00, slot)      // Prepare the slot address
    pop(staticcall(gas(), 0x5c, 0x00, 0x20, 0x00, 0x20)) // Raw opcode for TLOAD
    val := mload(0x00)      // Retrieve the value from memory

    // Store value 42 into transient storage at `slot`
    mstore(0x00, slot)      // Prepare the slot address
    mstore(0x20, 42)        // Prepare the value
    pop(staticcall(gas(), 0x5d, 0x00, 0x40, 0x00, 0x00)) // Raw opcode for TSTORE
}
```

This flexibility means that while Solidity `v0.8.24` introduces a more user-friendly way to access transient storage, it is not strictly required for its use. The feature itself is native to the EVM, so compatibility depends more on the runtime environment supporting these opcodes than on the Solidity compiler version.

In summary, the backwards compatibility section captures the key points well. For developers working with transient storage, the association with Solidity `v0.8.24` is primarily about convenience, as the opcodes themselves are an EVM feature accessible in any version of Solidity that supports inline assembly.

2024-11-25 15:38 UTC, snissn commented on FIPS/fip-draft_transient_storage.md
> +
12556d9 and f576eab

2024-11-25 15:39 UTC, snissn commented on FIPS/fip-draft_transient_storage.md
> +
f576eab I think this adds the requirement in a way that accommodates your comment

2024-11-25 15:44 UTC, snissn commented
Thanks for the comments @rvagg ! Your feedback helps clarify many important aspects of this FIP and leaves to a more robust proposal overall! I got a little "nerd sniped" by the solidity version relationship to this FIP, and hope I didn't get too nuanced and abstract! Please share any additional comments and feedback to ensure all of your requests and ideas have been addressed and accommodated! Thanks again!

2024-11-28 09:27 UTC, rvagg commented on FIPS/fip-draft_transient_storage.md
> +The addition of transient storage is fully backward-compatible. Existing contracts remain unaffected unless they utilize `TLOAD` and `TSTORE`. Contracts compiled with older Solidity versions will con
hah, that's all quite interesting! thanks for the braindump. I'm not sure how much of that to suggest putting into the doc, maybe at least the thing about it being an `assembly {}` feature even in newer versions of Solidity—the important point being that it's _explicitly_ opt-in, it's not something the compiler is going to pop out for you when you compile because it makes sense for something you're doing. Because that's the concern with compatibility - will a newer compiler produce bytecode that it thinks is optimal because there's a new feature but we're not able to run it. But in this case, from what you're saying, that's not even a possibility. That seems like something worth noting.

2024-11-28 12:54 UTC, jsoares approved these changes
Nothing substantive to add to @rvagg's excellent feedback. Provided the outstanding comments are addressed, this looks good to go.

2024-11-28 12:54 UTC, jsoares commented on FIPS/fip-draft_transient_storage.md
> +- Ensuring nested contracts do not have access to eachother's memory spaces.
```suggestion
- Ensuring nested contracts do not have access to each other's memory spaces.
```
I'm all for archaic and nonstandard spellings, but maybe not here :)

2024-11-28 12:54 UTC, jsoares commented on FIPS/fip-draft_transient_storage.md
> +By implementing transient storage, the FEVM ensures compatibility with Ethereum’s tooling and supports developers accustomed to this feature. It also facilitates seamless integration of existing proj
These read like product, rather than incentive, considerations. It's unclear if there are significant incentive considerations at play; I'm not convinced there are.

2024-11-28 12:55 UTC, jsoares commented
Assigning FIP-0097. Please update filename, front matter, and readme.

2024-12-05 10:09 UTC, snissn commented on FIPS/fip-draft_transient_storage.md
> +- Ensuring nested contracts do not have access to eachother's memory spaces.
thanks! The github UI is currently unwilling to commit the change but I added it here: 79d0086

2024-12-05 10:11 UTC, snissn commented on FIPS/fip-draft_transient_storage.md
> +Transient storage offers developers temporary, transaction-scoped storage for managing intermediate states. One key benefit of this feature is its ability to improve the implementation of reentrancy
thanks! 06ced1d

2024-12-05 10:19 UTC, snissn commented
@luckyparadise thanks for your question! Reviewing the writing I see that the word usage of ephemeral can be creating confusion witihout adding much to the document. 

Transient storage is the technical term that has technical meaning. My intention behind my usage of ephemeral in this FIP write up was to be a descriptive term that doesn't insist on a precise technical purpose per se. I think it's an attempt I made to create a category for memory data and transient data that would be separate from storage data..

 I think I can just delete the three instances of the word ephemeral in the FIP write up and it removes ambiguity and nothing is lost. Changed here b69533d

2024-12-05 10:24 UTC, snissn commented on FIPS/fip-draft_transient_storage.md
> +The addition of transient storage is fully backward-compatible. Existing contracts remain unaffected unless they utilize `TLOAD` and `TSTORE`. Contracts compiled with older Solidity versions will con
Thanks @rvagg what you are suggesting does sound helpful! I'll try to synthesize that into an addition this week.

2024-12-09 04:50 UTC, rvagg commented on FIPS/fip-0097.md
> +The addition of transient storage is fully backward-compatible. Existing contracts remain unaffected unless they utilize `TLOAD` and `TSTORE`. Contracts compiled with older Solidity versions will con
```suggestion
The addition of transient storage is fully backward-compatible. Existing contracts remain unaffected unless they utilize `TLOAD` and `TSTORE`. Contracts compiled with older Solidity versions will continue to execute without changes.

At the time of writing, support for `TLOAD` and `TSTORE` in current versions of Solidity is only available using inline-assembly. Thus, it is an explicitly opt-in feature, rather than a feature that contract authors may unknowngly be enabling when bumping compiler version and EVM target.
```

2024-12-09 04:50 UTC, rvagg commented on FIPS/fip-draft_transient_storage.md
> +The addition of transient storage is fully backward-compatible. Existing contracts remain unaffected unless they utilize `TLOAD` and `TSTORE`. Contracts compiled with older Solidity versions will con
left a suggestion for wording

2024-12-10 21:04 UTC, snissn commented on FIPS/fip-0097.md
> +The addition of transient storage is fully backward-compatible. Existing contracts remain unaffected unless they utilize `TLOAD` and `TSTORE`. Contracts compiled with older Solidity versions will con
Thanks @rvagg your addition is much appreciated!

2024-12-10 21:21 UTC, snissn commented on FIPS/fip-draft_transient_storage.md
> +By implementing transient storage, the FEVM ensures compatibility with Ethereum’s tooling and supports developers accustomed to this feature. It also facilitates seamless integration of existing proj
Thanks! I have revised this section here: ddf9501

2024-12-11 04:01 UTC, rvagg approved these changes

2024-12-11 19:16 UTC, anorth approved these changes
Editorial 👍

2024-12-11 22:20 UTC, merged