FIP process amendment to integrate spec update
filecoin-project/FIPs pull request #11
Opened 2020-10-12 20:46 UTC by yiannisbot

This PR proposes slight changes to the FIP process to include integration with the [Filecoin Specification](https://spec.filecoin.io/). There has been discussion and agreement on the fact that if the Filecoin protocol is updated without the changes being directly reflected in the protocol's specification, then the spec will be outdated very soon.

The updates include slight procedural modifications, i.e., a PR to the [spec repository](https://github.com/filecoin-project/specs) is submitted before the FIP is marked as "Final", as well as a small syntax change on the front matter of the FIP Template to indicate which section(s) the FIP is touching upon. This change will allow pulling this information from the FIP repo directly into the Spec repo and will enable us to link to the FIP(s) applied to each section of the spec.

cc: @hugomrdias

2020-10-19 11:26 UTC, hugomrdias commented
All sections in the spec now have a label that can be easily copy/pasted into a FIP frontmatter.

2020-10-21 09:24 UTC, hugomrdias commented
![spec label example](https://user-images.githubusercontent.com/314190/96700637-923e4800-1387-11eb-9ea5-7cd0e8f12bc8.gif)

2020-10-22 22:59 UTC, momack2 approved these changes
This looks good! We discussed in today's Core Devs meeting and generally approved this improvement to help keep the spec up to date: https://www.youtube.com/watch?v=58b8TY9LJaM

2020-10-27 11:16 UTC, hugomrdias requested changes
Added some suggested changes so we can better integrate FIPs in the spec.

2020-10-27 11:16 UTC, hugomrdias commented on FIPS/fip-0001.md
> +` spec-sec:` Spec section(s) that the FIP is updating (comma-separated if more than one).
```suggestion
`spec-sections:` A list of Spec sections that the FIP is updating.

`spec-pr:` The URL for the PR updating the Spec.
```

2020-10-27 11:16 UTC, hugomrdias commented on FIPS/fip-0001.md
> +Spec section(s) that the FIP is updating, based on the folder structure of the spec repository. For instance, if a FIP updates the operation of the `mpool`, the entry in this field should be `<fileco
```suggestion
Spec sections that the FIP is updating, each section has an ID that can be found in the Spec website under each section "three dot" menu. Example: https://github.com/filecoin-project/FIPs/pull/11#issuecomment-713435889.

Example:
```yaml 
spec-setions:
  - section-intro
  - section-libraries.libp2p
  - section-systems.filecoin_markets.storage_market.deal-flow
```

#### `spec-pr`

The URL for the PR that updates the Spec according to the current FIP.

Example:
```yaml
spec-pr: https://github.com/filecoin-project/specs/pull/1204
```


```

2020-10-27 11:16 UTC, hugomrdias commented on FIPS/fip-0001.md
> +#### `spec-sec`
```suggestion
#### `spec-sections`
```

2020-10-27 11:16 UTC, hugomrdias commented on FIPS/fip-0001.md
> +- Check whether the FIP needs to be accompanied by an update to the specification and if os, make sure that a PR to spec repository has been submitted and that the text that updates the spec is refle
```suggestion
- Check whether the FIP needs to be accompanied by an update to the specification and if so, make sure that a PR to spec repository has been submitted and that the text that updates the spec is reflecting the changes that the FIP proposes.
```

2020-10-27 11:16 UTC, hugomrdias commented on templates/template_FTP.md
> +spec-sec: Spec section(s) that the FIP is updating (comma-separated if more than one), displayed following the folder structure of the spec repository, e.g., for the mpool section it should be \<file
```suggestion
spec-sec: 
  - <section-id>
  - <section-id>
```

2020-10-27 11:16 UTC, hugomrdias commented on FIPS/fip-0001.md
> +Spec section(s) that the FIP is updating, based on the folder structure of the spec repository. For instance, if a FIP updates the operation of the `mpool`, the entry in this field should be `<fileco
the preview for the suggested change look a bit off but the source is correct.

2020-11-03 03:23 UTC, momack2 approved these changes

2020-11-03 07:40 UTC, daviddias approved these changes

2020-11-03 09:50 UTC, hugomrdias approved these changes

2020-11-03 21:54 UTC, merged