Create fip-0029 - remove DataCap from verified client
filecoin-project/FIPs pull request #226
Opened 2021-12-14 08:47 UTC by dkkapur

FIP to enable notaries and the Filecoin Plus community to remove unused DataCap from a client address on the network. DataCap removal will require 2 notary signatures and 1 RKH signature.

2021-12-15 01:18 UTC, jennijuju requested changes

2021-12-15 01:26 UTC, jennijuju commented on FIPS/fip-0029.md
> +
### **Add `RemoveVerifiedClient` to the verified_registry_actor**

<TO BE REVIEWED>

```go

  func (a Actor) RemoveVerifiedClient(rt runtime.Runtime, params * RemoveVerifiedClientParams) *abi.EmptyValue {
  ...

  }
  
  type RemoveVerifiedParams struct {
	  Address   addr.Address
	  InitiatorSignature crypto.Signature
          ApprovalSignature crypto.Signature
  }
```

2021-12-15 01:31 UTC, jennijuju commented on FIPS/fip-0029.md
> +<!--The technical specification should describe the syntax and semantics of any new feature. The specification should be detailed enough to allow competing, interoperable implementations for any of t
```suggestion
<!--The technical specification should describe the syntax and semantics of any new feature. The specification should be detailed enough to allow competing, interoperable implementations for any of the current Filecoin implementations. -->

**### **Add `RemoveVerifiedClient` to the verified_registry_actor**

<TO BE REVIEWED>

```go

  func (a Actor) RemoveVerifiedClient(rt runtime.Runtime, params * RemoveVerifiedClientParams) *abi.EmptyValue {
  ...

  }
  
  type RemoveVerifiedClientParams struct {
	  Address   addr.Address
	  InitiatorSignature crypto.Signature
          ApprovalSignature crypto.Signature
  }
```
```

2021-12-16 04:43 UTC, jennijuju requested changes

2021-12-16 04:43 UTC, jennijuju commented on FIPS/fip-0029.md
> +For the initial v1 design, neither of the notaries needs to have been the original verifier / granter of DataCap to the verified client.
```suggestion
For the initial v1 design, neither of the notaries needs to have been the original verifier / granter of DataCap to the verified client.

If the requested amount of datacap for removal is greater or equal than the remaining datacap the client has, the client address will be removed from the `VerifiedClients` map in verified_registry_state.
```

2021-12-16 10:02 UTC, ribasushi commented on FIPS/fip-0029.md
> +
Missing closing quote 
```suggestion

```

```

2021-12-16 10:03 UTC, ribasushi commented on FIPS/fip-0029.md
> +
Missing closing quote 
```suggestion

 ```
```

2021-12-17 21:23 UTC, arajasek requested changes

2021-12-17 21:23 UTC, arajasek commented on FIPS/fip-0029.md
> +`RemoveVerifiedClientDatacap` will need 3 signatures, two from any of the verifiers (notaries) and one from any of the signers of the root key holder multisig (`f080`). Every DataCap removal from a c
There's a problem with this approach -- the Verified Actor does not assume that it's VRK is a multisig. It could be a secp account, it just happens to be a multisig on mainnet.

Adding code that assumes that f080 is a multisig is therefore a weird change to be making. I also don't like the idea of having "partial" multisig approval -- anything "approved" by an msig should meet its threshold. Code that gets into the guts of an msig to see if any 1 of its signers has signed something is bad.

I have no opinion on whether the threshold should be raised to getting the full approval of the f080 msig (whatever its threshold is), or lowered to not needing VRK approval at all.

2021-12-17 21:25 UTC, arajasek commented on FIPS/fip-0029.md
> +`RemoveVerifiedClientDatacap` will need 3 signatures, two from any of the verifiers (notaries) and one from any of the signers of the root key holder multisig (`f080`). Every DataCap removal from a c
(I definitely see the need for including the VRK, because otherwise a rogue notary or 2 could revoke the entire network's cap)

2021-12-28 23:12 UTC, dkkapur commented on FIPS/fip-0029.md
> +`RemoveVerifiedClientDatacap` will need 3 signatures, two from any of the verifiers (notaries) and one from any of the signers of the root key holder multisig (`f080`). Every DataCap removal from a c
@arajasek sorry I didn't explicitly thumb this up, but we are in agreement for v1, let's proceed with 2 verifiers sending a message followed by RKH multisig approval (2 signer threshold). Would be great if we can get an early peek into the design for this so we can follow up with tooling that should be build for the Fil+ App

2021-12-28 23:22 UTC, jennijuju commented on FIPS/fip-0029.md
> +`RemoveVerifiedClientDatacap` will need 3 signatures, two from any of the verifiers (notaries) and one from any of the signers of the root key holder multisig (`f080`). Every DataCap removal from a c
@dkkapur WIP here https://github.com/filecoin-project/specs-actors/pull/1546/files

2022-01-04 03:25 UTC, arajasek commented on FIPS/fip-0029.md
> +- 2 RKH approving
outdated

2022-01-07 02:03 UTC, kaitlin-beegle commented on FIPS/fip-0029.md
> +fip: "to be assigned"
This is actually going to be FIP0028.  @dkkapur would you mind  updating the FIP number and file name?

2022-01-25 20:55 UTC, kaitlin-beegle commented
This FIP has officially passed 'Last Call' status, and is 'Accepted'! It's ready for implementation in v15.  

@dkkapur could you address the changes requested by @arajasek and @jennijuju so we can move towards merging this draft?

2022-01-26 01:31 UTC, hunjixin commented
@kaitlin-beegle  is title correct fip0028 or fip0029? 
![image](https://user-images.githubusercontent.com/41407352/151087993-dc5ce51d-5860-4c70-a091-f75335b71b20.png)

2022-01-26 01:36 UTC, kaitlin-beegle commented
> @kaitlin-beegle is title correct fip0028 or fip0029? ![image](https://user-images.githubusercontent.com/41407352/151087993-dc5ce51d-5860-4c70-a091-f75335b71b20.png)

This is correct; is there a reason why you think it isn't?

2022-01-26 06:36 UTC, hunjixin commented
not see the latest commit, this commit has change filename to 0028

2022-01-26 19:44 UTC, kaitlin-beegle commented
> not see the latest commit, this commit has change filename to 0028

Yep! This is correct.

2022-02-01 02:20 UTC, kdreampool commented
Am I late?
In case of no confirmed CLIENT activity or abuse of systems and incentives, the current level of discussion and action is correct.
However, it is often the SP that drives CLIENTs that use Datacap in unethical ways, such as excessive self-transactions, unsearchable data, etc.
Therefore, it is necessary to discuss how to strictly limit these SPs.

For example, the SP concludes that a CLIENT without valid data simply meets the conditions to apply for a data cap.
The SP then moves the CLIENT to apply the DataCap application on behalf of the CLIENT to request a DataCap or power on *10 with garbage data.

As discussed so far, there is no limit to these malicious SPs. SP recreates new CLIENTs used for unethical behaviors such as excessive self-transaction and inability to view data.

2022-02-02 00:35 UTC, anorth commented on FIPS/fip-0028.md
> +status: Draft
@dkkapur I understand that the implemeters committee have accepted this FIP and it's scheduled for the next network upgrade. Please update the status here.

2022-02-02 00:40 UTC, anorth approved these changes

2022-02-02 01:04 UTC, jennijuju requested changes

2022-02-02 01:04 UTC, jennijuju commented on FIPS/fip-0028.md
> +          ApprovalSignature crypto.Signature
Update to match with the final implementation

2022-02-02 01:04 UTC, jennijuju commented on FIPS/fip-0028.md
> +          ApprovalSignature crypto.Signature
https://github.com/filecoin-project/specs-actors/blob/80717140d6099c1374d4670fb2def9ff8ff4b218/actors/builtin/verifreg/verified_registry_actor.go#L322

2022-02-02 01:07 UTC, jennijuju commented
The implementation session doesn’t   

> Am I late? In case of no confirmed CLIENT activity or abuse of systems and incentives, the current level of discussion and action is correct. However, it is often the SP that drives CLIENTs that use Datacap in unethical ways, such as excessive self-transactions, unsearchable data, etc. Therefore, it is necessary to discuss how to strictly limit these SPs.
> 
> For example, the SP concludes that a CLIENT without valid data simply meets the conditions to apply for a data cap. The SP then moves the CLIENT to apply the DataCap application on behalf of the CLIENT to request a DataCap or power on *10 with garbage data.
> 
> As discussed so far, there is no limit to these malicious SPs. SP recreates new CLIENTs used for unethical behaviors such as excessive self-transaction and inability to view data.

What you described seems like a governance discussion that belongs to fil+ program and is not irrelevant to this fip.  id suggest you to raise your concern to fip+ Team/  community in https://github.com/filecoin-project/notary-governance/discussions

2022-02-04 02:13 UTC, kaitlin-beegle commented
> Am I late? In case of no confirmed CLIENT activity or abuse of systems and incentives, the current level of discussion and action is correct. However, it is often the SP that drives CLIENTs that use Datacap in unethical ways, such as excessive self-transactions, unsearchable data, etc. Therefore, it is necessary to discuss how to strictly limit these SPs.
> 
> For example, the SP concludes that a CLIENT without valid data simply meets the conditions to apply for a data cap. The SP then moves the CLIENT to apply the DataCap application on behalf of the CLIENT to request a DataCap or power on *10 with garbage data.
> 
> As discussed so far, there is no limit to these malicious SPs. SP recreates new CLIENTs used for unethical behaviors such as excessive self-transaction and inability to view data.

Hi @kdreampool - please note that this comment was received after the expiration of 'Last Call', so it has not impacted the acceptance of this FIP.  This FIP remains in 'accepted' status, and will be implemented in network v15. 

However, I believe the spirit of this FIP is intended to address the very situation you've outlined.  If a storage provider is pushing a client to apply for datacap, then diligence is still done on that client.  It is the responsibility of the FilecoinPlus notaries to do diligence on all clients and determine whether or not they are legitimate.  This FIP simply allows verified client status to be revoked after it had previously been granted, should a reason arise in which a client seems suspicious and/or appears to be abusing their datacap allocation. 

However, there is no technical change we could make that would prevent direct, off-line collusion, if that's what you're indeed claiming is a problem. If you're aware of a storage provider that is working in bad faith, or is trying to take advantage of the FilecoinPlus program, I would heavily encourage you to get in touch with the FilecoinPlus team.

CC: @dkkapur

2022-02-04 10:10 UTC, dkkapur commented on FIPS/fip-0028.md
> +status: Draft
@anorth @kaitlin-beegle is the right status "Accepted" or something else?

2022-02-04 10:10 UTC, dkkapur commented on FIPS/fip-0028.md
> +          ApprovalSignature crypto.Signature
@jennijuju - is additional review pending from the lotus side?

2022-02-04 10:14 UTC, dkkapur commented
Thanks @kdreampool for the discussion. I agree with @kaitlin-beegle's points above that this is just an implementation step that will help us build tools to shut down malicious use/abuse of DataCap. I also agree with @jennijuju that the case you've outlined requires work on the due diligence side and on arming the notaries to learn more about each client to ensure DataCap gets to the right hands. If it ends up in the wrong place, having this FIP implemented gives us an additional lever to correct course. Would be great to engage you in a Discussion on the Fil+ governance side to improve our processes for this.

2022-02-07 18:56 UTC, merged