FIP: gas model adjustment for user programmability.
filecoin-project/FIPs pull request #317
Opened 2022-03-09 14:49 UTC by raulk

This FIP follows #315, and introduces further gas model changes to address various aspects of user programmability.

2022-03-17 06:32 UTC, anorth reviewed
It looks like this PR accidentally duplicates part of #315. I've ignored the document `fip-0032.md` in this review.

2022-03-17 06:32 UTC, anorth commented on FIPS/fip-nnnn.md
> +author: Raúl Kripalani (@raulkr), Steven Allen (@stebalien)
Typo in `@raulkr` (also in fip-0032).

2022-03-17 13:25 UTC, raulk commented on FIPS/fip-nnnn.md
> +author: Raúl Kripalani (@raulkr), Steven Allen (@stebalien)
Thanks for noticing this. We really need a unified identity system :D

2022-04-01 18:26 UTC, kaitlin-beegle commented on FIPS/fip-nnnn.md
> +fip: "nnnn"
FIP0032, of course!

2022-05-09 17:48 UTC, kaitlin-beegle commented
Now that we're initiating Last Call on FVM FIPs 30-32, let's merge this FIP in as well in anticipation of upcoming work. 

FIP Editors, would you mind adding your review of the initial draft? @jennijuju @arajasek @momack2 

@raulk, it looks as if this branch should easily merge into master now that #315 is merged, but lmk if you have concerns about the way the PR was set up.

2022-06-23 22:57 UTC, kaitlin-beegle requested changes

2022-06-23 22:57 UTC, kaitlin-beegle commented on FIPS/fip-nnnn.md
> +fip: "nnnn"
FIP0037!

2022-07-08 02:03 UTC, merged