Updated Indexer FIP (ready to merge)
filecoin-project/FIPs pull request #365
Opened 2022-04-26 23:56 UTC by honghaoq

Updated latest version of Indexer FIP.

2022-04-27 00:53 UTC, kaitlin-beegle commented on FIPS/IndexerFIP.md
> +# Indexer FIP
Hey @honghaoq! Can you please add in the correct header? [See FIP0001 for details. ](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md#fip-header-preamble)

2022-04-27 01:06 UTC, honghaoq commented on FIPS/IndexerFIP.md
> +# Indexer FIP
Added!

2022-04-27 14:51 UTC, anorth commented
@kaitlin-beegle I'm not sure whether this should be a FIP or FRC. It doesn't propose any changes to the core Filecoin protocol, but proposes an ancillary protocol that is related and beneficial to Filecoin. But nodes don't have to implement it to remain fully-validating Filecoin nodes. It would still belong in this repo, but maybe have a different title. How shall we draw this distinction?

2022-04-27 17:09 UTC, kaitlin-beegle commented
> 

Thanks for surfacing this.  I was speaking with @honghaoq about this yesterday, and we briefly discussed it in Core Devs #41. 

I think you're correct that this ought to remain in this repo, but should be separated from our standard/Core Technical. FIPs.  If accepted, this should be seen as a standard for implementations, but the actual implementation doesn't need to be as closely coordinated. 

I'm inclined to adopt the EIP process, write up some quick documentation for this decision, open it for feedback for a few days, and codify this change (which seems a bit more formal) with a PR against FIP001.  However, @anorth, I know you had previously suggested introducing an FRC format and decided that more thought was needed- are there any particular considerations or concerns that you currently have about this format?

2022-04-27 17:14 UTC, kaitlin-beegle commented
> @kaitlin-beegle I'm not sure whether this should be a FIP or FRC. It doesn't propose any changes to the core Filecoin protocol, but proposes an ancillary protocol that is related and beneficial to Filecoin. But nodes don't have to implement it to remain fully-validating Filecoin nodes. It would still belong in this repo, but maybe have a different title. How shall we draw this distinction?

Thanks for surfacing this. I was speaking with @honghaoq about this yesterday, and we briefly discussed it in Core Devs https://github.com/filecoin-project/FIPs/issues/41.

I think you're correct that this ought to remain in this repo, but should be separated from our standard/Core Technical. FIPs. If accepted, this should be seen as a standard for implementations, but the actual implementation doesn't need to be as closely coordinated.

I'm inclined to adopt the EIP process, write up some quick documentation for this decision, open it for feedback for a few days, and codify this change (which seems a bit more formal) with a PR against FIP001. However, @anorth, I know you had previously suggested introducing an FRC format and decided that more thought was needed- are there any particular considerations or concerns that you currently have about this format?

2022-04-28 08:27 UTC, irybakov requested changes
Please, take this changes into account

2022-04-28 08:27 UTC, irybakov commented on FIPS/IndexerFIP.md
> +## Actors
```suggestion
## Parties
```

2022-04-28 08:27 UTC, irybakov commented on FIPS/IndexerFIP.md
> +    - Indexer ingestion latency: <60 sec p95
```suggestion
    - Indexing latency: <60 sec p95
```

2022-04-28 13:51 UTC, irybakov approved these changes

2022-05-03 23:37 UTC, honghaoq commented on FIPS/IndexerFIP.md
> +title: Indexer
Updated to 'Indexer Protocol for Filecoin Content Discovery'

2022-05-03 23:37 UTC, honghaoq commented on FIPS/IndexerFIP.md
> +status: Final
Updated!

2022-05-03 23:37 UTC, honghaoq commented on FIPS/IndexerFIP.md
> +spec-pr: https://github.com/filecoin-project/FIPs/pull/365/files
Added

2022-05-03 23:38 UTC, honghaoq commented on FIPS/IndexerFIP.md
> +## Actors
Thanks, changed to 'Parties'

2022-05-03 23:39 UTC, honghaoq commented on FIPS/IndexerFIP.md
> +    - Indexer ingestion latency: <60 sec p95
I added them as per the FIP template @kaitlin-beegle shared, happy to remove it though.

2022-05-09 17:43 UTC, willscott commented on FIPS/IndexerFIP.md
> +The metadata field contains provider-specific data that pertains to the set of multihashes being added.  The metadata is prefixed with a protocol ID number followed by data encoded as per the protoco
Can we specify the filecoin-graphsync transport metadata format that is being used by filecoin here?

2022-05-11 05:06 UTC, honghaoq commented on FIPS/IndexerFIP.md
> +The metadata field contains provider-specific data that pertains to the set of multihashes being added.  The metadata is prefixed with a protocol ID number followed by data encoded as per the protoco
bringing this to @gammazero 's attention

2022-05-22 23:36 UTC, anorth commented on FIPS/IndexerFIP.md
> +    - Indexer ingestion latency: <60 sec p95
I think test cases are relevant to consensus-changing FIPs, but since this is a recommendation rather than requirement for node operators, they could have different performance.

2022-05-22 23:38 UTC, anorth approved these changes
I think this is ready to be merged as a draft.

2022-05-22 23:38 UTC, anorth commented on FIPS/IndexerFIP.md
> +## Terminology
Nit: I would move this and "Parties" to level-3 headings under "Specification", so the level-2 headings remain as in the template.

2022-05-23 16:16 UTC, kaitlin-beegle commented on FIPS/IndexerFIP.md
> +The metadata field contains provider-specific data that pertains to the set of multihashes being added.  The metadata is prefixed with a protocol ID number followed by data encoded as per the protoco
Hey @honghaoq - was @gammazero able to provide clarity here? Are any final changes needed?

2022-05-23 16:21 UTC, honghaoq commented on FIPS/IndexerFIP.md
> +The metadata field contains provider-specific data that pertains to the set of multihashes being added.  The metadata is prefixed with a protocol ID number followed by data encoded as per the protoco
I am checking with Andrew

2022-05-23 21:14 UTC, gammazero commented on FIPS/IndexerFIP.md
> +The metadata field contains provider-specific data that pertains to the set of multihashes being added.  The metadata is prefixed with a protocol ID number followed by data encoded as per the protoco
```suggestion
The metadata field contains provider-specific data that pertains to the set of multihashes being added.  The metadata is prefixed with a protocol ID number followed by data encoded as per the protocol.  The content of the metadata is up to the provider, but if more than the limited size is needed, then the metadata should contain an ID identifying mode complex data stored by the provider.

Graphsync is the most commonly used protocol for retrieving content from a content provider. The filecoin-graphsync transport metadata is currently defined as follows:

Uvarint protcol `0x0910` (TransportGraphsyncFilecoinv1 in the [multicodec table](https://github.com/multiformats/multicodec/blob/master/table.csv#L134)). This is followed by a CBOR-encoded struct of:
- PieceCID, a link
- VerifiedDeal, boolean
- FastRetrieval, boolean  
```

2022-05-23 21:16 UTC, kaitlin-beegle commented
> > @kaitlin-beegle I'm not sure whether this should be a FIP or FRC. It doesn't propose any changes to the core Filecoin protocol, but proposes an ancillary protocol that is related and beneficial to Filecoin. But nodes don't have to implement it to remain fully-validating Filecoin nodes. It would still belong in this repo, but maybe have a different title. How shall we draw this distinction?
> 
> Thanks for surfacing this. I was speaking with @honghaoq about this yesterday, and we briefly discussed it in Core Devs #41.
> 
> I think you're correct that this ought to remain in this repo, but should be separated from our standard/Core Technical FIPs. If accepted, this should be seen as a standard for implementations, but the actual implementation doesn't need to be as closely coordinated.
> 
> I'm inclined to adopt the EIP process, write up some quick documentation for this decision, open it for feedback for a few days, and codify this change (which seems a bit more formal) with a PR against FIP001. However, @anorth, I know you had previously suggested introducing an FRC format and decided that more thought was needed- are there any particular considerations or concerns that you currently have about this format?

Alright, just pushed new docs outlining a potential FRC process...once we come to agreement about the details of this process, I suggest that this be the network's first FRC! 

To review: https://github.com/filecoin-project/FIPs/discussions/378

CC: @anorth @honghaoq

2022-05-23 22:49 UTC, gammazero commented on FIPS/IndexerFIP.md
> +- FastRetrieval, boolean
```suggestion
```go
type GraphsyncFilecoinV1 struct {
	// PieceCID identifies the piece this data can be found in
	PieceCID cid.Cid
	// VerifiedDeal indicates if the deal is verified
	VerifiedDeal bool
	// FastRetrieval indicates whether the provider claims there is an unsealed copy
	FastRetrieval bool
}
```
```

2022-06-23 23:56 UTC, kaitlin-beegle requested changes

2022-06-23 23:56 UTC, kaitlin-beegle commented on FIPS/IndexerFIP.md
> +fip: "0034"
FIP0038 please.

2022-06-23 23:56 UTC, kaitlin-beegle commented on FIPS/IndexerFIP.md
> +type: Technical (Core)
change type of 'FRC'

2022-06-25 01:27 UTC, closed without merging