Add FIP for Standard Authentication Method for Actors
filecoin-project/FIPs pull request #424
Opened 2022-08-03 03:14 UTC by arajasek

First draft of a replacement for FIP-0035, see #413 .

An open question is how much to couple this FIP to the discussion in #382 (if at all). Feedback welcome!

2022-08-03 22:26 UTC, jennijuju commented
This will be fip-0044

2022-08-04 00:40 UTC, jennijuju requested changes

2022-08-04 00:40 UTC, jennijuju commented on FIPS/fip-draft_authenticate_method.md
> +created: 2022-09-02
May i borrow your time machine?

2022-08-04 22:00 UTC, anorth commented on FIPS/fip-draft_authenticate_method.md
> +author: Alex North (@anorth), Aayush Rajasekaran (@arajasek)
Please list yourself as first author

2022-08-04 22:00 UTC, anorth commented on FIPS/fip-draft_authenticate_method.md
> +Unfortunately, today, the only kind of actors that can be asked to verify whether they have authorized a piece of data are account actors -- they do so through a signature validation.
"Authenticate" is the right term to use throughout this FIP. This is all about attesting to the authenticity of some message. Authorization refers to what some (authenticated) party is allowed to do (think ACLs). That's a topic for the party sending this message, not the receiver.

2022-08-04 22:00 UTC, anorth commented on FIPS/fip-draft_authenticate_method.md
> +approves of a piece of data. This is a small change to the existing actors, and allows for user-defined actors to flexibly implement this method according to their needs.
Mention the concrete actual change here, which is to the built-in account and storage market actors?

2022-08-04 22:00 UTC, anorth commented on FIPS/fip-draft_authenticate_method.md
> +to be landing on the Filecoin blockchain. Instead, a flexible, universal approach for actors to authorize data would be preferred.
Mention the concrete capability motivation of user actors being clients of the built-in market.

2022-08-04 22:00 UTC, anorth commented on FIPS/fip-draft_authenticate_method.md
> +```
Define the exit code to be returned if authentication fails?

2022-08-04 22:00 UTC, anorth commented on FIPS/fip-draft_authenticate_method.md
> +as a simpler replacement for FIP-0035, with the only drawback being that this proposal as currently written does not allow for multisigs to be storage clients. It would be trivial
```suggestion
as a simpler replacement for FIP-0035, with the only drawback being that this proposal as currently written does not allow for the existing built-in multisig actor to be a storage client. It would be trivial 
```

2022-08-08 19:01 UTC, kaitlin-beegle commented on FIPS/fip-draft_authenticate_method.md
> +fip: <to be assigned>
FIP0044 please

2022-08-08 19:05 UTC, kaitlin-beegle approved these changes

2022-08-22 17:14 UTC, arajasek commented on FIPS/fip-draft_authenticate_method.md
> +to be landing on the Filecoin blockchain. Instead, a flexible, universal approach for actors to authorize data would be preferred.
I do so in the previous paragraph, will move things around.

2022-08-22 18:28 UTC, Kubuxu commented
@arajasek did you maybe forgot to push a commit? There are a bunch of review comments marked as resolved which aren't.

2022-08-22 20:34 UTC, arajasek commented
@Kubuxu Got distracted and never pushed! Doing so now!

2022-08-22 20:36 UTC, arajasek commented
Now ready for another review.

2022-08-23 22:48 UTC, anorth approved these changes
In order to be a standard, we need a standard method number, which this FIP doesn't propose. I think that's ok, but we should discuss it. Mention that the intention is to re-export this method via a standard calling convention such as FRC-0042 or others that may emerge.

2022-08-23 22:48 UTC, anorth commented on FIPS/fip-0044.md
> +It would be trivial to add a similar `verify_authorization` method to the built-in multisig actor, though.
If it's trivial we should do it. I'm not sure it is.

2022-08-25 17:45 UTC, jennijuju approved these changes

2022-08-25 17:45 UTC, merged