WithdrawBalance fails when beneficiary is expired or out of quota
filecoin-project/FIPs pull request #454
Opened 2022-09-05 17:58 UTC by geoff-vball

2022-09-05 18:18 UTC, jennijuju requested changes

2022-09-05 18:18 UTC, jennijuju commented on FIPS/fip-0029.md
> +- If the **Beneficiary** is expired, or has used all of its **Quota**, then no withdrawls are possible until the beneficiary is updated or changed. Calls to **WithdrawBalance** will fail in this case
```suggestion
- If the ** BeneficiaryTerm** is expired, or has used all of its **Quota**, then no withdrawals are possible until the beneficiary is updated or changed. Calls to **WithdrawBalance** will fail in this case.
```

2022-09-05 18:19 UTC, jennijuju commented on FIPS/fip-0029.md
> +- If the **Beneficiary** is expired, or has used all of its **Quota**, then no withdrawls are possible until the beneficiary is updated or changed. Calls to **WithdrawBalance** will fail in this case
```suggestion
- If the **Beneficiary** is expired, or has used all of its **Quota**, then no withdrawls are possible until the beneficiary is updated or changed. Calls to **WithdrawBalance** will fail in this case, with `illegal_state`.
```

2022-09-05 21:30 UTC, anorth reviewed
I'm ok with this change.

I dunno what acceptable process is for changing an already-accepted FIP. The right time for this was the many months prior to acceptance, and during any of the two times this was initially implemented. But we shouldn't be too rigid either.

2022-09-05 21:30 UTC, anorth commented on FIPS/fip-0029.md
> +- If the ** BeneficiaryTerm** is expired, or has used all of its **Quota**, then no withdrawals are possible until the beneficiary is updated or changed. Calls to **WithdrawBalance** will fail in thi
Either USR_FORBIDDEN(18) or USR_INSUFFICIENT_FUNDS(19) would be better. Illegal state should not be used for things that can legitimately happen.

Please note explicitly that this behaviour is different to when the owner withdraws to themselves, where a withdrawal when 0 available will "succeed" to withdraw nothing (best effort).

2022-09-06 02:01 UTC, steven004 commented
I have no objection of this change, though I have a little (not strongly) different opinion. 
So, the reviewers, please feel free to approve it if you think it's fine. 

@anorth brought up a very good point about the change for an accepted proposal. We'd better to have one for future changes which might be needed for future FIPs. My suggestion is only for missed security issues or other major found mistakes.

2022-09-06 03:01 UTC, jennijuju commented
I feel like FIP authors should approve, or one or more core devs approve. this should not be a solely, or at all an fip editor decision.

2022-09-06 03:14 UTC, jennijuju commented
from @kaitlin-beegle in [slack](https://filecoinproject.slack.com/archives/C01EU76LPCJ/p1662433500804789?thread_ts=1662415392.474929&cid=C01EU76LPCJ)

> Great flag, thanks Jennifer.
> Is it correct to say that the change you seek to make is a technical change, discovered during implementation? Does the change substantively change the design, rationale, or problem statement of the FIP? I've reviewed, and it appears to be no. The proposed change necessarily takes into account a scenario which is probable but previously unaccounted for.  The change is necessary to properly implement the FIP.
> I also do not think this FIP needs an Active flag, since additional changes over time do not seem likely.
> My preference is that you amend the FIP in the repo, and we flag the change in the governance documentation (and potentially make a version note in the FIP itself). In the future, we will need more robust reviews to ensure these changes aren't needed, but I don't think we need a new FIP, etc. (e

2022-09-08 00:55 UTC, steven004 approved these changes

2022-09-08 06:05 UTC, jennijuju approved these changes

2022-09-08 06:06 UTC, jennijuju commented
merging as the author approved

2022-09-08 06:06 UTC, merged