Add market notify deal to 'other changes'
filecoin-project/FIPs pull request #566
Opened 2022-12-11 22:26 UTC by ZenGround0

Discussed here #549 
Prototyped here: https://github.com/filecoin-project/builtin-actors/pull/894/files

This change is small enough and aligned with the other FIP 50 changes that I think it belong here without lots of explanation.  It's up for discussion whether this should be its own FIP or if it needs more description.

2022-12-11 23:49 UTC, arajasek approved these changes

2022-12-11 23:49 UTC, arajasek commented on FIPS/fip-0050.md
> +- Modify MarketActor::PublichStorageDeals to call out to exported method `MarketNotifyDeal` for all deal clients
```suggestion
- Modify `MarketActor::PublishStorageDeals` to call out to exported method `MarketNotifyDeal` for all deal clients
```

2022-12-11 23:49 UTC, arajasek commented on FIPS/fip-0050.md
> +  - Errors are unchecked so client actor need not implement MarketNotifyDeal
```suggestion
  - Errors are unchecked so client actor need not implement `MarketNotifyDeal`
```

2022-12-12 02:47 UTC, jennijuju requested changes
Im not sure adding this api can go into this FIP, cuz unlike other apis, this one introduce behaviour changes into existing method, and may add on additional gas to the existing message.

requested change to block merge before we align on whether this needs a new fip (its gonna be a small one)

2022-12-12 03:58 UTC, ZenGround0 commented
This is a great point however I believe the gas change is small enough for this to be in scope:

The latest implementation of MarketNotifyDeal calling incurs minimal new compute from the PSD side when the proposal client is an account actor (the common case we want to avoid breaking).  It reuses the serialized results from the existing serialization for authenticate message and does a single send per client.  Sends are ~30k gas at syscall level.  Assuming 100 million gas for PSD that's less than 0.1 % of current gas costs.  

In the account case the client account actor will have to do a match and throw an error since the Account actor doesn't implement MarketNotifyDeal.  We can measure this but it should be quite small.  The only other thing from the account side is the new `restrict_internal_api` call which is also a new gas cost incurred by *all* methods.

2022-12-12 03:59 UTC, ZenGround0 commented
In short I will measure in a devnet and report back but don't think it's worth holding up this merge.

2022-12-12 04:45 UTC, jennijuju commented
I’m sold

2022-12-12 04:46 UTC, jennijuju approved these changes

2022-12-12 04:46 UTC, merged