FIP-0049 (actor events): align with implementation.
filecoin-project/FIPs pull request #581
Opened 2022-12-27 18:58 UTC by raulk

Mostly aligns FIP with the final implementation, adds a table of contents, product considerations. Missing gas costs.

2022-12-28 02:28 UTC, jennijuju requested changes

2022-12-28 02:28 UTC, jennijuju commented on FIPS/fip-0049.md
>  title: Actor events
```suggestion
title: Actor Events & Logs
```

2022-12-28 02:28 UTC, jennijuju commented on FIPS/fip-0049.md
>  This FIP adds the ability for actors to emit externally observable events during
```suggestion
This FIP adds the ability for actors to emit externally observable onchain events during
```

2022-12-28 02:28 UTC, jennijuju commented on FIPS/fip-0049.md
>  This FIP adds the ability for actors to emit externally observable events during
it is not clear to me what is "external" with the current description

2022-12-28 02:28 UTC, jennijuju commented on FIPS/fip-0049.md
> +that some relevant circumstance, action or transition has ocurred. Actor events
```suggestion
that some relevant state transition has occurred. Actor events
```

2022-12-28 02:28 UTC, jennijuju commented on FIPS/fip-0049.md
>  from execution. The payloads of events are self-describing objects signalling
```suggestion
from execution. The payloads of events are self-describing objects signaling
```

2022-12-28 02:28 UTC, jennijuju commented on FIPS/fip-0049.md
>  execution. Events are fire-and-forget, and can be thought of as a side effect
im not really getting the "side effect" analogy choice - can you elaborate more on why you chose this word? 

(wydt about "asynchronous state transition signal/trigger"?)

2022-12-28 02:28 UTC, jennijuju commented on FIPS/fip-0049.md
> +2. The upcoming introduction of the Filecoin Ethereum Virtual machine runtime
```suggestion
2. The upcoming introduction of the Filecoin Ethereum Virtual Machine(EVM) runtime
```

2022-12-28 02:28 UTC, jennijuju commented on FIPS/fip-0049.md
> +2. The upcoming introduction of the Filecoin Ethereum Virtual machine runtime
link to the FEVM fip plz

2022-12-28 02:28 UTC, jennijuju commented on FIPS/fip-0049.md
> +   JSON-RPC methods.
```suggestion
   JSON-RPC APIs to application/tooling developers.
```

2022-12-28 02:28 UTC, jennijuju commented on FIPS/fip-0049.md
> +   JSON-RPC methods.
```suggestion
   JSON-RPC APIs to application/tooling developers.
```

2022-12-28 02:28 UTC, jennijuju commented on FIPS/fip-0049.md
> +We introduce a DAG-CBOR encoded `StampedEvent` type to represent an actor event
```suggestion
We introduce a[ DAG-CBOR](https://github.com/ipld/specs/blob/master/block-layer/codecs/dag-cbor.md) encoded `StampedEvent` type to represent an actor event
```

2022-12-28 02:28 UTC, jennijuju commented on FIPS/fip-0049.md
> +as committed on chain.
```suggestion
as emitted on chain.
```

2022-12-28 03:11 UTC, jennijuju requested changes

2022-12-28 03:11 UTC, jennijuju commented on FIPS/fip-0049.md
>  **Event examples**
lets add an example where the value is indexed?

2022-12-28 03:11 UTC, jennijuju commented on FIPS/fip-0049.md
> +During message call stack execution, DAG-CBOR encoded `Event`s are accumulated
"call stack" as in including all internal tx as well?

2022-12-28 03:11 UTC, jennijuju commented on FIPS/fip-0049.md
>  committed to the chain state with no futher structural changes needed.
```suggestion
emitted to the chain state with no further structural changes needed.
```

2022-12-28 03:11 UTC, jennijuju commented on FIPS/fip-0049.md
> +message execution, the AMT is flushed into the FVM's (buffered) blockstore, and
if the message execution is failed - does all the events accumulated so far got flushed?

2022-12-28 03:11 UTC, jennijuju commented on FIPS/fip-0049.md
>  > TODO need to make syscall gas dynamic based on param length
❗ todo is needed before moving to last call

2022-12-28 03:11 UTC, jennijuju commented on FIPS/fip-0049.md
> +events for meaningful transitions and circumstances. This would allow
```suggestion
events for meaningful state transitions. This would allow
```

2022-12-28 03:11 UTC, jennijuju commented on FIPS/fip-0049.md
> +events for meaningful transitions and circumstances. This would allow
```suggestion
events for meaningful state transitions. This would allow
```

2022-12-28 03:11 UTC, jennijuju commented on FIPS/fip-0049.md
> +A project tackling this mission should begin by inventorizing all situations
Probably off-topic, tho for builtin actors' events, we shall think about who pays for events' emissions & why..

2022-12-28 03:11 UTC, jennijuju commented on FIPS/fip-0049.md
> +### Client handling
can you link a impl for indexing?

2022-12-28 12:06 UTC, raulk commented on FIPS/fip-0049.md
>  title: Actor events
Is this a personal style comment or is there a rule that I've overlooked? I would keep as-is unless there's clear justification. The recommended style in scientific writing is lower case nouns for theories, concepts, etc.

2022-12-28 12:09 UTC, raulk commented on FIPS/fip-0049.md
> +that some relevant circumstance, action or transition has ocurred. Actor events
Can you please explain your suggestion here, @jennijuju? (Generally, for all other comments, please explain your suggestion unless it's a typo). We **do not** want to limit actor events to state transitions only. For example, a forbidden action could not result in a state transition, but still be recorded as an event (e.g. `TokenTransferDenied`).

2022-12-28 12:17 UTC, raulk commented on FIPS/fip-0049.md
> +2. The upcoming introduction of the Filecoin Ethereum Virtual machine runtime
Once it's merged as a draft, I will post it here. I won't link to a PR.

2022-12-28 12:19 UTC, raulk commented on FIPS/fip-0049.md
> +   JSON-RPC methods.
I suspect you are intending to add more colour here.

The problem is that JSON-RPC APIs are not serving data to _developers_ (the people), but to external agents, so this is imprecise.

I will add the "external" keyword, that's sufficient.

2022-12-28 12:19 UTC, raulk commented on FIPS/fip-0049.md
> +   JSON-RPC methods.
(Although JSON-RPC implies external...)

2022-12-28 12:19 UTC, raulk commented on FIPS/fip-0049.md
> +   JSON-RPC methods.
Duplicated comment.

2022-12-28 12:20 UTC, raulk commented on FIPS/fip-0049.md
> +We introduce a DAG-CBOR encoded `StampedEvent` type to represent an actor event
Spacing in the suggestion is wrong, so I can't accept it as-is. I'm also using the lookup link format, so I will add it to the bottom.

2022-12-28 12:21 UTC, raulk commented on FIPS/fip-0049.md
> +as committed on chain.
No, that's incorrect.

2022-12-28 12:21 UTC, raulk commented on FIPS/fip-0049.md
> +    /// Carries the actor ID of the emitting actor (stamped by the FVM).
No, that's incorrect. This carries the actor ID, not the actor's ID address.

2022-12-28 12:24 UTC, raulk commented on FIPS/fip-0049.md
>  Over time, we expect the community to standardise on a set of keys through FRC
The keys. There's an example below in _Multisig approval_.

2022-12-28 12:24 UTC, raulk commented on FIPS/fip-0049.md
> +Payloads are DAG-CBOR encoded types.
The spec? Or a link to the spec? I've added the latter, but I won't add the full spec here, it makes no sense.

2022-12-28 12:25 UTC, raulk commented on FIPS/fip-0049.md
>      emitter: 1260,
No, it's an actor ID, not an ID address.

2022-12-28 12:26 UTC, raulk commented on FIPS/fip-0049.md
> +    entries: [  // all entries indexed, with type as key
No, the type of the event is specified as a key.

2022-12-28 12:26 UTC, raulk commented on FIPS/fip-0049.md
>      emitter: 1678,
No, see above.

2022-12-28 12:27 UTC, raulk commented on FIPS/fip-0049.md
> +    flags: u64,
No, this value carries multiple flags in the form of bitflags/bitmask.

2022-12-28 12:27 UTC, raulk commented on FIPS/fip-0049.md
>  **Event examples**
Hm, can do.

2022-12-28 12:27 UTC, raulk commented on FIPS/fip-0049.md
> +During message call stack execution, DAG-CBOR encoded `Event`s are accumulated
Yes.

2022-12-28 12:28 UTC, raulk commented on FIPS/fip-0049.md
>  committed to the chain state with no futher structural changes needed.
No, `commit` is the right word here, `emit` changes the meaning to an inaccurate one. Thanks for the typo fix, I've fixed it.

2022-12-28 12:28 UTC, raulk commented on FIPS/fip-0049.md
> +events for meaningful transitions and circumstances. This would allow
Rejected as per above comments.

2022-12-28 12:29 UTC, raulk commented on FIPS/fip-0049.md
> +events for meaningful transitions and circumstances. This would allow
Rejected as per above comments.

2022-12-28 12:30 UTC, raulk commented on FIPS/fip-0049.md
>  from execution. The payloads of events are self-describing objects signalling
North Americans... :D

2022-12-28 12:30 UTC, raulk commented on FIPS/fip-0049.md
>  become the source of internal message triggers.
Note: "Internal transaction" is an imprecise term and I'm not aware of us using it at all (if it's used somewhere, it should be revised). Rationale: a transaction is a single unit of execution, which in our system can only be the external (on-chain) message. 

An internal message is a send from one actor to another.

2022-12-28 12:31 UTC, raulk commented on FIPS/fip-0049.md
>  become the source of internal message triggers.
This is a speculative feature, and this means that an actor event could lead to a send.

2022-12-28 14:42 UTC, raulk commented on FIPS/fip-0049.md
> +message execution, the AMT is flushed into the FVM's (buffered) blockstore, and
Good call, specified the behaviours on the various exit codes.

2022-12-28 14:45 UTC, raulk commented on FIPS/fip-0049.md
> +A project tackling this mission should begin by inventorizing all situations
These can only be paid for by gas. Gas is paid by the caller. I think the question you're hinting at is: "why would the caller subsidize the monitoring operations of third parties?" I don't think this is any different than the rationale of why callers pay for events in other chains. We're just being confronted with this question because we are introducing events after contracts already exist that would've benefitted from those events from day 0, so we have a sensation of optionality here.

2022-12-28 14:46 UTC, raulk commented on FIPS/fip-0049.md
>      emitter: 101,
No.

2022-12-28 14:46 UTC, raulk commented on FIPS/fip-0049.md
> +| `0x02` | `b00000010` | indexed by value |
Added.

2022-12-28 14:50 UTC, raulk commented on FIPS/fip-0049.md
> +### Client handling
It's not on master yet, so unsafe to link. I will add a PR link, but generally not happy doing that.

2022-12-30 03:39 UTC, mriise commented on FIPS/fip-0049.md
>  is inspired by structured logging concepts. **Keys** are strings, while
```suggestion
is inspired by structured logging concepts. **Keys** are utf-8 strings, while
```
All strings in rust are utf-8 (if we are sticking to the String types and not just bytes)

2022-12-30 03:39 UTC, mriise commented on FIPS/fip-0049.md
> +Flags are additive, such that value 0x03 (`b00000011`) indicates that the entry
Is the additive property something we are enforcing for future flags as well or is it just the current state of things?

2022-12-30 03:39 UTC, mriise commented on FIPS/fip-0049.md
> +must be indexed by both key and value.
Must? Below it describes flags as being client hints that _should_ be done.

2022-12-30 03:39 UTC, mriise commented on FIPS/fip-0049.md
>  The following examples demonstrate how to use these structures in practice.
```suggestion
The following examples demonstrate these structures in practice.
```

2022-12-30 03:39 UTC, mriise commented on FIPS/fip-0049.md
>      emitter: 1260,
```suggestion
    emitter: <actor id>,
```

2022-12-30 03:39 UTC, mriise commented on FIPS/fip-0049.md
>      emitter: 101,
```suggestion
    emitter: <actor id>,
```

2022-12-30 03:39 UTC, mriise commented on FIPS/fip-0049.md
> +// type, sender, receiver indexed.
```suggestion
// type, sender, and receiver indexed by key and value.
```

2022-12-30 03:39 UTC, mriise commented on FIPS/fip-0049.md
> +        (0x00, "amount", <token amount in atto precision>),
```suggestion
        (0x00, "amount", <token amount in atto precision>), // Not indexed.
```

2022-12-30 03:39 UTC, mriise commented on FIPS/fip-0049.md
> +    emitter: 480,
```suggestion
    emitter: <actor id>,
```

2022-12-30 03:39 UTC, mriise commented on FIPS/fip-0049.md
> +// only type and signers indexed; signer is a variadic entry.
```suggestion
// Only type and signers indexed; signer is a variadic entry.
```

2022-12-30 03:39 UTC, mriise commented on FIPS/fip-0049.md
>      emitter: 1678,
```suggestion
    emitter: <actor id>,
```

2022-12-30 03:39 UTC, mriise commented on FIPS/fip-0049.md
> +implementation](https://github.com/filecoin-project/ref-fvm/blob/master/testing/integration/tests/events_test.rs).
```suggestion
implementation](https://github.com/filecoin-project/ref-fvm/blob/master/testing/integration/tests/events_test.rs). [permalink](https://github.com/filecoin-project/ref-fvm/blob/d8f5d86f28ecd03a9934240134dae83a9754f72e/testing/integration/tests/events_test.rs)
```

2022-12-30 11:20 UTC, raulk commented on FIPS/fip-0049.md
>  is inspired by structured logging concepts. **Keys** are strings, while
UTF-8 encoding is implied by CBOR.

2022-12-30 11:21 UTC, raulk commented on FIPS/fip-0049.md
> +Flags are additive, such that value 0x03 (`b00000011`) indicates that the entry
Specifications are usually written perennially unless otherwise specified.

2022-12-30 11:22 UTC, raulk commented on FIPS/fip-0049.md
>  The following examples demonstrate how to use these structures in practice.
No, these examples demonstrate _usage_.

2022-12-30 11:22 UTC, raulk commented on FIPS/fip-0049.md
>      emitter: 1260,
No, these are _concrete examples_ not templates.

2022-12-30 11:24 UTC, raulk commented on FIPS/fip-0049.md
> +must be indexed by both key and value.
Will lower language.

2022-12-30 11:27 UTC, raulk commented on FIPS/fip-0049.md
>      emitter: 101,
I'm OK making payloads placeholders (as they are user defined), but not data stamped by the protocol.

2022-12-30 11:27 UTC, raulk commented on FIPS/fip-0049.md
> +    emitter: 480,
I'm OK making payloads placeholders (as they are user defined), but not data stamped by the protocol.

2022-12-30 11:28 UTC, raulk commented on FIPS/fip-0049.md
>  is inspired by structured logging concepts. **Keys** are strings, while
Will add if it makes you happy (but with the right capitalization, i.e. UTF-8, since we're in heavy bikeshedding territory)

2022-12-30 19:51 UTC, jennijuju commented on FIPS/fip-0049.md
>  title: Actor events
Nope - not personal style. It's a pattern that past FIPs have been used + FIP-0001 does the same https://github.com/filecoin-project/FIPs/tree/master/FIPS

2022-12-30 19:57 UTC, jennijuju commented on FIPS/fip-0049.md
> +    /// Carries the actor ID of the emitting actor (stamped by the FVM).
Can you specify what actor ID is then?  I cannot find any definition in [filecoin spec](https://spec.filecoin.io) or in any past FIPs. The spec only have mentioned `actor id address`

2022-12-30 19:57 UTC, jennijuju commented on FIPS/fip-0049.md
> +Payloads are DAG-CBOR encoded types.
yes link is fine.

2022-12-30 19:57 UTC, jennijuju commented on FIPS/fip-0049.md
>      emitter: 1260,
same question as above - not sure what an actor ID is, and how is an value assigned.

2022-12-30 20:09 UTC, raulk commented on FIPS/fip-0049.md
>  title: Actor events
Happy to e=>E if it gets this merged...

2022-12-30 20:12 UTC, raulk commented on FIPS/fip-0049.md
> +    /// Carries the actor ID of the emitting actor (stamped by the FVM).
The actor ID is the internal identifier of the actor in the state tree, and the payload of the ID address. If it's not specified in the spec, it needs to be fixed there. I can add a footnote if others share this concern, but anybody reading this spec should know what an actor ID is (prerequired knowledge).

2022-12-30 20:21 UTC, jennijuju commented on FIPS/fip-0049.md
> +that some relevant circumstance, action or transition has ocurred. Actor events
AFAIK, (in etherum), any actions that cause a failed message execution will lead to all state changes to be reverted, including the events. (quick google verification, [here](https://ethereum.stackexchange.com/questions/90535/will-event-be-emitted-on-failed-transaction))

> We do not want to limit actor events to state transitions only. For example, a forbidden action could not result in a state transition,

In this example, according to the definition below: _When an actor exits abnormally (exit code > 0), events emitted from that invocation and its transitive callee are discarded._ Could you please provide an example that a forbidden action in actors that will result in an exit code =0 (successful execution?)

2022-12-30 20:29 UTC, jennijuju commented on FIPS/fip-0049.md
> +    /// Carries the actor ID of the emitting actor (stamped by the FVM).
hrm, Im also not able to find any reference in spec-actor or go-state-types about actor ID. Ive been working on Filecoin for two years, tho it's certain that I still have unknown knowledge of this complicated system!  @raulk or other @filecoin-project/fips-editors , can one of you help me find a reference or explanation on this plz?

2022-12-30 20:35 UTC, jennijuju commented on FIPS/fip-0049.md
>  title: Actor events
lolol

2022-12-30 20:35 UTC, jennijuju commented on FIPS/fip-0049.md
>  title: Actor events
hahah

2022-12-30 20:45 UTC, jennijuju commented on FIPS/fip-0049.md
>  become the source of internal message triggers.
> An internal message is a send from one actor to another.

\ I think we use "internal invocation" more often but its not specifically defined, internal messages also make sense to me

2022-12-30 20:47 UTC, jennijuju commented on FIPS/fip-0049.md
> +as committed on chain.
elaborate why please? what is an committed event and whats an emitted event?

2022-12-30 20:52 UTC, jennijuju commented
@kaitlin-beegle  - I'd like either @anorth or @arajasek to review this FIP before we move this DRAFT to LAST CALL, thanks!

2023-01-03 13:37 UTC, maciejwitowski commented on FIPS/fip-0049.md
> +However, this FIP restricts accepted types to byte strings only (CBOR major type
I had to jump to go back to the sentence above to understand what `types` refers to. Maybe consider changing to "types of values" or "values' types"?

2023-01-03 14:46 UTC, raulk commented on FIPS/fip-0049.md
> +However, this FIP restricts accepted types to byte strings only (CBOR major type
Thanks, will adjust the prose.

2023-01-03 14:47 UTC, raulk commented on FIPS/fip-0049.md
> +However, this FIP restricts accepted types to byte strings only (CBOR major type
Fixed in 05f693f.

2023-01-05 20:19 UTC, anorth approved these changes
Looks good except:
- Gas cost parameters are still TODO

2023-01-05 20:19 UTC, anorth commented on FIPS/fip-0049.md
> +**NOTE: value types not supported yet.**
```suggestion
**NOTE: value types other than byte string are not supported yet.**
```

And ditto below

2023-01-05 20:19 UTC, anorth commented on FIPS/fip-0049.md
> +        (0x01, "transfer", null),
Nit: why is this inconsistent with the fungible token transfer using ("type", "transfer")?

2023-01-05 20:19 UTC, anorth commented on FIPS/fip-0049.md
> +they're responsible for managing receipts.
The correctness of this is dubious. The VM might not write, but the node probably does, or certainly could, in order to support subsequent queries. I think this paragraph could just be dropped without loss.

2023-01-05 20:19 UTC, anorth commented on FIPS/fip-0049.md
> +sweet spot that strikes the optimal balance between value and cost.
Nit: this paragraph is unnecessary here IMO

2023-01-06 18:42 UTC, jennijuju commented on FIPS/fip-0049.md
> +    /// Carries the actor ID of the emitting actor (stamped by the FVM).
@raulk and I did a walk through here and found out that the we actually store ID address in the state trees for most filecoin things. The exception here is the recently added datacap actor. And we use ID addresses  in the clients - thats where the confusion was coming from. chatting with aayush and steb, we think it is worth considering to do a migration and use `ActorID` in places.

2023-01-06 18:43 UTC, jennijuju commented
I lifted my `change request`, however, there are still resolved conversation on this PR that I think authors should consider before we move it to last call.

2023-01-08 20:30 UTC, anorth commented
@raulk ping us when you've pushed any final edits and I can merge (overriding branch protection) or @jennijuju can approve (necessary to unblock merging).

2023-01-08 20:45 UTC, jennijuju approved these changes

2023-01-09 11:37 UTC, raulk commented on FIPS/fip-0049.md
> +**NOTE: value types not supported yet.**
Fixed in d002339.

2023-01-09 11:42 UTC, raulk commented on FIPS/fip-0049.md
> +        (0x01, "transfer", null),
I added this example with a different key-value style to demonstrate a usage of the "index by key" flag. Since user code will pay per byte, I expect devs will come up with ways to produce compact event representations without information loss. On an abstract level, this follows this pattern for a schema:

```json
{ "transfer": { "sender": 1111, "receiver": 2222, "token_id": "0x12345678" }  }
```

As opposed to:

```json
{ "type": "transfer", "sender": 1111, "receiver": 2222, "token_id": "0x12345678" } 
```

2023-01-09 11:50 UTC, raulk commented on FIPS/fip-0049.md
> +sweet spot that strikes the optimal balance between value and cost.
I would like to retain some form of an consideration here on the value/cost balance, and the need for community discussion on what kinds of events would give the most bang for the buck.

- Events benefit observability tools.
- They do not benefit the message sender, who pays for the gas expenditures that those events incur. In a way, users are subsidizing the operating cost of observability tools.
- Built-in actors are of compulsory usage in the system. Users cannot choose alternative, cheaper implementations that could've emerged from open competition.

However, I can also move this thought to the discussion if it makes us feel better: https://github.com/filecoin-project/FIPs/discussions/484

2023-01-09 13:53 UTC, raulk commented on FIPS/fip-0049.md
> +they're responsible for managing receipts.
Which part is incorrect? The FVM certainly does not write receipts, so writing the event AMTs would lead to a dangling write since they would be unreferenced unless the client writes the receipt.

2023-01-09 13:53 UTC, raulk commented on FIPS/fip-0049.md
> +they're responsible for managing receipts.
Basically what this is saying is: "look client, you're responsible for managing receipts, and that includes events."

2023-01-09 13:54 UTC, merged

2023-01-13 03:39 UTC, jennijuju commented on FIPS/fip-0049.md
> +that some relevant circumstance, action or transition has ocurred. Actor events
Still seeking for an explanation.