Update fip-0059.md
filecoin-project/FIPs pull request #737
Opened 2023-06-22 14:07 UTC by luckyparadise

2023-06-22 19:54 UTC, anorth commented
@filecoin-project/fips-editors please land #731 first.

2023-06-30 18:07 UTC, cryptonemo approved these changes
Pending #731

2023-06-30 19:22 UTC, kaitlin-beegle approved these changes

2023-07-02 21:42 UTC, anorth requested changes
#731 is landed, but this needs to be redone so as not to undo that change.

2023-07-13 22:18 UTC, closed without merging