Draft of Removing Restriction to Access to Multiplier and Allowing Unrestricted Minting of Datacap
filecoin-project/FIPs pull request #803
Opened 2023-08-23 08:18 UTC by dcasem

Draft of Removing Restriction to Access to Multiplier and Allowing Unrestricted Minting of Datacap (FCM Option)

2023-08-23 20:21 UTC, anorth commented on FIPS/FIL+ FIP.md
> +# FIPXXXX: Phasing Out Fil+ and Restoring Deal Quality Multiplier to 1x
You appear to have inadvertently included the file from #788 in this PR as well. I assume it's not intended. Can you remove it here (it should stay in #788)?

2023-08-26 03:11 UTC, anorth commented
This proposal is technically well specified and implementable. It's kinda light on motivation and analysis of impacts, but much of that is present in the discussion. I do appreciate this brevity vs copy-pasting the discussion post into the FIP. We might want a _little_ more included inline before we could consider this final, but as a first draft this is describing a pretty clear change.

2023-08-30 01:11 UTC, jennijuju commented on FIPS/fip-FCM.md
> +This proposal aims to remove restrictions associated with the 10X multiplier in Fil+ deals and allow any actor to mint Datacap, promoting decentralization and simplifying the Filecoin ecosystem.
The title suggests "Removing Restriction to Access to Multiplier" & "Remove restrictions associated with the 10X multiplier in Fil+ deals"  - what does this mean? 

are you suggesting who may call `AddVerifier` and `AddVerifiedClient`

2023-08-30 01:13 UTC, jennijuju commented on FIPS/fip-FCM.md
> +The Fil+ program was designed to encourage high-quality storage on the Filecoin network. The current proposal intends to remove complexities that have arisen from its initial conception, thereby ensu
High-quality storage sounds ambiguous to me, as one can also provide "high quality" committed capacity storage on Filecoin.

2023-08-30 01:16 UTC, jennijuju commented on FIPS/fip-FCM.md
> +The current Fil+ implementation, though well-intentioned, has added complexities that deviate from Filecoin's core mission. Simplifying this system will encourage the onboarding of genuine data and u
Can you elaborate on the complexities and the issue/challenges associated with them?  (They were discussed in the discussed, lets summarize the points that your proposal can resolve. We should ensure FIP readers may get enough context without going through the whole fip discussion)

2023-08-30 01:22 UTC, jennijuju commented on FIPS/fip-FCM.md
> +Allowing any actor to mint datacap is the simplest change to the current protocol that removes the Fil+ process restrictions on datacap issuance. This datacap can then be transferred to the verified
```suggestion
Allowing any actor to mint datacap is the simplest change to the current protocol that removes the Fil+ process restrictions on datacap issuance. Datacap can then be transferred to the verified registry to create a datacap allocation. Storage Providers can claim the allocation assigned to them and get the associated 10x deal multiplier when onboarding the data piece.
```

2023-08-30 01:24 UTC, jennijuju commented on FIPS/fip-FCM.md
> +After this change, the verified registry and datacap actors will be mostly obsolete. Allowing unlimited datacap does not create any complexity, but does make it possible to remove some. Future protoc
as suggested above - specify the complexity it addresses and how plz

2023-08-30 01:31 UTC, jennijuju commented on FIPS/fip-FCM.md
> +This FIP, though providing simplified access, doesn't introduce new security threats.
I think we will need analysis on this -what is the cost for any/group of malicious actors  to mint large amount of the data cap and onboarding CC sectors with the 10x multiplier and get>30% of the network QAP.

2023-08-30 01:32 UTC, jennijuju commented on FIPS/fip-FCM.md
> +The proposed change effectively removes a significant incentive for the onboarding of data that was previously determined as valuable by the off-chain notaries under the Fil+ mechanism. As a result,
>As a result, it's anticipated that the overall rate of data onboarding may decrease

Are you suggesting that this FIP, will reduce the network storage utility?

2023-08-30 01:33 UTC, jennijuju commented on FIPS/fip-FCM.md
> +With the removal of the restriction, effectively-empty sectors can now benefit from a multiplier. This adjustment allows Storage Providers (SPs) to onboard more Raw Byte Power (RPB) at a potential pr
```suggestion
With the removal of the restriction, effectively-empty (a.k.a committed capacity) sectors can now benefit from a multiplier. This adjustment allows Storage Providers (SPs) to onboard more Raw Byte Power (RPB) at a potential profit, potentially leading to an increase in such sectors being onboarded.
```

2023-08-30 01:37 UTC, jennijuju commented on FIPS/fip-FCM.md
> +With the removal of the restriction, effectively-empty sectors can now benefit from a multiplier. This adjustment allows Storage Providers (SPs) to onboard more Raw Byte Power (RPB) at a potential pr
> With the removal of the restriction, effectively-empty sectors can now benefit from a multiplier. This adjustment allows Storage Providers (SPs) to onboard more Raw Byte Power (RPB) at a potential profit, potentially leading to an increase in such sectors being onboarded.

please elaborate what are the incentives that will bring to the network/SP by enabling onboard more CC/RBP and drive towards potential profit.

2023-08-30 01:37 UTC, jennijuju commented on FIPS/fip-FCM.md
> +Clients and Storage Providers will experience a streamlined interaction with the Filecoin network, which could lead to more user-friendly products and services built on top of Filecoin.
https://github.com/filecoin-project/FIPs/pull/803/files#r1309506511

2023-08-30 01:38 UTC, jennijuju commented on FIPS/fip-FCM.md
> +The proposed changes present SPs with a more flexible environment, allowing them to select a pledge-to-hardware ratio best aligned with the specific costs and benefits they encounter. This enhanced f
Could you please add how would the proposed change impact the data client?

2023-08-30 01:41 UTC, jennijuju commented on FIPS/fip-FCM.md
> +Discussions-to: https://github.com/filecoin-project/FIPs/discussions/774
I would suggest we create a new FIP discussion just for this proposed solution

2023-08-30 04:31 UTC, anorth commented on FIPS/fip-FCM.md
> +This proposal aims to remove restrictions associated with the 10X multiplier in Fil+ deals and allow any actor to mint Datacap, promoting decentralization and simplifying the Filecoin ecosystem.
I don't think any change to AddVerifier/Client is needed to accomplish the authors goal here. Those only serve to funnel the datacap minting process through the verifreg. Am I missing something?

2023-08-30 04:33 UTC, anorth commented on FIPS/fip-FCM.md
> +After this change, the verified registry and datacap actors will be mostly obsolete. Allowing unlimited datacap does not create any complexity, but does make it possible to remove some. Future protoc
I don't think this FIP has any place to specify how a future FIP should do that. It's enough to point out that it will be possible.

2023-08-30 04:37 UTC, anorth commented on FIPS/fip-FCM.md
> +After this upgrade, Storage Providers (SPs) can engage with any deal, whether Fil+ or not by minting Datacap. Deals will still need the `verified` flag set to true, but clients will be able to freely
Good point. This is currently acheived by `AddVerifiedClient` (which should really be called AddDataCapToVerifiedClient). _Instead_ of that, clients (or anyone) will need to mint the datacap by explicitly invoking the Datacap actor's `mint` method. The old methods all still work, there's no backwards incompatibility. But the new flow uses a more direct method (the client can mint their own instead of requiring a verifier to do it for them).

2023-08-30 04:39 UTC, anorth commented on FIPS/fip-FCM.md
> +The proposed change effectively removes a significant incentive for the onboarding of data that was previously determined as valuable by the off-chain notaries under the Fil+ mechanism. As a result,
@jennijuju what is the editorial change you are requesting before considering this a valid FIP draft?

2023-08-30 04:40 UTC, anorth commented on FIPS/fip-FCM.md
> +With the removal of the restriction, effectively-empty sectors can now benefit from a multiplier. This adjustment allows Storage Providers (SPs) to onboard more Raw Byte Power (RPB) at a potential pr
@jennijuju they won't be CC sectors. They will have (self-)deals in them because that's how to onboard the datacap.

2023-08-30 04:41 UTC, anorth commented on FIPS/fip-FCM.md
> +With the removal of the restriction, effectively-empty sectors can now benefit from a multiplier. This adjustment allows Storage Providers (SPs) to onboard more Raw Byte Power (RPB) at a potential pr
This would actually be a strong motivation to follow on with the clean-up work of removing datacap and verifreg if this FIP is accepted.

2023-08-30 04:42 UTC, anorth commented on FIPS/fip-FCM.md
> +With the removal of the restriction, effectively-empty sectors can now benefit from a multiplier. This adjustment allows Storage Providers (SPs) to onboard more Raw Byte Power (RPB) at a potential pr
The incentive to onboard is just block rewards, the same incentive currently for onboarding 10x sectors today.

2023-08-30 04:51 UTC, kaitlin-beegle requested changes

2023-08-30 04:51 UTC, kaitlin-beegle commented on FIPS/fip-FCM.md
> +title: "Removing Restriction to Access to Multiplier and Allowing Unrestricted Minting of Datacap"
For my own clarity (apologies if it's been mentioned elsewhere, but it's not clear in the PRs)- can you explain how we should understand this FIP, as it relates to #788? I haven't had time to closely follow the discussion, which is happening across multiple spheres.  I assume you opened this PR as an acceptable alternative to #788?

2023-08-30 04:51 UTC, kaitlin-beegle commented on FIPS/fip-FCM.md
> +This proposal aims to remove restrictions associated with the 10X multiplier in Fil+ deals and allow any actor to mint Datacap, promoting decentralization and simplifying the Filecoin ecosystem.
[editorial nit...not a big deal].  

I would remove the "promoting decentralization and simplifying the Filecoin ecosystem" piece of this.  It's not necessary.

I would simply state: "This proposal aims to remove restrictions associated with the 10x multiplier offered to Fil+ deals.  Specifically, it does so by allowing any actor to mint Datacap so long as....[insert condition here].

2023-08-30 04:51 UTC, kaitlin-beegle commented on FIPS/fip-FCM.md
> +The Fil+ program was designed to encourage high-quality storage on the Filecoin network. The current proposal intends to remove complexities that have arisen from its initial conception, thereby ensu
^^ I think a lot of this language is ambiguous.  

If the simple summary gives a 1-2 sentence overview of the changes you want, the abstract should add a bit more detail about why. Saying that you want to "remove complexities" and "ensure the Filecoin mission is better represented" is a unclear.  Just say **what** the complexities are, and **how** your proposed changes service the Filecoin mission. 

Re: @jennijuju's points above, one definition that you can use for Fil+ is the one in FIP0003: "... maximize the amount of useful storage that Filecoin can and will support." 

I want to help you avoid vagueness as much as possible.  If you have vague language and terms in your FIP draft, it makes it harder to navigate the soft consensus/last call process.

2023-08-30 04:51 UTC, kaitlin-beegle commented on FIPS/fip-FCM.md
> +## Incentive Considerations
I still have some hesitation about the doneness of this proposal, and I think it has to do with this section. 

@jennijuju and I each flagged above that we'd like more specific language, specifically where "complexities" and "simplification" are referenced. 

I'd also like to see a bit more documentation about _the assumptions/observations driving this desired change_, and _what it actually means for anyone to be able to mint datacap_. I know what they are, and they've been well discussed by folks engaging on this discussion topic.  Those details should at least be summarized here as well (or below in Product Considerations; doesn't matter too much). 

This FIP should not just direct implementers, but should also justify and explain the policy. It would be great for you to add a few sentences about how those minting datacap will (presumably) be opting for higher collateral rates, and why they may choose to do so.  Why would people choose to mint datacap if its otherwise available to everyone? Or rather, why would someone NOT mint datacap if it's giving them a 10x multiplier? Etc. 

I know you know these things; they should be here too.

2023-08-30 07:42 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +The current Fil+ implementation, though well-intentioned, has added complexities that deviate from Filecoin's core mission. Simplifying this system will encourage the onboarding of genuine data and u
The motivation for this FIP is less the complexities of FIL+ and more that it’s permissioned.

We talked about this at length in 774.

2023-08-30 07:46 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +title: "Removing Restriction to Access to Multiplier and Allowing Unrestricted Minting of Datacap"
Yes, this is an alternative.

2023-08-30 07:48 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +Discussions-to: https://github.com/filecoin-project/FIPs/discussions/774
Create a new discussion, miss the deadline, and then have to go through another 6 months of permissioned nonsense.

No.

2023-08-30 07:51 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +The proposed changes present SPs with a more flexible environment, allowing them to select a pledge-to-hardware ratio best aligned with the specific costs and benefits they encounter. This enhanced f
The SPs are the real users of the network at the moment because they pay for the vast, vast majority of Filecoin blockspace / transaction fees.

2023-08-30 08:00 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +This proposal aims to remove restrictions associated with the 10X multiplier in Fil+ deals and allow any actor to mint Datacap, promoting decentralization and simplifying the Filecoin ecosystem.
I would replace 

> promoting decentralization and simplifying the Filecoin ecosystem.

with

> thus making Filecoin permissionless again.

2023-08-30 08:02 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +The Fil+ program was designed to encourage high-quality storage on the Filecoin network. The current proposal intends to remove complexities that have arisen from its initial conception, thereby ensu
I would replace

> The current proposal intends to remove complexities that have arisen from its initial conception, thereby ensuring the Filecoin mission is better represented and uncomplicated.

with

> the current proposal intends to remove the permissioned notary system, ensuring that Filecoin remains decentralized and fair.

2023-08-30 08:09 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +The current Fil+ implementation, though well-intentioned, has added complexities that deviate from Filecoin's core mission. Simplifying this system will encourage the onboarding of genuine data and u
I would replace

> The current Fil+ implementation, though well-intentioned, has added complexities that deviate from Filecoin's core mission. Simplifying this system will encourage the onboarding of genuine data and uphold the integrity of the Filecoin blockchain.

with

> The current Fil+ implementation, though well-intentioned, has created an uneven playing field for SPs, permissioned the chain, and encouraged undesirable behaviors like bribery and false accusations. Our proposal makes Filecoin fully permissionless. It will remove these problems and restore confidence in the integrity and neutrality of our consensus algorithm

2023-08-30 09:27 UTC, ArthurWang1255 commented on FIPS/fip-FCM.md
> +The proposed changes present SPs with a more flexible environment, allowing them to select a pledge-to-hardware ratio best aligned with the specific costs and benefits they encounter. This enhanced f
Filecoin is a blockchain, and the users of a blockchain are those who hold and consume Filecoin through gas. The impact to data clients are not directly related to the filecoin core protocol. IMHO, the fertility of RBP and SPs is what needs to be considered in a fip.

2023-08-30 09:32 UTC, ArthurWang1255 commented on FIPS/fip-FCM.md
> +This FIP, though providing simplified access, doesn't introduce new security threats.
The security of the network will actually be increased by the fip. In the past, only 1/10 of the hardware + enough DC was needed to do evil. Now it needs 1:1 hardware to be evil.

2023-08-30 10:02 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +The proposed changes present SPs with a more flexible environment, allowing them to select a pledge-to-hardware ratio best aligned with the specific costs and benefits they encounter. This enhanced f
Agree with Arthur.

A fair, transparent chain with a lower barrier to entry will attract more SPs.
All else equal that should mean more storage, cheaper storage, and better storage.

The notary system doesn't incentivize useful storage.
It incentivizes bribery and fraud.
The scale and sophistication of the fraud/bribery just increases with the size of the bureaucracy.

2023-08-30 19:18 UTC, kaitlin-beegle commented on FIPS/fip-FCM.md
> +replaces:
Please specify that this would need to replace FIP0003.

2023-08-30 23:39 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +replaces:
Sure

2023-08-30 23:47 UTC, The-Wayvy requested changes

2023-08-30 23:47 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +replaces:
replaces FIP0003

2023-08-31 00:16 UTC, The-Wayvy requested changes

2023-08-31 00:16 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +replaces:
replaces: FIP0003

2023-08-31 00:16 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +This proposal aims to remove restrictions associated with the 10X multiplier in Fil+ deals and allow any actor to mint Datacap, promoting decentralization and simplifying the Filecoin ecosystem.
This proposal aims to remove restrictions on access to the 10X multiplier in Fil+ deals and allow any actor to mint Datacap, thus making Filecoin permissionless again.

2023-08-31 00:16 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +The Fil+ program was designed to encourage high-quality storage on the Filecoin network. The current proposal intends to remove complexities that have arisen from its initial conception, thereby ensu
The Fil+ program was designed to encourage 'useful' storage on the Filecoin network. The current proposal intends to remove the permissioned notary system. This will ensure that Filecoin remains decentralized, transparent and fair. The power to define usefulness is transferred to users.

2023-08-31 00:16 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +The current Fil+ implementation, though well-intentioned, has added complexities that deviate from Filecoin's core mission. Simplifying this system will encourage the onboarding of genuine data and u
The current Fil+ implementation, though well-intentioned, has created an uneven playing field for SPs, permissioned the chain, and encouraged undesirable behaviors like bribery, fraud and framing competitors. Our proposal makes Filecoin fully permissionless. It will remove these problems and restore confidence in the integrity and neutrality of our consensus algorithm

2023-08-31 03:07 UTC, momack2 commented on FIPS/fip-FCM.md
> +Discussions-to: https://github.com/filecoin-project/FIPs/discussions/774
Jennifer is requesting a new discussion so that folks who read this proposal have a place to go comment and discuss it going forward that isn't already crowded with many competing/alternate proposals that are different to the one described here. This enables clearer discussion and debate with a new draft proposal.

2023-08-31 03:44 UTC, momack2 requested changes

2023-08-31 03:44 UTC, momack2 commented on FIPS/fip-FCM.md
> +This proposal aims to remove restrictions associated with the 10X multiplier in Fil+ deals and allow any actor to mint Datacap, promoting decentralization and simplifying the Filecoin ecosystem.
```suggestion
This proposal aims to allow any actor to mint Datacap and bestow a 10X multiplier to any sector, regardless of whether it stores client data / serves FIL+ deals.
```
Seems like this is a more accurate and descriptive summary for this proposal

2023-08-31 03:44 UTC, momack2 commented on FIPS/fip-FCM.md
> +The current Fil+ implementation, though well-intentioned, has added complexities that deviate from Filecoin's core mission. Simplifying this system will encourage the onboarding of genuine data and u
Can you please explain how this proposal will "encourage the onboarding of genuine data"? This seems core to your argument, but is unsubstantiated in this proposal.

2023-08-31 03:44 UTC, momack2 commented on FIPS/fip-FCM.md
> +After this upgrade, Storage Providers (SPs) can engage with any deal, whether Fil+ or not by minting Datacap. Deals will still need the `verified` flag set to true, but clients will be able to freely
how does this change interface with the new direct data onboarding proposal here (https://github.com/filecoin-project/FIPs/pull/804/files)?

2023-08-31 03:44 UTC, momack2 commented on FIPS/fip-FCM.md
> +This FIP, though providing simplified access, doesn't introduce new security threats.
I agree with Jennifer that this section seems incomplete. Security consideration should be given to: 
- could a large CC-sector miner use this change to quickly upgrade all their CC sectors into fake "10x deal" sectors (without actually onboarding any real/useful client data) and use that to gain control of the network?
- how does this change harm the security of **data** on the network? (ex it significantly decreases the confidence of existing Filecoin clients that SPs will continue to store and safeguard their data - since they could instead dump their sectors full of real client data and get the same protocol incentive for storing strings of 0s - which are easier to repair and come with no client expectations)

2023-08-31 03:44 UTC, momack2 commented on FIPS/fip-FCM.md
> +With the removal of the restriction, effectively-empty sectors can now benefit from a multiplier. This adjustment allows Storage Providers (SPs) to onboard more Raw Byte Power (RPB) at a potential pr
How does this proposal contend with the attack vector that both FIP36 and FIP56 ran into - that an increased multiplier actually has a *downward* pressure on RBP (and therefore block rewards)?
- Most SPs are **capital-limited**, not hardware-limited, and will therefore onboard 1/10th the number of sectors for the same collateral requirements (causing a 10x decrease in RBP)
- The final version of the FIP56 proposal decreased the multiplier for any non-deals sector to a max of 2x to ensure the network RBP would not contract massively if SPs rationally chose to terminate their existing storage and recommit only 1/Xth

2023-08-31 03:44 UTC, momack2 commented on FIPS/fip-FCM.md
> +Following this amendment, primary motivations for SPs to onboard data will still need to originate from outside the core protocol. This could encompass direct client payments or potential incentive m
Can you give a rough estimate on the drop in current inbound client demand for Filecoin that would drop off given the scale required for these "direct client payments", either here or in the product consideration section?

2023-08-31 03:44 UTC, momack2 commented on FIPS/fip-FCM.md
> +Clients and Storage Providers will experience a streamlined interaction with the Filecoin network, which could lead to more user-friendly products and services built on top of Filecoin.
Can you please clarify why you expect more user-friendly product and services to exist without client data storage incentives?

2023-08-31 03:44 UTC, momack2 commented on FIPS/fip-FCM.md
> +The proposed changes present SPs with a more flexible environment, allowing them to select a pledge-to-hardware ratio best aligned with the specific costs and benefits they encounter. This enhanced f
1. FIL+ is not limited to the notary system. There are 4 different data cap distribution programs within FIL+ - one of which automatically gives _any_ github acct that requests it 64GB of datacap per month. 
2. Data storage clients are a valued and critical constituency within the Filecoin network. If your proposal aims to disenfranchise them in favor of SPs, you need to say so explicitly in your proposal.

2023-08-31 18:12 UTC, raghavrmadya commented on FIPS/fip-FCM.md
> +The current Fil+ implementation, though well-intentioned, has added complexities that deviate from Filecoin's core mission. Simplifying this system will encourage the onboarding of genuine data and u
I would like to share that there is no concrete evidence of bribery, even though multiple claims have been made about secondary markets for DC. Additionally, all accusations, as they concern abuse of DC, are well founded in evidence here - https://www.notion.so/filecoin/T-T-Dispute-Tracker-d28b93677cb544b48e77b585856601cf

2023-08-31 18:18 UTC, raghavrmadya commented on FIPS/fip-FCM.md
> +The proposed changes present SPs with a more flexible environment, allowing them to select a pledge-to-hardware ratio best aligned with the specific costs and benefits they encounter. This enhanced f
If we are going to take the current state of the world where SPs have access and influence ( partly because the network spent the initial years focusing on the supply side) and use that as an argument to build the future state, then how do we create a place for clients in this network? If data clients are arguably a negligible constituency, this should be a concern for us and we should find ways to support this constituency.

2023-08-31 18:33 UTC, galen-mcandrew commented on FIPS/fip-FCM.md
> +This proposal aims to remove restrictions associated with the 10X multiplier in Fil+ deals and allow any actor to mint Datacap, promoting decentralization and simplifying the Filecoin ecosystem.
Agree with this edit, it is more accurate than unsubstantiated commentary around decentralization, simplification, or permissionlessness.

2023-08-31 18:36 UTC, galen-mcandrew commented on FIPS/fip-FCM.md
> +After this upgrade, Storage Providers (SPs) can engage with any deal, whether Fil+ or not by minting Datacap. Deals will still need the `verified` flag set to true, but clients will be able to freely
Will this proposal change existing RKH and Notary chain-states? Will clients still be able to choose to go through an existing notary process, such as Glif Autoverification?

2023-08-31 18:40 UTC, galen-mcandrew commented on FIPS/fip-FCM.md
> +This FIP, though providing simplified access, doesn't introduce new security threats.
Currently, DataCap has no 'expiration point' and can only be destroyed by notary and RKH message (per FIP0028) or burned in deals.
Are there additional concerns of actors minting massive amounts of DataCap? What would happen if a bot opened new client addresses and spammed that mint DataCap function, creating EiB of DataCap immediately? 
Should there be a threshold or gate on minting?

2023-08-31 18:54 UTC, galen-mcandrew commented on FIPS/fip-FCM.md
> +With the removal of the restriction, effectively-empty sectors can now benefit from a multiplier. This adjustment allows Storage Providers (SPs) to onboard more Raw Byte Power (RPB) at a potential pr
Currently, we see 10.8EiB with 1.4EiB active Fil+ deals. Based on this proposal, one possible outcome is a continuing decrease in RBP with a massive increase in QAP. For example, what happens if the RBP to active 'DataCap' deals ratio is closer to 1:1? Has there been any modeling on how the block reward calculation would be impacted?

2023-08-31 20:10 UTC, anorth commented on FIPS/fip-FCM.md
> +The proposed changes present SPs with a more flexible environment, allowing them to select a pledge-to-hardware ratio best aligned with the specific costs and benefits they encounter. This enhanced f
@raghavrmadya thanks for your contributions here, but this PR review should be fairly strictly focussed on editorial review of the content. It's not the place to ask or answer questions like this. Please do raise them in the discussion thread item, though.

2023-08-31 22:10 UTC, kaitlin-beegle commented on FIPS/fip-FCM.md
> +title: "Removing Restriction to Access to Multiplier and Allowing Unrestricted Minting of Datacap"
Great. Does this mean that we can close the other PR? @The-Wayvy

2023-08-31 23:14 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +The current Fil+ implementation, though well-intentioned, has added complexities that deviate from Filecoin's core mission. Simplifying this system will encourage the onboarding of genuine data and u
Molly, the core of our argument is making Filecoin Permissionless / providing an even playing field for all participants / neutrality and objectivity.

I think by now you get our views.
@momack2

2023-09-01 03:29 UTC, 15012700225 commented on FIPS/fip-FCM.md
> +This FIP, though providing simplified access, doesn't introduce new security threats.
What's the difference between fil+casting datacap and free casting datacap, especially given the amount of abuse?
What I want to know is why you don’t need to consider security issues when you turn on fil+ casting datacap, but you need to turn on free casting?

Is it more straightforward to switch to staking mining (POS) in one step?

2023-09-01 10:21 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +title: "Removing Restriction to Access to Multiplier and Allowing Unrestricted Minting of Datacap"
@kaitlin-beegle 
That's David's decision.

2023-09-01 10:25 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +This proposal aims to remove restrictions associated with the 10X multiplier in Fil+ deals and allow any actor to mint Datacap, promoting decentralization and simplifying the Filecoin ecosystem.
@galen-mcandrew 

Our commentary on permissionlessness is pure fact.

2023-09-01 10:28 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +With the removal of the restriction, effectively-empty sectors can now benefit from a multiplier. This adjustment allows Storage Providers (SPs) to onboard more Raw Byte Power (RPB) at a potential pr
@galen-mcandrew 

This is something for CEL to analyze.

2023-09-02 13:04 UTC, cryptowhizzard commented on FIPS/fip-FCM.md
> +The current Fil+ implementation, though well-intentioned, has added complexities that deviate from Filecoin's core mission. Simplifying this system will encourage the onboarding of genuine data and u
This is really strange. Fil+ is about onboarding valuable data and onboarding this takes effort, resources and time.

If you want to onboard crap and trash I think people are welcome to do that, just not with 10x.

And why is a permissioned system bad? If the goal is onboarding true and real data there is nothing wrong with it. The argument “no market” makes no sense at all, there is market and there are customers atm. If those customers don’t want have anything to do with company’s who are not suiting them well for their needs it is up to them to change and make themselves competitive.

2023-09-03 03:55 UTC, hyunmoon commented on FIPS/fip-FCM.md
> +The current Fil+ implementation, though well-intentioned, has added complexities that deviate from Filecoin's core mission. Simplifying this system will encourage the onboarding of genuine data and u
Could the decision to weaken Filecoin Plus at this time speed up our move to a future where most storage deals are paid?
If yes, could you please explain why?

2023-09-03 03:58 UTC, hyunmoon commented on FIPS/fip-FCM.md
> +The current Fil+ implementation, though well-intentioned, has added complexities that deviate from Filecoin's core mission. Simplifying this system will encourage the onboarding of genuine data and u
While I am not overly concerned about being permissionless, I do prioritize a steady increase in market capitalization.
I believe that an increase in paid deals is crucial to achieving this objective.

2023-09-04 00:49 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +Following this amendment, primary motivations for SPs to onboard data will still need to originate from outside the core protocol. This could encompass direct client payments or potential incentive m
That is CEL's job.

If you are worried about it then you can do the analysis yourself.

2023-09-04 00:52 UTC, The-Wayvy commented
@momack2 

Stop putting words in our mouths

> Can you please explain how this proposal will "encourage the onboarding of genuine data"? This seems core to your argument, but is unsubstantiated in this proposal.

The core of our argument is that Filecoin Plus creates an uneven playing field, and that non-user's judgements about quality are not a solid foundation for a consenus algorithm. 

We covered this in 774. That is where the 'philosophical' part of the debate occurred.

2023-09-04 00:54 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +The current Fil+ implementation, though well-intentioned, has added complexities that deviate from Filecoin's core mission. Simplifying this system will encourage the onboarding of genuine data and u
@cryptowhizzard 

You are a notary and do not want to lose your privilege.
That is why you defend the current system.

@hyunmoon 
You have made large investments in Filecoin Plus-compatible hardware.
That is why you defend the current system.

2023-09-04 01:02 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +The current Fil+ implementation, though well-intentioned, has added complexities that deviate from Filecoin's core mission. Simplifying this system will encourage the onboarding of genuine data and u
> This is really strange. Fil+ is about onboarding valuable data and onboarding this takes effort, resources and time.

The question is: who should decide what is valuable?

Users will decide what is valuable and what is a good use-case for our technology.

The governance team and notaries are not the ones paying and therefore should not be making decisions about what is quality and useful.

Having non-users dictate 'quality' and 'utililty' is speculative at best and corrupt at worst.

> If you want to onboard crap and trash I think people are welcome to do that, just not with 10x.

Again, data you don't like is not 'crap' 

The usefulness of data = how much users will pay for it

You don't know what Filecoin's PMF will be. 

This is like saying Uniswap is crap because you can't trade 'real assets' like US Treasury Bonds and NASDAQ stocks.

> And why is a permissioned system bad? If the goal is onboarding true and real data there is nothing wrong with it. The argument “no market” makes no sense at all, there is market and there are customers atm. If those customers don’t want have anything to do with company’s who are not suiting them well for their needs it is up to them to change and make themselves competitive.

The whole point of having a sybil resistance mechanism on a network is to enable permissionless participation.
PoSt and PoS are sybil resistance mechanisms.
If you want a permissioned network then there is no need to waste so much capital in PoS and so much computation in PoSt.
We can KYC every storage provider and have them sign contracts with PL.

Literally the entire point of this technology is to enable permissionlessness.

True and Real data does nothing for the price of Filecoin is users aren't paying for it.

Also, if you believe in the market then at the very least all Filecoin Plus deals should be required to go up for public auction.

2023-09-04 01:04 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +The current Fil+ implementation, though well-intentioned, has added complexities that deviate from Filecoin's core mission. Simplifying this system will encourage the onboarding of genuine data and u
@hyunmoon 

If the governance team wants to play VC they can use their own money to subsidize 'real' users.

Their speculation/preferences are not a legitimate input to a crypto consensus algorithm.

2023-09-04 01:07 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +Clients and Storage Providers will experience a streamlined interaction with the Filecoin network, which could lead to more user-friendly products and services built on top of Filecoin.
Without the notary system there would be fewer steps to getting their data onboarded.
 
Storage incentives are fine, but they can't have a human in the loop.

2023-09-04 01:09 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +## Incentive Considerations
@kaitlin-beegle 

if you add me as a collaborator I will speed up the editing process.

This was not David's first choice and he just wanted to get the PR out the door, not write a masterpiece.

2023-09-04 01:17 UTC, anorth commented on FIPS/fip-FCM.md
> +## Incentive Considerations
@The-Wayvy we have no ability to give you edit access here since the source of the PR is a repository under @dcasem's GitHub account. He should be able to do so, though.

2023-09-04 01:20 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +With the removal of the restriction, effectively-empty sectors can now benefit from a multiplier. This adjustment allows Storage Providers (SPs) to onboard more Raw Byte Power (RPB) at a potential pr
@momack2 
@galen-mcandrew 

Crypto-Economic Analysis is a job for... Crypto-Econ Lab

They've already done the work.

https://hackmd.io/zp-40inqSny5HMqmTSOKxw?view

2023-09-04 01:24 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +After this upgrade, Storage Providers (SPs) can engage with any deal, whether Fil+ or not by minting Datacap. Deals will still need the `verified` flag set to true, but clients will be able to freely
@momack2 

That is a legitimate question. 

I will ping Alex.

2023-09-04 01:34 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +This FIP, though providing simplified access, doesn't introduce new security threats.
1

> I agree with Jennifer that this section seems incomplete. Security consideration should be given to:

could a large CC-sector miner use this change to quickly upgrade all their CC sectors into fake "10x deal" sectors (without actually onboarding any real/useful client data) and use that to gain control of the network?

Even in the worst case scenario where only one miner converts their RBP to 10x, and the others stick with CC
It would still take that malicious miner over 2 exabytes of RBP + all that new 10x collateral to get 50% of network power.

If you aren't convinced that that's unlikely then I hope you ask CEL.

2

> how does this change harm the security of data on the network? (ex it significantly decreases the confidence of existing Filecoin clients that SPs will continue to store and safeguard their data - since they could instead dump their sectors full of real client data and get the same protocol incentive for storing strings of 0s - which are easier to repair and come with no client expectations)

Real users will pay the price that a service is worth.

We keep telling you that you're in too much of a rush to get these big Web2 clients.

It takes a long time to build consumer applications on a blockchain.

Ex. Ethereum is not used for mortgages or trading TradFi stocks / bonds even after 8 years in production.

The first applications are going to be stupid: like CryptoKitties and Satoshi Dice.

Please be more patient.

3

There is no fake and real. 
No useful and useless.
Only paid and unpaid.

2023-09-04 02:35 UTC, The-Wayvy requested changes

2023-09-04 02:35 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +replaces:
replaces: FIP0003

2023-09-04 06:10 UTC, hyunmoon commented on FIPS/fip-FCM.md
> +The current Fil+ implementation, though well-intentioned, has added complexities that deviate from Filecoin's core mission. Simplifying this system will encourage the onboarding of genuine data and u
I concur. The project should have commenced with a stipend rather than a subsidy from the network.
I think the situation wouldn't have been this problematic if the program had been managed by Protocol Labs employees.

2023-09-04 06:16 UTC, hyunmoon commented on FIPS/fip-FCM.md
> +The current Fil+ implementation, though well-intentioned, has added complexities that deviate from Filecoin's core mission. Simplifying this system will encourage the onboarding of genuine data and u
I concur. Ideally, the project should have been supported by a single, upfront allocation of funds.
I believe the situation wouldn't have become this problematic had it remained under the management of Protocol Labs employees, rather than being handed over to elected notaries.

2023-09-04 08:57 UTC, Derek-zd commented
> @momack2
> 
> It would be nice if you focused on the benefits of this proposal rather than cherry-picking individual phrases in a PR draft.
> 
> Marko summarized our position in 774, and many others made good contributions as well.
> 
> You could help us synthesize all those valid points into a cohesive narrative for why Filecoin Plus 1.0 is being retired.
> 
> > Can you please explain how this proposal will "encourage the onboarding of genuine data"? This seems core to your argument, but is unsubstantiated in this proposal.
> 
> The core of our argument is that Filecoin Plus creates an uneven playing field, and that non-user's judgements about the value of a data-set to Filecoin are guess-work and not an acceptable input to our consenus algorithm.
> 
> But I'll respond to this point: The current system incentives miners to take data that you would consider 'fake' and pass it off as 'real' to get the 10x multiplier. To get rid of the incentive for this charade, just get rid of notaries. Then 100% of user data onboarded will be real. We can be sure of that because no real user would pay to onboard useless data.
> 
> > FIL+ is not limited to the notary system. There are 4 different data cap distribution programs within FIL+ - one of which automatically gives any github acct that requests it 64GB of datacap per month.
> 
> > Data storage clients are a valued and critical constituency within the Filecoin network. If your proposal aims to disenfranchise them in favor of SPs, you need to say so explicitly in your proposal.
> 
> Nobody is disenfranchising users.
> 
> They are free to bid for services on Filecoin.
> 
> That is the whole point.
> 
> We want users themselves to decide what data and what transactions make it onto Filecoin.
> 
> Rather than the governance team and notaries.

oh, man. Why are you so ignorant of the current fil + situation, and why are you so naive。 No user is willing to pay to store the data in Filecoin。SP pays client to store the data in SP.
>We can be sure of that because no real user would pay to onboard useless data.

2023-09-04 09:09 UTC, The-Wayvy commented
@Derek-zd 

> oh, man. No user is willing to pay to store the data in Filecoin。SP pays client to store the data in SP.

I know that.

So let's drop the Fil+ charade about 'quality' and focus instead on improving the tech.

2023-09-04 09:19 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +The proposed changes present SPs with a more flexible environment, allowing them to select a pledge-to-hardware ratio best aligned with the specific costs and benefits they encounter. This enhanced f
@raghavrmadya 

### It's too early for the use cases that Filecoin Plus is trying to subsidize

I believe the root of our problem is an extreme lack of patience.

We don't even have stablecoins or a DEX on Filecoin.
 
In fact we don't even have good oracles.

Ofcourse we aren't going to have Web2 giants using our tech.

There is still a lot of work to be done on very basic infrastructure.

We do have real users on the FVM and the miners themselves are users because they pay for blockspace.

Some are choosing to 
1.) deny the value of these real users.
2.) try to force certain use-cases and users on the network before Filecoin is ready for them.

Just keep building and have a little faith.

And please keep an open-mind to who the next set of real users and use-cases will be.

It probably will not be what you expect: just like few saw Uniswap or Cryptokitties etc coming.

2023-09-04 11:55 UTC, The-Wayvy requested changes

2023-09-04 11:55 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +replaces:
replaces: FIP0003

2023-09-04 23:40 UTC, jennijuju commented on FIPS/fip-FCM.md
> +After this change, the verified registry and datacap actors will be mostly obsolete. Allowing unlimited datacap does not create any complexity, but does make it possible to remove some. Future protoc
@anorth No, im not referring to then future opportunities. 

> Allowing unlimited datacap does not create any complexity, but does make it possible to remove some.

I am asking the complexities that will be removed by this proposal to be included as a a part of the design rationale/product/incentive consideration.

2023-09-04 23:48 UTC, jennijuju commented on FIPS/fip-FCM.md
> +This proposal aims to remove restrictions associated with the 10X multiplier in Fil+ deals and allow any actor to mint Datacap, promoting decentralization and simplifying the Filecoin ecosystem.
I also dont think they are needed - thus im confused with the phrasing of "Removing restriction to access to multiplier" in the title -  to me it implies a change anyone can deploy their own multiplier and gets additional QAP thats other than the `deal  quality multiplier` that comes with datacap.  

That being said, this proposal should also call out the degraded functionality and/or the unnecessity  of  `AddVerifier` and `AddVerifiedClient` methods, with the introduction of "all you can mint" datacap rule.

2023-09-05 08:51 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +This proposal aims to remove restrictions associated with the 10X multiplier in Fil+ deals and allow any actor to mint Datacap, promoting decentralization and simplifying the Filecoin ecosystem.
@jennijuju 

You are the expert on implementation.

We appreciate your help.

2023-09-05 10:07 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +The proposed change effectively removes a significant incentive for the onboarding of data that was previously determined as valuable by the off-chain notaries under the Fil+ mechanism. As a result,
@jennijuju 

No

2023-09-05 21:58 UTC, anorth commented on FIPS/fip-FCM.md
> +After this upgrade, Storage Providers (SPs) can engage with any deal, whether Fil+ or not by minting Datacap. Deals will still need the `verified` flag set to true, but clients will be able to freely
@galen-mcandrew no it won't, all the existing workflows will still work fine (and the FIP should note this).

I've responded about interactions with direct onboarding [here](https://github.com/filecoin-project/FIPs/discussions/774#discussioncomment-6918983) (I don't see any).

2023-09-06 06:33 UTC, Fatman13 commented
Should we keep the PR thread strictly between authors and FIP editors? Everything else should go to the discussion thread.

2023-09-06 13:34 UTC, The-Wayvy commented
I committed changes based on everyone's comments.

@anorth @jennijuju @jsoares @raulk @kaitlin-beegle @arajasek 

Can I get a merge?

2023-09-08 02:47 UTC, anorth commented on FIPS/fip-FCM.md
> +This FIP, though providing simplified access, doesn't introduce new security threats.
Regarding the risk of rapid gains in power from upgrading CC, thanks for the napkin analysis but the point of the question is the FIP document must discuss this the presence and likely size of this risk, and any mitigating factors. You might also note that SPs would have to snap-deal to do that upgrade, which introduces a hardware constraint. But again, the point isn't to convince anyone here, the point is that the document needs to contain a reasonable discussion of the risk.

2023-09-08 02:47 UTC, anorth commented on FIPS/fip-FCM.md
> +This FIP, though providing simplified access, doesn't introduce new security threats.
Re existing client data, I don't really think it's a security consideration, but it's definitely an incentive consideration. The change in incentives to SPs currently storing verified data is real. I tend to think the practical impact is low since "dumping" the data requires paying termination fees and re-sealing. But again, the FIP document must lay this out.

2023-09-08 02:58 UTC, anorth commented on FIPS/fip-FCM.md
> +With the removal of the restriction, effectively-empty sectors can now benefit from a multiplier. This adjustment allows Storage Providers (SPs) to onboard more Raw Byte Power (RPB) at a potential pr
This substitution risk similar to FIP56 is important to explain in the FIP document. You can note that it's similar to risk of such behaviour if FIL+ was significantly more efficient and so datacap easier to get (even if all "good" data). It won't change the behaviour of SPs currently getting FIL+ much, which account for most onboarding today. It could change behaviour of others, but it's rather hard to say in which direction: balancing the substitution idea is the idea that for SPs who can't/won't get FIL+, onboarding _anything at all_ becomes profitable, an improvement to today.

This risk comes down to the ability of SPs to chose their hardware/data capital balance. I tend to this this could be good for SP business models (heterogeneous environments and setups can optimise for their comparative advantage) but it does introduce the _risk_ of this substitution having an impact on RPB. The FIP must discuss this.

It is not sufficient to say anything is someone else's job. This FIP document must describe all the relevant considerations. You can take some things from CEL's existing analysis. If more is needed you can ask them to help you, and they probably will. But no-one is obligated to do the work for you.

2023-09-08 06:04 UTC, momack2 commented on FIPS/fip-FCM.md
> +Clients and Storage Providers will experience a streamlined interaction with the Filecoin network, which could lead to more user-friendly products and services built on top of Filecoin.
there already exists pathways to onboard data without FIL+ incentives or using the notary program - however we have not seen any user-friendly products or services building around that data onboarding flow (that I know of - maybe Telnyx offers one that is publicly accessible?). I don't think you have evidence to support your claim that better UX will just happen without economic incentives (ex, multiple data onboarding solutions - offering much better UX) have been created around the FIL+ data onboarding flow including Spade, Singularity, web3.storage, BDE, Motion, and many tools created directly by storage providers.

2023-09-08 06:08 UTC, momack2 commented on FIPS/fip-FCM.md
> +This FIP, though providing simplified access, doesn't introduce new security threats.
If this FIP doesn't discuss data security of client data here, then it needs to be explicitly discussed in the product section - both for new data onboarded (how secure is that data vs status quo) and data that's already been onboarded into the network. IMHO is appropriate to include in the security section because ensuring storage is not suddenly dropped or storage quality reduced is a security concern for achieving the core purpose of the Filecoin network - but as long as it's included clearly it could be in either section

2023-09-08 06:12 UTC, Fatman13 commented on FIPS/fip-FCM.md
> +With the removal of the restriction, effectively-empty sectors can now benefit from a multiplier. This adjustment allows Storage Providers (SPs) to onboard more Raw Byte Power (RPB) at a potential pr
How about the following edits regarding substitution risk? @anorth 

There may be different outcomes with regard to substitution risk, which refers to a CC SP who may expire its RBP and use the released collateral to achieve same amount of QAP power as before but with less hardware. In the scenario where we don't have [direct data on-boarding](https://github.com/filecoin-project/FIPs/discussions/730), the network growth would still be limited by the chain throughput of PublishStorageDeal messages which in turn minimizing substitution risk and effectively maintaining the current network status quo of RBP falling generally. In the scenario where we do have [direct data on-boarding](https://github.com/filecoin-project/FIPs/discussions/730), substitution risk would depend on how fast different SPs could react to the new FIP, recalibrate their hardware deployment to maximize their data on-boarding efficiency (hardware/data capital balance) and new chain throughput of direct data on-boarding message. Substitution risk in second scenario is also mitigated by the fact that CC SPs are expiring sectors anyway given the history CC expiring trend. Substitution in such case may even help to retain the SPs to stay in the network.

2023-09-08 06:20 UTC, momack2 commented on FIPS/fip-FCM.md
> +The Fil+ program intended to compensate miners for storing non-random data on Filecoin. It was hoped that these datasets would increase the utility of the network and thereby attract paying users. Fi
actually - there are paying customers utilizing FIL+ right now to achieve the cost-reductions necessary to make adopting Filecoin (instead of other storage networks) worth the transition costs. Agree we're still early days here - but this is an increasing trend that Fil+ has enabled.

It has also increased network utility -- there are now PiBs of valuable datasets (such as the recently rescued [Meta BioML dataset used for training protein folding language models](https://medium.com/@labdao/how-to-save-20-terabytes-of-scientific-public-goods-23151d24c6b2)) stored on Filecoin that are available for compute providers, DeSci builders, FVM smart contracts, and more to build their businesses on. There are [nearly 100M NFTs](https://nft.storage/stats/) stored on Filecoin (26B market cap). 

Maybe reframe this as: "Fil+ has accelerated the development of data-onboarding tools, increased network utility, and is in the early days of attracting and converting paying data clients to Filecoin -- however the notary system used by 3/4 Fil+ programs today is inefficient, un-objective, and riddled with perverse incentives."

2023-09-08 06:23 UTC, momack2 commented on FIPS/fip-FCM.md
> +A more transparent, predictable and fair Filecoin will attract new miners, driving down the price of storage.
Agree this would likely attract new miners - but since a much smaller portion of miners will be engaging in data storage and there will be no incentives to subsidize data storage - I don't see how this would drive down the price of storage. I think more likely we'll see more miners join the network with zero intention to store data.

2023-09-08 11:14 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +A more transparent, predictable and fair Filecoin will attract new miners, driving down the price of storage.
I do think that in the short-run most miners will join the network looking to just mine block rewards.

My _guess_ is that storage of user data will become the norm _evenutally_ because 

1.) Margins on CC mining will keep going down (ever more mining power + an ever smaller block reward) 
2.) We'll build applications that users are actually willing to pay for. 

IMO we're trying to get there too fast.

2023-09-13 13:12 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +This FIP, though providing simplified access, doesn't introduce new security threats.
I briefly discussed this in a PR just now.

2023-09-13 13:35 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +With the removal of the restriction, effectively-empty sectors can now benefit from a multiplier. This adjustment allows Storage Providers (SPs) to onboard more Raw Byte Power (RPB) at a potential pr
@momack2 

We would like to cut the multiplier to keep RBP from further contracting.

One variation on 803 would be to give everyone access to the multiplier, but also gradually cut the multiplier down to one.

2023-09-14 10:40 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +With the removal of the restriction, effectively-empty sectors can now benefit from a multiplier. This adjustment allows Storage Providers (SPs) to onboard more Raw Byte Power (RPB) at a potential pr
Resolved

2023-09-14 13:05 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +Clients and Storage Providers will experience a streamlined interaction with the Filecoin network, which could lead to more user-friendly products and services built on top of Filecoin.
I changed it to: 

> Removing the notary system will streamline data onboarding for users as well as lower costs and uncertainty for miners.

Miners are still free to use all those data onboarding tools that you mentioned.

Under this proposal, the only economic incentive for miners to improve data-onboarding UX would be to get more paying users.

We think that's a good thing.

I added it to incentive considerations.

2023-09-21 05:40 UTC, kaitlin-beegle commented on FIPS/fip-FCM.md
> +The Fil+ program was designed to encourage high-quality storage on the Filecoin network. The current proposal intends to remove complexities that have arisen from its initial conception, thereby ensu
No, these are the same things. Words like "permissioned", "decentralized", and "fair" don't clearly frame your proposal. You need to say 1) what concrete change you're making, and 2) for what specific, concrete reason.  Adding vague words- especially ones like "decentralized", which can be interpreted and defined in many different ways- makes both governance and implementation harder to navigate. 

So, for example: 

"The Fil+ program was designed to encourage high-quality storage on the Filecoin network.  However, [insert specific problem you're trying to address].  To address this, we propose a change to the maintenance of datacap, such that datacap can be accessed by any network participant.  Doing so will enable us to solve [insert aforementioned problem] because [insert reason]." 

In other words, you're not making an argument; you're specifying a proposal.  Does that make sense?

2023-09-21 08:26 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +Following this amendment, primary motivations for SPs to onboard data will still need to originate from outside the core protocol. This could encompass direct client payments or potential incentive m
I edited the FIP to mention that drops in demand are hard to quantify because
1.) We don't know what % of existing data on Filecoin has a real user behind it.
2.) We don't know what users are actually willing to pay for Filecoin services since they've been getting storage for free on Filecoin Plus.

2023-09-21 08:39 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +This FIP, though providing simplified access, doesn't introduce new security threats.
I addressed this in security considerations.

2023-09-21 09:39 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +After this upgrade, Storage Providers (SPs) can engage with any deal, whether Fil+ or not by minting Datacap. Deals will still need the `verified` flag set to true, but clients will be able to freely
I addressed direct data onboarding in "Specification"

2023-09-21 09:48 UTC, The-Wayvy commented on FIPS/fip-FCM.md
> +The current Fil+ implementation, though well-intentioned, has added complexities that deviate from Filecoin's core mission. Simplifying this system will encourage the onboarding of genuine data and u
I addressed how 803 will disincentivize the onboarding of data with no paying users and fabricated datasets in "Product Considerations"

2023-10-03 19:43 UTC, anorth commented on FIPS/fip-FCM.md
> +Discussions-to: https://github.com/filecoin-project/FIPs/discussions/774
I agree with @jennijuju and @momack2 here and have created https://github.com/filecoin-project/FIPs/discussions/844. This should not be taken as any rewinding of process, but a venue for discussion of this concrete proposal to aid a quicker governance process.

2023-10-03 22:30 UTC, anorth commented
I'm assigning FIP number 0078 to this proposal. @The-Wayvy please update the FIP document and the README.md to reflect this.

2023-10-04 22:00 UTC, anorth approved these changes
I don't see any reason not to merge this draft FIP. Merging the draft is not equivalent to declaring this FIP ready for last call. Merging the draft gives us a linkable document to refer to, and the ability to PR additional changes into it and track history.

2023-10-04 23:30 UTC, jsoares approved these changes
I second @anorth. Leaving some minor editorial suggestions for the sake of clarity and readability.

2023-10-04 23:30 UTC, jsoares commented on FIPS/fip-0078.md
> +We will work around this by detecting explicit commitments to the "Zero" unsealed CID, which is the same unsealed CID that CC sectors use. Even though this unsealed CID is not stored on chain, we can
```suggestion
 **Snap Deals**: When an SP only wants to commit capacity, but do so with a high multiplier, the verified allocation they claim must specify a data CID, which must match the committed data. (Before direct onboarding, they would do a full-on deal with the built-in market; after direct onboarding, they can just directly commit the data). This would give the sector verified deal weight, making it not appear to be CC, and therefore ineligible for subsequent snap deal with client data. We will work around this by detecting explicit commitments to the "Zero" unsealed CID, which is the same unsealed CID that CC sectors use. Even though this unsealed CID is not stored on chain, we can set a flag in the sector's on-chain info to indicate that the sector data is zero, despite having verified deal weight, and that it is a valid target for snap deals.
```

2023-10-04 23:30 UTC, jsoares commented on FIPS/fip-0078.md
> +After this change, the verified registry and datacap actors will be mostly obsolete. Allowing unlimited datacap does not create any complexity. Future protocol improvements could remove these actors
```suggestion

After this change, the verified registry and datacap actors will be mostly obsolete. Allowing unlimited datacap does not create any complexity. Future protocol improvements could remove these actors and support direct specification of a multiplier when onboarding, in order to further simplify the protocol and reduce cost.
```

2023-10-04 23:30 UTC, jsoares commented on FIPS/fip-0078.md
> +This proposal does not change any chain state or method interfaces so is backwards compatible to all clients. All existing workflows will continue to work, and this change is also compatible with dir
```suggestion
This proposal does not change any chain state or method interfaces. It is, therefore, backwards compatible with all clients. All existing workflows will continue to work, and this change is also compatible with direct onboarding. A network upgrade is required to deploy the new actor code.
```

2023-10-04 23:30 UTC, jsoares commented on FIPS/fip-0078.md
> +After this upgrade, Storage Providers (SPs) can engage with any deal, whether Fil+ or not by minting Datacap. Deals will still need the `verified` flag set to true, but clients will be able to freely
```suggestion
After this upgrade, Storage Providers (SPs) can engage with any deal, whether Fil+ or not, by minting Datacap. Deals will still need the `verified` flag set to true, but clients will be able to do this freely because they can mint the required datacap.
```

2023-10-04 23:30 UTC, jsoares commented on FIPS/fip-0078.md
> +Test that a non-account actor can mint datacap
```suggestion
- Test that an account actor that is not a notary can mint datacap
- Test that a non-account actor can mint datacap
```

2023-10-04 23:30 UTC, jsoares commented on FIPS/fip-0078.md
> +The proposed change removes Fil+'s incentive for the onboarding of non-random data. As a result, it's anticipated that the onboarding rate of non-random data may decrease. It is still uncertain how m
```suggestion
The proposed change removes Fil+'s incentive for the onboarding of non-random data. As a result, it's anticipated that the onboarding rate of non-random data may decrease. It remains unclear how much of the data currently incentivized by Fil+ is not in compliance with the program's goals.
```

_Fake_, like _useful_, remains vaguely and contentiously defined.

2023-10-04 23:30 UTC, jsoares commented on FIPS/fip-0078.md
> +It is hard to estimate how much user demand Filecoin will lose in the short-run, (both demand for data already stored on the network, and data that potentially could have been onboarded in the future
```suggestion
It is hard to estimate how much user demand Filecoin will lose in the short run, (both demand for data already stored on the network and for data that potentially could have been onboarded in the future). There are two reasons for this: first, we don't know how much of the data stored via Fil+ deals has an actual user behind it; second, because Fil+ distorted price discovery, we don't know what users are willing to pay for Filecoin storage and what miners are willing to accept.  
```

2023-10-08 23:12 UTC, anorth commented
The merge button on GitHub is disabled because @momack2 and @kaitlin-beegle used "request changes" for their reviews. GitHub workflow requires them to re-review to lift the request for change (which makes sense and is useful in many code review contexts). I believe a some reasonable changes have been made in response, at least enough to make this PR reasonable as a draft FIP. I will "dismiss review" and then merge in a couple of days. Of course, more improvements can be requested in the associated discussion thread if needed before moving to Last Call.

2023-10-09 02:02 UTC, kaitlin-beegle approved these changes

2023-10-09 02:03 UTC, kaitlin-beegle commented
> The merge button on GitHub is disabled because @momack2 and @kaitlin-beegle used "request changes" for their reviews. GitHub workflow requires them to re-review to lift the request for change (which makes sense and is useful in many code review contexts). I believe a some reasonable changes have been made in response, at least enough to make this PR reasonable as a draft FIP. I will "dismiss review" and then merge in a couple of days. Of course, more improvements can be requested in the associated discussion thread if needed before moving to Last Call.

Thanks for the flag, Alex. It was not my intention to hold this up, and I agree that substantial improvements have been made.  I've approved this for merging.

2023-10-11 01:42 UTC, merged