Update fip-0001.md
filecoin-project/FIPs pull request #850
Opened 2023-10-15 14:53 UTC by kaitlin-beegle

Replaced existing FIP0001 text with FIP0001v2 text.

Introduces all policies introduced in #799, which have been presented, deliberated, and discussed over the past several months via Community Governance Calls, community public forums, at working group meetings, and in-person at various Fil and other events. 

Next week during regular working hours, I'll flesh out some additional questions for community consideration, and will open (and link) to PRs against the FIP spec that I think will provide some additional clarifying details.

2023-10-15 21:04 UTC, momack2 commented on FIPS/fip-0001.md
> +created: 2023-10-15
shall we maybe leave created at 2019-04-02, and then add "last-updated" for the current date? Don't want to break the history and imply the FIP process was only created in 2023...

2023-10-15 21:04 UTC, momack2 commented on FIPS/fip-0001.md
> +# Simple Summary
YES! so glad to have this FIP follow our FIP template!

2023-10-15 21:05 UTC, momack2 commented on FIPS/fip-0001.md
> +FIP0001v1 was largely a legacy document (see: History [link TODO]) which adopted the governance practices of other decentralized networks and open-source communities. It outlined an initial classific
can probably link to original commit already?

2023-10-15 21:11 UTC, momack2 commented on FIPS/fip-0001.md
> +Different kinds of FIPs have different requirements for consensus, depending on the scope and complexity of those changes. In general, more complex FIPs must meet a higher bar of review and approval
```suggestion
Different kinds of FIPs have different requirements for consensus, depending on the scope and complexity of those changes. In general, more complex or revolutionary FIPs must meet a higher bar of review and approval in order to achieve acceptance. 
```

2023-10-15 21:14 UTC, momack2 commented on FIPS/fip-0001.md
> +4. A **Security FIP** is drafted to remediate a network policy, bug, or related issue that poses a clear threat to network functionality. There are three levels of security FIP:
Thank you for adding these post discussion at FIL Dev Summit!

2023-10-17 10:02 UTC, willscott commented on FIPS/fip-0001.md
> +1. For **Level 1 security threats**, a FIP should be written for review and approval by the Filecoin Community Guild. Guild members will be asked to accept or reject the FIP; they may not abstain. Th
That highest security level issues are approved before the core devs see the fip and can comment on practicality / path seems to introduce the potential for misalignment and creating worse outcomes.

since implementation will need to happen by the core devs, it seems unclear that having fip decision happen before the issue is shared with core devs dos not save much in this case, but rather opens up additional surface area of another set of, in this case less technical stakeholders that also need to reach understanding and resolution on the security issue.

2023-10-17 23:35 UTC, anorth commented on FIPS/fip-0001.md
>  However, we also require that, where appropriate, Technical FIPs are also reflected in the protocol's specification, which is the primary source of reference for other developers. The [Filecoin Spec
This is a lie today, and I don't think there is any serious appetite from those responsible and/or capable to actually implement. I suggest we drop this paragraph.

2023-10-17 23:35 UTC, anorth commented on FIPS/fip-0001.md
> +  * :x: WIP -- Core Devs maintain the right to strike down WIP Technical FIP drafts that are technically unsound, unable to be implemented, or should otherwise be deprioritized.
> "should otherwise be deprioritized" 

This is _huge_ wiggle room and I think should be tightened a lot, or just dropped. We want something like "are otherwise completely ridiculous", but where that qualifier can't be used to reject any change to _anything_ specified in this FIP. E.g. a FIP to change the Filecoin mission can't be rejected out of hand by core devs if most of the community want it (i.e. it could subsequently pass the necessary processes)

2023-10-17 23:35 UTC, anorth commented on FIPS/fip-0001.md
> +* **Superseded** -- A FIP which was previously final but is no longer considered state-of-the-art. Another FIP will be in Final status and reference the Superseded FIP.
```suggestion
* **Superseded** -- A FIP which was previously accepted or final but is no longer considered state-of-the-art. Another FIP will be in Accepted or Final status and reference the Superseded FIP.
```

2023-10-17 23:35 UTC, anorth commented on FIPS/fip-0001.md
> +        * This specification[TODO] is an addenda to FIP0001 and can only be changed via FIP.
Please insert a hash of the specification text so that there is no ambiguity about which version this FIP is enshrining. Or will that document be added here in this PR as a resource or another document hosted in the FIPs repository?

2023-10-17 23:35 UTC, anorth commented on FIPS/fip-0001.md
> +    * The Guild maintains seven seats: one for each [Filecoin community stakeholder group](https://filecoin.io/blog/posts/filecoin-s-island-economy/), and one seat each for Filecoin founding institut
Please enumerate the stakeholder groups here rather than link to a resource which could go away.

2023-10-17 23:35 UTC, anorth commented on FIPS/fip-0001.md
> +        * Though the Filecoin Foundation maintains the ability to appoint representative groups to join the Guild, the community can vote to remove representative groups.  In these instances, a "supe
I'm also confused here. It is unclear above whether FF is appointing a specific person from a group, or just the group, who can nominate their own representative. I don't know what "composition of a Guild seat" means.

2023-10-17 23:35 UTC, anorth commented on FIPS/fip-0001.md
> +            3) Openly document and reasonably justify all Guild votes.
Does this mean their group's vote within the Guild?

2023-10-17 23:35 UTC, anorth commented on FIPS/fip-0001.md
> +            * Guild members can vote to Accept, Reject, or Abstain.  Votes cast in abstention will automatically count towards the majority preference. In instances of a 3/3 split with one abstention
Or a 1/1 or 2/2 split, I presume.

2023-10-17 23:35 UTC, anorth commented on FIPS/fip-0001.md
> +![](https://hackmd.io/_uploads/Skhq4iwZT.png)
Please upload the resource here, don't host it on HackMD. Or even better, make a table in text here.

2023-10-17 23:35 UTC, anorth commented on FIPS/fip-0001.md
> +* **Hybrid Consensus (Filecoin Community Guild)** -- The Filecoin Community Guild is an expert council that provides guidance, coordinates debate, and executes decision-making on behalf of key Fileco
Hybrid Consensus is an opaque term, and the remainder of this document doesn't use it at all. Instead, it tends to say "Community Guild approval" or similar. I suggest removing the jargon-like term and just calling this what it is.

2023-10-17 23:35 UTC, anorth commented on FIPS/fip-0001.md
> +**Consensus for cryptoeconomic and governance FIPs is determined by both community vote and Community Guild approval.**
```suggestion
**Consensus for cryptoeconomic and governance FIPs is determined by both hard consensus *AND* Community Guild approval.** 
```

2023-10-17 23:35 UTC, anorth commented on FIPS/fip-0001.md
> +1. For **Level 1 security threats**, a FIP should be written for review and approval by the Filecoin Community Guild. Guild members will be asked to accept or reject the FIP; they may not abstain. Th
> they may not abstain

The Guild process already described that abstain -> majority vote. Why does this need to be a special case? There are good reasons for community guild members to abstain from voting on something technical that they don't understand. I suggest either they always can abstain, or always can't.

2023-10-17 23:35 UTC, anorth commented on FIPS/fip-0001.md
> +The Filecoin Foundation is responsible for appointing and maintaining active FIP Editors.
While _probably_ fine, this is another FF-controlled single point of power. An alternative is to define the group to self-manage, like a guild member group, FF to step in only if the group disappears.

2023-10-18 10:26 UTC, jsoares commented on FIPS/fip-0001.md
> +    * Consensus amongst representatives in the Filecoin Community Guild will be determined.
```suggestion
During the Last Call period: 
* A vote will be held to determine community consensus to accept or reject. 
* Consensus amongst representatives in the Filecoin Community Guild will be determined. 
```

Fix indentation so that it renders as list

2023-10-18 10:26 UTC, jsoares commented on FIPS/fip-0001.md
> +![](https://hackmd.io/_uploads/Skhq4iwZT.png)
I'm already getting "forbidden" on the link so can't even assess content

2023-10-18 10:26 UTC, jsoares commented on FIPS/fip-0001.md
> +Once a decision has been reached by both consensus mechanisms- a hard consensus community poll, and consensus within the Filecoin community guild- the joint outcomes are used to determine the final c
```suggestion
Once a decision has been reached by both consensus mechanisms, the joint outcomes are used to determine the final consensus decision. 
```

Duplicated from lines above

2023-10-18 10:26 UTC, jsoares commented on FIPS/fip-0001.md
> +1. For **Level 1 security threats**, a FIP should be written for review and approval by the Filecoin Community Guild. Guild members will be asked to accept or reject the FIP; they may not abstain. Th
"may not abstain" is impossible to enforce. Guild members always have the option of not responding, especially on tight security deadlines.

We could have it as a rule that abstention would lead to replacement _but_ that's a matter of guild management and shouldn't be a part of the security FIP process description. It's also probably a bad rule for the reasons @anorth explained.

2023-10-18 10:26 UTC, jsoares commented on FIPS/fip-0001.md
> +## FIP Workflows
This should probably come before or alongside the description of the statuses above. Actually, I'd recommend making the order of the sections match the process, i.e. start with workflows and how to write and then progress to acceptance, rather than the way around.

2023-10-18 22:16 UTC, anorth requested changes
I, too, am very glad to have this FIP following our FIP template. However the current draft does not finish the job. It's missing a few key sections that are important to participants understanding the impacts of a proposal. While they usually apply to the technical/protocol impacts, I think it's just as important for a governance/community FIP to address the governance impacts.

### Incentive considerations
- What are the behaviours incentivised for individuals or groups to gain and hold governance power? Details here probably depend on not-yet-specified voting constituencies. 
- What are incentives re guild groups or members thereof? 
- What behaviours are incentivised for FF to retain its power/influence?

### Security considerations
- What are the weakest points of governance, and how strong are they? To (a) non-participation/incompetence, and (b) motivated/resourced attack?
- What are the minimum groups of people that can (a) block change, (b) force change of various types? Who is trusted for what?
- Perhaps a note about the limitations of this FIP? I.e. it can define a notion of legitimacy, but can't actually constrain real world action. Power centres remain, such as token holders/exchanges defining what Filecoin "is" in the event of fork, developers to actually implement any technical change, or SPs to decide what protocol to actually execute with their hardware.

We all accept that governance can't be perfect, the mechanisms will be a compromise. This will certainly be an improvement over status quo. But just as with technical systems, understanding the limits and weaknesses (which must exist) is part of gaining confidence that it's "good enough".

2023-10-18 22:16 UTC, anorth commented on FIPS/fip-0001.md
>  - Test Cases - Test cases for an implementation are mandatory for FIPs that are affecting consensus changes. Other FIPs can choose to include links to test cases if applicable.
The FIP template includes incentive considerations, and product considerations. They should be included here too.

Alternatively, to de-duplicate I think it would be fine to remove all the text here and instead link to the template (and include a note in the template that it's governed by FIP0001 so we don't accidentally make substantive changes).

2023-10-18 23:15 UTC, LukeHolon commented on FIPS/fip-0001.md
> +        * Though the Filecoin Foundation maintains the ability to appoint representative groups to join the Guild, the community can vote to remove representative groups.  In these instances, a "supe
I'm keen to understand the metrics (for example, why is supermajority consensus 66%? Most governance models use 75%) and mechanism (i.e., what are the specific voting protocols, including vote weightings, etc?) of the caucusing/gathering support and voting systems. Critical to voting systems and good governance is the ability for "identify verification" (KYC) of contributors/voters, and that those contributors/voters' identities ("names and businesses represented") are made publicly available for audit purposes. Identity verification would also significantly reduce noise and bad actor participation and reaffirm that a genuine and mature, open-source, democratic process, such as the Filecoin Network, requires a commensurate degree of genuine and mature transparency for human participation.

2023-10-18 23:30 UTC, rvagg commented on FIPS/fip-0001.md
> +Generally speaking, they are standards or recommendations and can be published by anyone.  Though they will be edited and maintained by FIP Editors, their publication does not indicate the collective
```suggestion
Generally speaking, they are standards or recommendations and can be published by anyone.  Though they will be reviewed and maintained by FIP Editors, their publication does not indicate the collective preference or endorsement of the Filecoin community. 
```

aligning language with the two previous instances that mention FIP Editor involvement in this process

2023-10-19 19:57 UTC, LaurenSpiegel commented on FIPS/fip-0001.md
> +* Anyone can open a PR against the Filecoin spec to update or clarify governance processes.
Why are these different from FRC's?

2023-10-19 20:03 UTC, LaurenSpiegel commented on FIPS/fip-0001.md
> +    * For a FIP to become accepted via soft consensus, there can be no outstanding or previously unresolved technical concerns, open questions, or substantive disagreements about accepting the FIP at
no "material" outstanding or previously...

2023-10-19 20:07 UTC, LaurenSpiegel commented on FIPS/fip-0001.md
> +            1) Maintain an open membership policy;
what does this mean in this context? the Guild member entities need an open membership policy?

2023-10-19 20:09 UTC, LaurenSpiegel commented on FIPS/fip-0001.md
> +**Consensus for cryptoeconomic and governance FIPs is determined by both community vote and Community Guild approval.**
So, in order to remove the Guild in the future by amending this FIP you would need the Guild to agree?

2023-10-19 21:44 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
> +created: 2023-10-15
My intention with FIP0001v2 was to maintain as much of FIP0001 as possible.  This includes a differentiation between "active" and "final" drafts. 

Most accepted and implemented FIPs are declared "final", and can only be superseded with new FIPs.  FIP0001 and FIP0003 are "active" in the sense that they are meant to be updated.  

- If we maintain this convention, then the most appropriate thing to do is to update FIP0001, rely on the version history, and call attention to it in _History_.   

- If it is clearer to community contributors for FIP0001 to remain unchanged and be superseded by this draft, which will get its own FIP number, then we should do away with the "active" and "final" distinction all together. 

I don't have a strong preference- each method is organizationally fine, and I'm happy to do whatever the majority thinks is best.  I have a slight preference for what @momack2 is asking, which is to simply rely on the versioning and more clearly indicate the update history.  

CC: @willscott

2023-10-19 21:51 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
> +Different kinds of FIPs have different requirements for consensus, depending on the scope and complexity of those changes. In general, more complex FIPs must meet a higher bar of review and approval
The standard for including descriptive language in FIP0001 should be _illusory_.  We should only include unspecified, descriptive terms (such as "complex") when they help explain the intent of the stated policy. This is important, as these words tend to become contentious when we encounter new use or edge cases. 

"Revolutionary" is a strong word. Can you please explain how adding this word better specifies policy? If there is disagreement in the future about the status of a FIP, how should FIP Editors interpret this word?

2023-10-19 21:53 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
> +4. A **Security FIP** is drafted to remediate a network policy, bug, or related issue that poses a clear threat to network functionality. There are three levels of security FIP:
Yes! @momack2 we did not dig too deeply into specifics of Security FIP subtypes, so these are definitions that I am putting forth.  They were the last part of this document to be added, and are the only part that hasn't been publicly vetted prior to this FIP being opened. 

Just flagging, so that you and others can be sure that these definitions map to your experiences/expectations.

2023-10-19 21:59 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
> +5.  A **Filecoin Request for Comment (FRC)** is an informational document which suggests standards and best practices for the Filecoin community.  It may suggest rules or procedures, including other
I think what you're pointing to is the need for greater review, scrutiny, and engagement on FRCs, correct? 

When we first started accepting FRCs, the ideal workflow was: 
- An FRC is opened as a PR against the FIP repo
- It is reviewed by FIP Editors
- It is merged as a 'Draft' once complete 
- It remains as a 'Draft' until Core Devs push for it to be determined 'Final', or else the FRC Author/other community members are able to demonstrate widescale adoption of the standard, etc. 

In practice (maybe a structural problem, maybe an issue of time), no one could or wanted to advocate for the adoption of FRCs.  They sat as drafts, and this was often confusing to community members. 
- The change here is that the threshold for "acceptance" is much lower, which I believe is what you're raising concern about.  

**Do you have any ideas or preferences about how we could reconfigure this (or another) FIP definition to better account for the use cases you're thinking about?**

2023-10-19 22:05 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
> +            * All Guild votes must be documented and supported.
^ +1 as well. 

My preference: 
- Any decision from the Guild must be documented and made public. 
   -  This includes decisions made about security FIPs, which may be made public at a later date (with an impetus to make it available ASAP). 
- Any dissenting opinions, or else the voting rationale from individual representatives, should be made just as accessible. 
- Agree about consensus decisions in the FIP text.  **I think we should update the template to include a note on consensus decisions, so that all outcomes are referenced and recorded in the FIP itself**. 

For security FIPs, the proposed policy effectively defers to Core Devs to make a decision about what is most appropriate, and to then be held accountable to that decision.  Do you feel like this is adequate? If not, how do you think we ought to more clearly specify time limits/etc., on security FIP decisions?

2023-10-19 22:18 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
> +        * Though the Filecoin Foundation maintains the ability to appoint representative groups to join the Guild, the community can vote to remove representative groups.  In these instances, a "supe
Good flags- I'll update the text to be a bit clearer. 

There is a difference between what role the seat is intended to fill (which is specified in the FIP), the group that is selected to fill that seat (as appointed by FF, but open to community veto), and the actual person(s) that show up to Guild meetings (selected/managed by the community group). 

The intent here is that a 66% community vote could a group that has been selected by FF to fill a seat; this is the veto mentioned above. If a group were voted out, FF would need to choose a different community group to better represent this function. 

- Reasonably, we may also need to specify that any proposed veto of a representative group ALSO needs to name a new group to replace them. This is a bit complicated, which is why I originally omitted it.  
- A community veto should/would be a rare thing, in part because active participants and working groups in the Filecoin ecosystem remain small. The intent of this detailed rulemaking is to prevent against future abuse. 
   -  A reasonable hypothetical for knowing when these rules/requirements may be important is to consider a schism or "fork" of the SP Working Group. If there are two working groups that each claim to represent SP interests, and which refuse to work together, which group legitimately gets to join the Guild?

2023-10-19 22:25 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
> +        * Though the Filecoin Foundation maintains the ability to appoint representative groups to join the Guild, the community can vote to remove representative groups.  In these instances, a "supe
@LukeHolon 66% is an arbitrary figure! Generally speaking, 66% is considered a statistical "supermajority".  The [draft spec](https://docs.google.com/document/d/13910NE-O3mUQ6rztt6f3xe7hwW_aS-xaPW_zHuTpBW4/edit#heading=h.4kbcnjlru68f) we have for voting breaks out different community functions with different ways of determining vote power, which reinforces the idea of 66% as a high threshold (I can explain this further if you'd like, but will omit it here for brevity). 

A 75% acceptance threshold is more common in blockchain voting structures because: 
1) when your vote power is solely a function of your token holdings, your voters are much more likely to operate as a single block, and; 
2) there are often few total participants (compared to overall network size).  A small pool of contributors means less diversity of opinion, and thus 75% agreement is achievable and appropriate. 

It could be with time that 75% is more appropriate than 66% and we need to make that change. Or, if you have a strong argument now as to why we should choose one threshold over another, I'm happy to make the change. 

And yes- voting will be anonymous-ish (with votes associated with Filecoin wallets), but Guild votes will not. Representatives will need to represent their groups, and justify their votes/preferences. The Guild exists to provide many checks and balances on voting, and this is one of them.  Does that address your concern?

2023-10-19 22:29 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
> +    * The Filecoin Foundation acts as the Chair of the Filecoin Community Guild.  The Foundation is thus obligated to 1) appoint representative groups to the Guild, 2) provide material support to ens
The Foundation makes decision to coordinate Guild work and function, though there is still a community veto upon the Foundation's ability to make appointments. 

I can see this appearing as "centralization" in the sense that one seat has disproportionate power in certain regards, but these rules were written with an intent to check that power.  In addition, the role that the Foundation has been given doesn't necessarily affect operations of the Guild; if the Foundation were to disappear, the Guild could still form. 

If we remove the Foundation as the seat of the Guild, how should we fund this body, appoint members, and make rules for it? My expectation is that, with time, the role that the Guild is play will change dramatically in operation, and many parts of this functionality could be automated and/or brought on chain. In this initial phase, however, I don't think this scoped role for FF is inappropriate.

2023-10-19 22:54 UTC, LukeHolon commented on FIPS/fip-0001.md
> +        * Though the Filecoin Foundation maintains the ability to appoint representative groups to join the Guild, the community can vote to remove representative groups.  In these instances, a "supe
Thanks @kaitlin-beegle. I think its fine to start at 66% and assess effectiveness down the track. Good that Guild votes are not anonymous and open to public scrutiny. Any way to shift/tag/link filecoin wallets to specific identified voters (ie., real people representing their organisation), or is this something being worked on for the future?

2023-10-20 12:44 UTC, jsoares commented on FIPS/fip-0001.md
> +            * All Guild votes must be documented and supported.
I don't see an issue with the security FIP progress and discretion given to core devs; it's hard to fully specify what will be somewhat ad hoc based on the circumstances. But it's a weakly held opinion.

2023-10-20 12:52 UTC, willscott commented on FIPS/fip-0001.md
> +    * The Filecoin Foundation acts as the Chair of the Filecoin Community Guild.  The Foundation is thus obligated to 1) appoint representative groups to the Guild, 2) provide material support to ens
* if we define what a community veto looks like for appointments, that would be a reasonable limitation on power.
* how would the guild form without any entity to appoint missing stakeholders? is there a path to legitimacy here if the foundation abstains to name a representative that the rest of the community / some factions of stakeholders favor?
    * I think my main concern in this structure is to make sure that misalignment doesn't potentially lead to deadlocks

2023-10-20 12:56 UTC, willscott commented on FIPS/fip-0001.md
> +1. For **Level 1 security threats**, a FIP should be written for review and approval by the Filecoin Community Guild. Guild members will be asked to accept or reject the FIP; they may not abstain. Th
For security FIPs, i would like to understand what expectations around confidentiality are put on:
1. the appointed guild-member groups
2. the representatives from the guild-member groups that show up to a guild meeting.

how large of a circulation are potentially security issues going to see before mitigation? how much risk is that taking on, and what expectations for data protection / siloing are we able to put in place here?

With core devs there's a specific list of humans who are expected to not reveal security issues past that group until after an embargo. With this structure the limits for information sharing seem more risky / less clear.

2023-10-24 19:59 UTC, anorth commented on FIPS/fip-0001.md
> +created: 2023-10-15
As a practical matter, for most FIPs we encourage a draft version of the text to be merged as an easily linkable and understandable document, something that the community can consume without staring at funny red and green highlights etc. Then this draft can evolve with more PRs as the discussion prompts changes. And then finally a very small PR updates status when governance processes are done.

A PR against this FIP-0001 can't follow that process. There's not an obvious document to share widely (yes, a clean view can be obtained from GitHub, but it's not obvious). As changes are made, they will be harder to see and discuss explicitly. And as an editor it's harder to decouple pure editorial feedback and process from the broader governance process – I can't approve and land this "draft" without overwriting FIP-0001. If targeting a new document with a status of "draft" we could get an editorial approval very soon (after missing sections are added) which might _support_ the broader discussion and convergence by having a named, visible, linkable document with clear change history.

So whether or not we plan to eventually overwrite FIP-0001 in place, I request that this PR be re-based to create a new document that we can land in draft status to work with. I appreciate the framing as a diff, but the practical outcome it's 80% new content, including all the important stuff. I think the view of the whole proposal is more important to most than the diff. WDYT @filecoin-project/fips-editors ?

2023-10-24 20:48 UTC, jsoares commented on FIPS/fip-0001.md
> +created: 2023-10-15
I am inclined to agree 👍

2023-10-31 10:24 UTC, The-Wayvy commented
@kaitlin-beegle @momack2

I oppose giving 'clients' 20% of the vote since they are mostly self-dealing miners and DC dealers.

We shouldn't reward gamers with extra votes.

I suggest increasing their weighting from 0% to 20% over 4 years.

[voting specification](https://docs.google.com/document/d/13910NE-O3mUQ6rztt6f3xe7hwW_aS-xaPW_zHuTpBW4/edit#heading=h.4kbcnjlru68f)

2023-10-31 11:59 UTC, The-Wayvy commented
@kaitlin-beegle 

Voting

I propose summing the weighted percentages, rather than having each constituency vote as a block.

If each stakeholder group votes as a block, we could see a FIP rejected despite having 70% of voters in favor.

ex. Voters In Favor of FIP XXXX:

100% RBP
100% Token Holders
49.99% Deal Bytes 
49.99% Core Devs
49.99% EcoSystem Partners

You'd have ~70% of voting power in favor, but the FIP would be rejected 3-2.

2023-11-02 21:59 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
> +created: 2023-10-15
I disagree.  In practice, yes, it's better to have a single text that folks can more easily look at without the direct comparison. 

However, we have long referred to this as "FIP0001v2" to make explicit the fact that we are _replacing_ the current text of FIP0001. Though we do not have many/any(?) precedents for these kinds of FIPs, I would argue that the intent was always for "active" drafts to be replaced for coherency. The purpose of Git changes is to allow for document evolution without having those documents being fragmented across a repo. 

**If consensus is for these changes to be submitted as a new FIP, and for FIP0001 to then be 'superseded' but otherwise remain unchanged, then fine**.  I have updated the PR and you should be able to see the proposed text without contrast.  I am also going to remove "active" as a FIP designation, since it does not seem like there is a meaningful differentiation between "active" and "final" FIPs.

2023-11-02 22:02 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
> +created: 2023-10-15
tl;dr - active status removed.  This will get its own FIP number and FIP0001 will be marked as 'superseded' if/when this FIP is accepted.

2023-11-02 22:22 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
> +    * The Filecoin Foundation acts as the Chair of the Filecoin Community Guild.  The Foundation is thus obligated to 1) appoint representative groups to the Guild, 2) provide material support to ens
Hey @willscott, good points.  As background, I spent much of the last two weeks meeting with counsel to review this structure and ensure that is both appropriately scoped and decentralized. The (short) summary of those (long) conversations is: 

- If community members can replace a group via a vote, and the Foundation cannot interfere in this vote, this is a reasonable check on the Foundation's authority. 
- The explicit assumption is that the Foundation is obligated to name these representatives. 
  -    There is still an open question about which governing rules need to be specified upfront, and which can exist as norms of behavior.  Right now, it's my opinion that any further specification about rules for the Guild should be added to the spec, not to FIP0001v2. 
  - The path to legitimacy for an unpopular representative is removal by vote.  There are also rules (in the FIP0001v2 draft under "FIP Consensus Mechanisms") about what a group needs to do to be legitimate enough to be named.  At this point in the Filecoin community's maturation, there are few (if any) instances where multiple groups are mature enough to claim to legitimately represent a single community faction.  For most of these chairs, there is presently but one option.

2023-11-06 13:25 UTC, jennijuju commented on FIPS/fip-0001.md
> +created: 2023-10-15
> So whether or not we plan to eventually overwrite FIP-0001 in place, I request that this PR be re-based to create a new document that we can land in draft status to work with. I appreciate the framing as a diff, but the practical outcome it's 80% new content, including all the important stuff. I think the view of the whole proposal is more important to most than the diff. WDYT https://github.com/orgs/filecoin-project/teams/fips-editors ?


I agree - the change is sufficient enough to a  point this proposal should be treated as a new organizational FIP that will supersede FIP-0001 upon its acceptance.

2023-11-06 14:09 UTC, jennijuju commented on FIP0001v2
> +Different kinds of FIPs have different requirements for consensus, depending on the scope and complexity of those changes. In general, more complex FIPs must meet a higher bar of review and approval
"more complex" could be subjective - maybe give some examples?

2023-11-06 14:11 UTC, jennijuju commented on FIP0001v2
> +Clarifying details, workflows, and other resources change more frequently and can be found in the Filecoin spec [TODO insert link to GovDocs].
what in https://spec.filecoin.io are we referring to here?

2023-11-06 14:12 UTC, jennijuju commented on FIP0001v2
> +* Anyone can open a PR against the Filecoin spec to update or clarify governance processes.
I don't think Filecoin spec https://spec.filecoin.io convert governance process. if I missed it - could you please share a link?

2023-11-06 14:23 UTC, jennijuju commented on FIP0001v2
> +1. A **Technical FIP** describes any change that affects most or all Filecoin implementations, such as a change to the network protocol, a change in block or transaction validity rules, or any change
```suggestion
1. A **Technical FIP** describes any change that affects most or all Filecoin implementations, such as a change to the network protocol, a change in block or message validity rules, or any change or addition that affects the interoperability of applications using Filecoin. Technical FIPs consist of three parts: a design document, an implementation, and- if warranted- an update to [the formal specification](https://filecoin-project.github.io/specs/).
```

2023-11-06 14:24 UTC, jennijuju commented on FIP0001v2
> +1. A **Technical FIP** describes any change that affects most or all Filecoin implementations, such as a change to the network protocol, a change in block or transaction validity rules, or any change
> if warranted- an update to [the formal specification](https://filecoin-project.github.io/specs/).

if the spec fully reflects the filecoin protocol - then won't  any technical FIP guaranteed to warrant an update to the filecoin spec?

2023-11-06 14:29 UTC, jennijuju commented on FIP0001v2
> +2. A **Cryptoeconomic FIP** primarily seeks to affect economic policy on the network. Though most technical changes could affect network economic elements- including gas fees, token utilization, or o
Please elaborate and define more clearly on what count as in "fundamentally change the economic logic", maybe some example: minting mechanism; mining reserves,  consensus pledge system; gas mechanism, & etc

2023-11-06 14:42 UTC, jennijuju commented on FIP0001v2
> +5.  A **Filecoin Request for Comment (FRC)** is an informational document which suggests standards and best practices for the Filecoin community.  It may suggest rules or procedures, including other
could you please add what  an FRC consists of? (i.e: for technical FIPs, it is specified it requires a design, an **implementation**, and an update to spec. I think for an FRC, a design and an implementation are needed at least

2023-11-06 14:51 UTC, jennijuju commented on FIP0001v2
> +4. A **Security FIP** is drafted to remediate a network policy, bug, or related issue that poses a clear threat to network functionality. There are three levels of security FIP:
TE is a part of the network security. if an CE change is required for the network security, does it follow the security FIP governance process over the CE FIP governance process?

2023-11-06 14:54 UTC, jennijuju commented on FIP0001v2
> +* **Work in progress (WIP)** -- Once the FIP Author has asked the Filecoin community whether an idea has any chance of support, they will write a draft FIP as a [pull request](https://github.com/file
I recommend change this to `FIP discussion` - as that's the starting point of all FIPs. an WIP status has no where to capture as the FIP only gets to merged and getting recorded when the `Draft` is approved and merged.

2023-11-06 16:02 UTC, jennijuju commented on FIP0001v2
> +5.  A **Filecoin Request for Comment (FRC)** is an informational document which suggests standards and best practices for the Filecoin community.  It may suggest rules or procedures, including other
I think at least ONE reference implementation is needed to demonstrate the spec could be realized in production, Imho it's a part of review process of the FRC - ensure the spec is clearly stated and can be verified

2023-11-06 16:09 UTC, jennijuju commented on FIP0001v2
> +  * :x: WIP -- Core Devs maintain the right to strike down WIP Technical FIP drafts that are technically unsound, unable to be implemented, or should otherwise be deprioritized.
> should otherwise be deprioritized.

Is there a reason why prioritization is ought to be defined at this stage? I personally an idea should only be "strike down" if and only if it is 'non sense" and would be wasting time for FIP editors / community to engage. 

> Core Devs maintain the right to strike down WIP Technical FIP drafts

Do you mean core dev or fip editors here?

2023-11-14 08:05 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
> +created: 2023-10-15
OK! Declaring this resolved :)

2023-11-30 22:53 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
> +1. For **Level 1 security threats**, a FIP should be written for review and approval by the Filecoin Community Guild. Guild members will be asked to accept or reject the FIP; they may not abstain. Th
Hey folks! Making another round of updates and want to close the loop here. 

@jsoares is correct - during emergency situations, it is Filecoin Core Devs who should take the lead.  Only during minor, future -looking changes should the Guild have any particular ability to block a proposed change, and this is intended merely as a check on a Core Dev body trying to circumvent the governance process.  Language was previously added to make this clear. 

@willscott, it is my expectation that the terms of confidentiality are managed situationally.  This is how it is done today.  I believe a fair expectation for the Guild is that they may not disclose discussions, decisions, etc., until materials are public, and we will need to develop intraorganizational trust in order for this to work. There is no rulemaking that will ensure confidentiality. 

- The current structure is designed such that security issues are handled quickly and by technical experts, with the Guild primarily playing the role of oversight and documentation post facto. 
- The bigger issues/priority should be Core Devs deciding the order of command for security issues.  This has always been a bit of a black box, and I would love the group to work towards more clearly codified expectations. 
   - Currently, there seems to be interest in opening this group up to more people, which is fine by me.  However, it may then require there to be a sub-committee with particular maintainer credentials, etc., for handling security issues.

2023-11-30 22:53 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
>  However, we also require that, where appropriate, Technical FIPs are also reflected in the protocol's specification, which is the primary source of reference for other developers. The [Filecoin Spec
Addressed.

2023-11-30 22:59 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
> +  * :x: WIP -- Core Devs maintain the right to strike down WIP Technical FIP drafts that are technically unsound, unable to be implemented, or should otherwise be deprioritized.
Firstly, I see @anorth's point, though I'm not sure the language change from "otherwise deprioritized" to "completely ridiculous" leads to a substantive difference in practice. I think the correct balance, perhaps, is with language for WIPs that are "fundamentally underspecified"? Or perhaps "irrelevant to the protocol"? 

Ultimately, executing authority here would come down to Core Devs having the collective will to do so, and it's hard to see that happening (at least, with our current balance of participants, which includes both of us).  However, I think the two language suggestions above are a bit more reasonable to justify, and thus may work better to limit an abuse of authority. 

Let me know if you have further thoughts and/or a preference.

2023-11-30 22:59 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
> +  * :x: WIP -- Core Devs maintain the right to strike down WIP Technical FIP drafts that are technically unsound, unable to be implemented, or should otherwise be deprioritized.
Secondly, @jsoares, agree.  Updated for coherency.

2023-11-30 23:05 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
> +        * This specification[TODO] is an addenda to FIP0001 and can only be changed via FIP.
I am happy to codify a single document for the voting tool, which can be included as an auxiliary file to this FIP. 

The current spec is a dynamic document, the details of which are still being developed.  It is also the case that, through testing and initial roll-out, elements of the detailed spec will need to change in order to support the functionality of the tool; however, the key intent of tool design should be unchangeable. 

Just as we want an updated version of FIP0001 to only enshrine high-order processes and structures, so too should the auxiliary voting spec structure the design intent of the voting tool without impeding changes to functional details.  This can of course be a grey area at times, but I trust that with collaboration and codification we can chart a clear course through it.  

Writing this document has been added to the top of my to-do list 👍 I'll flag it when available.

2023-12-01 00:02 UTC, willscott commented on FIPS/fip-0001.md
> +        * This specification[TODO] is an addenda to FIP0001 and can only be changed via FIP.
I think it is still true that, especially since we say "the specification can only be changed via FIP", we need to know what we are voting on - to vote on a spec doc that is in limbo means we aren't able to justify any of the specific points in flux as having come through the FIP consensus process. We get more legitimacy by having a fixed spec doc linked here.

2023-12-01 02:02 UTC, kaitlin-beegle commented on FIPS/fip-0001.md
> +            3) Openly document and reasonably justify all Guild votes.
Yes; clarified.

2023-12-04 23:16 UTC, jsoares commented on FIP0001v2
> +5.  A **Filecoin Request for Comment (FRC)** is an informational document which suggests standards and best practices for the Filecoin community.  It may suggest rules or procedures, including other
I think that's an artefact of the current process, in that we often don't specify things properly and instead rely on the code to do so. A clearly specified FIP can be clearly stated and verifiable, though, particularly when it doesn't impact the line protocol and can be implemented with differences by different clients (think e.g. TCP congestion control [local] vs. segment structure [global]).

2023-12-07 18:08 UTC, jsoares commented on FIP0001v2
> +5.  A **Filecoin Request for Comment (FRC)** is an informational document which suggests standards and best practices for the Filecoin community.  It may suggest rules or procedures, including other
I did, thanks for catching it!

2024-01-15 14:31 UTC, jsoares commented on FIP0001v2
> +* **Withdrawn** -- A FIP which was merged into the repo, but has sense been abandoned by its Author.  FIP drafts should be considered 'withdrawn' after six months of inactivity.
```suggestion
* **Withdrawn** -- A FIP which was merged into the repo, but was then withdrawn or abandoned by the Author.  FIP drafts should be considered 'withdrawn' after six months of inactivity. 
```

This new *withdrawn* status might be a future solution to the discussion [here](https://github.com/filecoin-project/core-devs/discussions/148#discussioncomment-7858442) (even if I still believe that we have a solution today in _rejected_). For that to be the case, though, we should expand the definition to allow for explicit withdrawal by the author.

2024-01-29 16:17 UTC, willscott commented on FIP0001v2
> +    * A FIP achieves "acceptance" by hard consensus whenever polling generates a >50% (i.e., simple majority) 'accept' outcome.
who is allowed to 'vote' in such a poll / how are votes weighted?

2024-03-21 21:06 UTC, kaitlin-beegle commented
> @kaitlin-beegle what's the status here? The PR has been open for 5 months and inactive for close to 2 months. We should convert it to draft if not in active review.

Hey @jsoares - I'd prefer if you leave it open, not as a draft, though I don't feel strongly about that request. I've left a lot of feedback yet unresolved because we aren't ready to incorporate final changes and push for the next stage of review. 

We've been giving updates in Community Governance Calls; I've also written up the most recent update [HERE](https://filecoinproject.slack.com/archives/C0535S9TUUF/p1711054887861589). 

tl;dr - we're about a quarter behind where we projected to be, and all of it is due to unforeseen complications with on-chain voting specification.  This is a single blocker affecting all other parts of this effort. 

- To support and resolve this, I'm looking to hire a TPM (familiar with smart contracts) to provide support for the next 8 weeks. Fully compensated, of course; I expect the work will require ~25% of their daily capacity.  If you know anyone, I'd be grateful if you sent them my way!

2024-07-02 18:41 UTC, jennijuju commented on FIP0001v2
> +    * The Guild maintains seven seats: one for each [Filecoin community stakeholder group](https://filecoin.io/blog/posts/filecoin-s-island-economy/), and one seat each for Filecoin founding institut
Could you please define “founding institutions” here and elaborate on why they deserve extra seat, outside of their role in the other stakeholder group as defined in the linked post?

2024-07-02 18:45 UTC, jennijuju commented on FIP0001v2
> +        * This specification[TODO] is an addenda to FIP0001 and can only be changed via FIP.
@kaitlin-beegle is the link available somewhere yet?

2024-07-02 18:54 UTC, jennijuju commented on FIP0001v2
> +    * The reference tool and polling specification accepted by the Filecoin community can be found [HERE](https://github.com/black-domain/power-voting).
```suggestion
    * The reference tool and polling specification accepted by the Filecoin Foundation can be found [HERE](https://github.com/black-domain/power-voting). 
```

2024-07-02 18:57 UTC, jennijuju commented on FIP0001v2
> +* **Hybrid Consensus (Filecoin Community Guild)** -- The Filecoin Community Guild is a representative expert council that provides guidance, coordinates debate, and executes decision-making on behalf
I’m less sure hybrid consensus is the best way for progressing security FIPs - do we expect all guild groups provide effective input towards security matters? Some security fips may need the while community to move fast to resolve - how fast can this process move?

2024-07-02 19:00 UTC, jennijuju commented on FIP0001v2
> +    * The Filecoin Foundation acts as the Chair of the Filecoin Community Guild.  The Foundation is thus obligated to 1) appoint representative groups to the Guild, 2) provide material support to ens
How FF makes decisions on 1 here needs to be transparent

2024-07-02 19:08 UTC, jennijuju commented on FIP0001v2
> +**Consensus for Technical FIPs can be determined by soft consensus *OR* hard consensus.**
Hybrid Consensus?

2024-07-02 19:09 UTC, jennijuju commented on FIP0001v2
> +Prior to the Last Call Period, the FIP Author will work with FIP Editors to determine the most appropriate consensus mechanism.  In most cases, soft consensus will be the most appropriate pathway.  H
> FIP Editors to determine the most appropriate consensus mechanism

This is introducing new responsibilities for FIP editors and should be documented.

2024-07-02 19:18 UTC, jennijuju commented on FIP0001v2
> +**Consensus for cryptoeconomic and governance FIPs is determined by both community vote and Community Guild approval.**
This seems to be a very expensive operation. My understanding is that the community guild is proposed as the guilld that can represent key stakeholder groups in Filecoin communit. If so, community vote shouldnt be necessary. If no, maybe it is not meaningful for community guild to exist in the first place (proposed guild members can just vote as the community)

2024-07-02 19:18 UTC, jennijuju commented on FIP0001v2
> +    * A vote will be held to determine community consensus to accept or reject.
is it onchain voting?

2024-07-02 19:20 UTC, jennijuju commented on FIP0001v2
> +1. For **Level 1 security threats**, a FIP should be written for review and approval by the Filecoin Community Guild. Guild members will be asked to accept or reject the FIP; they may not abstain. Th
is there a level of categorization?

2024-07-02 19:23 UTC, jennijuju commented on FIP0001v2
> +- Security Considerations - All FIPs must contain a section that discusses the security implications/considerations relevant to the proposed change. Include information that might be important for se
why is product consideration removed?

2024-07-02 19:24 UTC, jennijuju commented on FIP0001v2
> +- Specification - The specification should describe the syntax and semantics of any new feature or process. Technical specifications should be detailed enough to allow competing, interoperable implem
specification should include migration details

2024-07-03 22:49 UTC, kaitlin-beegle commented on FIP0001v2
> +        * This specification[TODO] is an addenda to FIP0001 and can only be changed via FIP.
Sorry @jennijuju, which link? To the polling spec and repos?

2024-07-03 23:20 UTC, kaitlin-beegle commented on FIP0001v2
> +* **Hybrid Consensus (Filecoin Community Guild)** -- The Filecoin Community Guild is a representative expert council that provides guidance, coordinates debate, and executes decision-making on behalf
The processes for security FIPs are enumerated below- can you look at that section and let me know which/if the three categories of security FIP/consensus are of concern to you? 

The general gist is that the higher risk the scenario, the quicker individuals are empowered to act.

2024-07-03 23:21 UTC, kaitlin-beegle commented on FIP0001v2
> +**Consensus for Technical FIPs can be determined by soft consensus *OR* hard consensus.**
Sorry- what is the question? Hybrid consensus isn't an option for technical FIPs; it does not seem necessary.  Are you asking that it be made an option?

2024-07-03 23:24 UTC, kaitlin-beegle commented on FIP0001v2
> +Prior to the Last Call Period, the FIP Author will work with FIP Editors to determine the most appropriate consensus mechanism.  In most cases, soft consensus will be the most appropriate pathway.  H
Yes, this would be the documentation. We have also added it to a FIP Editor handbook, which will be pushed to the Filecoin docs site once approved (currently in internal review)

2024-07-03 23:28 UTC, kaitlin-beegle commented on FIP0001v2
> +**Consensus for cryptoeconomic and governance FIPs is determined by both community vote and Community Guild approval.**
Could you please explain what you mean by 'expensive'? The intent of this function is to formalize oversight of critical FIPs and empower the work that folks are already doing. The cost of providing hosting platforms for meetings, etc., will be absorbed by the Foundation; I also think it's negligible compared to the potential cost of a poorly implemented cryptoeconomic or governance policy. 

Apologies, but I'm not sure what is meant by the second part of your comment.  Yes, the Guild is supposed to represent groups of stakeholders, and it is also supposed to vote.  Representative voting functions are very different from private, individual voting functions; that's the mechanism by which oversight and deliberation are introduced for complicated FIPs.

2024-09-05 04:57 UTC, lanzafame commented on FIP0001v2
> +![](https://hackmd.io/_uploads/Skhq4iwZT.png)
Link is broken or doesn't have public access

2024-09-05 04:57 UTC, lanzafame commented on FIP0001v2
> +            * Guild members can vote to Accept, Reject, or Abstain.  Votes cast in abstention will automatically count towards the majority preference. In instances of an equal vote split (e.g., 3/3
Abstain votes should count towards the Community Vote majority (hard consensus), not the Community Guild majority. If the "expert" representatives abstain, it should not fall to a fewer number of expert votes but to the community vote.

2025-02-13 18:55 UTC, closed without merging

2025-03-03 22:09 UTC, dannyob commented
@kaitlin-beegle I'm sorry I missed this earlier! Thank you so much for your work, and we are indeed taking up the pieces of your work and taking them forward. I think you're right in that this commit isn't the best place to proceed, but don't worry, much of your work will be incorporated in these reforms.