Aggregation frc
filecoin-project/FIPs pull request #879
Opened 2023-12-07 16:14 UTC by aashidham

Create aggregation FRC. More edits to come before finalization.

2023-12-07 17:00 UTC, willscott commented on FRCs/frc-0070.md
> +- Retrieval endpoint for Filecoin retrieval: GET /data/<pieceCID>
Is there an example of a market implementation on filecoin that supports data at this path?

I believe boost would expose these pieces at `/piece/<pieceCID>`, fwiw

We should also specify the expectation for how an aggregator supporting this standard would define where it's HTTPS endpoint for the data layer is located.

2023-12-13 11:24 UTC, jsoares requested changes
I'm confused about the scope of this PR. 
* It's adding two new files (FRC-0067.md and FRC-0070.md)
* FRC-0067.md seems to correspond to existing FRC-0068.md 
* FRC-0070.md claims to be FRC-0068 in the metadata, is using an unassigned and conflicting FIP number in filename, and has seemingly the same title as FRC-0068. 

I think part of this is due to having been branched out of an older branch, but can we clean this up prior to substantive review? There should only be one RFC here, no unassigned numbers, and no recommitting of existing files. The metadata for the new RFC should match its content.

2023-12-13 11:24 UTC, jsoares commented on FRCs/frc-0070.md
> +fip: "0068"
```suggestion
fip: "**TODO**" 
```

2023-12-13 11:24 UTC, jsoares commented on FRCs/frc-0070.md
> +title: Deal making between SPs and FVM contracts
```suggestion
title: "FVM-Enabled Deal Aggregation"
```

2023-12-13 16:41 UTC, aashidham commented on FRCs/frc-0070.md
> +title: Deal making between SPs and FVM contracts
Yes this may be my PR-fu lacking. This comes from a prior forked repo of FIPs, which already had a PR with FRC-0067.md / FRC-0068.md already merged into the master FIPs branch (like you said).

Should I delete the repo, make a new fork and make a new PR with only  FRC-0070.md?

2023-12-13 20:39 UTC, jsoares commented on FRCs/frc-0070.md
> +title: Deal making between SPs and FVM contracts
The easiest way forward is to delete frc-0067.md in this branch + rename frc-0070.md --> frc-xxxx.md. I don't think you need a new fork & PR. I can do it too; leaving it to your discretion.

2023-12-14 00:48 UTC, aashidham commented on FRCs/frc-0070.md
> +title: Deal making between SPs and FVM contracts
Done, (I think) correctly. Please have a look and ping if something is still off.

2023-12-14 08:35 UTC, jsoares commented on FRCs/frc-0070.md
> +title: Deal making between SPs and FVM contracts
Looks good, thanks.

2023-12-17 23:24 UTC, rvagg commented on FRCs/frc-xxxx.md
> +- Retrieval gateway for IPFS retrieval: https://gateway/ipfs/<pieceCID>
I think this is using the client's piece CID here, rather than the aggregated piece CID, correct? I like the use of `commPc` above to differentiate from `commPa`, perhaps that could be used here to disambiguate what this is referring to? They look very close to existing boost retrieval endpoints, with `/piece/` instead of `/data/` today, but those are for stored deal pieces, of `commPa` (I don't _think_ we do anything fancy with `/piece/` retrievals on PoDSI deals today yet anyway).

2023-12-17 23:24 UTC, rvagg commented on FRCs/frc-xxxx.md
> +				uint64 marketActorId; // The actor ID of the storage market in which the deal representation is stored. dealId is scoped by marketActorId
```suggestion
        uint64 providerId;  // The storage provider that is storing the data for the deal.
        uint64 marketActorId; // The actor ID of the storage market in which the deal representation is stored. dealId is scoped by marketActorId
```

2023-12-17 23:25 UTC, rvagg commented on FRCs/frc-xxxx.md
> +																					uint256 _renew_threshold);
```suggestion
    event SubmitAggregatorRequestWithRaaS(uint256 indexed id, bytes cid, uint256 _replication_target, uint256 _repair_threshold, uint256 _renew_threshold);
```

2023-12-17 23:26 UTC, rvagg commented on FRCs/frc-xxxx.md
> +     * @notice Function to submit a new file to the aggregator, specifing the raas parameters
```suggestion
    /**
     * @notice Function to submit a new file to the aggregator, specifing the raas parameters
```

2023-12-17 23:26 UTC, rvagg commented on FRCs/frc-xxxx.md
> +									       uint256 memory _renew_threshold);
```suggestion
     */
	function submitRaaS(bytes memory _cid, bytes memory _fetchLink, uint256 memory _replication_target, uint256 memory _repair_threshold, uint256 memory _renew_threshold);
```

2023-12-17 23:27 UTC, rvagg commented on FRCs/frc-xxxx.md
> +				uint64 _marketActorId,
```suggestion
        uint256 _id,
        uint64 _marketActorId,
```

2023-12-17 23:27 UTC, rvagg commented on FRCs/frc-xxxx.md
> +				uint64 marketActorId; // The actor ID of the storage market in which the deal representation is stored. dealId is scoped by marketActorId
```suggestion
        uint64 providerId;  // The storage provider that is storing the data for the deal.
        uint64 marketActorId; // The actor ID of the storage market in which the deal representation is stored. dealId is scoped by marketActorId
```

2023-12-17 23:28 UTC, rvagg commented on FRCs/frc-xxxx.md
> +
```suggestion
    event SubmitAggregatorRequestWithRaaS(uint256 indexed id, bytes cid, uint256 _replication_target, uint256 _repair_threshold, uint256 _renew_threshold);

```

2023-12-17 23:28 UTC, rvagg commented on FRCs/frc-xxxx.md
> +     * @notice Function to submit a new file to the aggregator, specifing the raas parameters
```suggestion
    /**
     * @notice Function to submit a new file to the aggregator, specifing the raas parameters
```

2023-12-17 23:28 UTC, rvagg commented on FRCs/frc-xxxx.md
> +
```suggestion
		function submitRaaS(bytes memory _cid, bytes memory _fetchLink, uint256 memory _replication_target, uint256 memory _repair_threshold, uint256 memory _renew_threshold);

```

2023-12-17 23:28 UTC, rvagg commented on FRCs/frc-xxxx.md
> +				uint64 _marketActorId,
```suggestion
        uint256 _id,
        uint64 _marketActorId,
```

2023-12-17 23:34 UTC, rvagg commented on FRCs/frc-xxxx.md
> +    bytes32[] path;
Is it a concern at all that this could be a _very_ large value where aggregating very small pieces into very large deals? How does that impact gas or consumption of the `complete()` even when using the on-chain form of this (asking from a position of relative naivety about how this gets used in practice)?

2023-12-19 21:58 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +- Retrieval gateway for IPFS retrieval: https://gateway/ipfs/<pieceCID>
Yes this is referring to client piece CID. We had a call with Will to align on these, so that it is consistent with the piece retrieval gateway FRC https://github.com/willscott/FIPs/blob/3c073e89d5c2df1b24742af748c4fbacb4e06846/FRCs/piece-gateway.md. 

Note that this PR is not updated (@aashidham will be updating it soon), you can see the latest draft for retrieval section here https://github.com/willscott/FIPs/blob/3c073e89d5c2df1b24742af748c4fbacb4e06846/FRCs/piece-gateway.md

2023-12-19 22:04 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +    bytes32[] path;
The idea is not to store proof onchain, proof is verfied at complete callback and we recommend aggregators to store it in offchain db with associated endpoint for client to access proof offchain as needed. If aggregator wants to do this onchain, we generally recommend doing it on L2 (IPC) to save cost

2024-01-04 21:01 UTC, kaitlin-beegle commented on FRCs/frc-xxxx.md
> +Filecoin deal-making flows for small files previously required trusted offchain aggregators to consolidate small files into a storage deal with a Filecoin Storage Provider. This FRC proposes a robust
```suggestion
Filecoin deal-making flows for small files previously required trusted offchain aggregators to consolidate small files into a storage deal with a Filecoin Storage Provider. This FRC proposes a robust standard for an FEVM smart contract to act abstractly as an aggregator, enabling use cases for trustless aggregation, storage of small files on Filecoin, and composability with other onchain data organiations on FEVM (including dapps and DataDAOs).
```

2024-01-04 21:03 UTC, kaitlin-beegle commented on FRCs/frc-xxxx.md
> +Filecoin deal-making flows for small files previously required trusted offchain aggregators to consolidate small files into a storage deal with a Filecoin Storage Provider. This FRC proposes a robust
Correct me if I'm wrong, but this FRC doesn't remove the requirement that small data files be aggregated by third-parties in order to be enabled in a storage deal, yes? This FRC puts forth a standard for doing so, but doesn't affect the need, correct? 

If so, we need to amend the simple summary.

2024-01-04 21:04 UTC, kaitlin-beegle commented on FRCs/frc-xxxx.md
> +This proposal presents the `I*DataAggregator` set of interfaces for the Filecoin Virtual Machine (FVM) along with its reference implementation. This family of interfaces manages storage deal creation
Is the standard to write "FEVM" or "FVM"? The author uses 'FEVM' in the summary and 'FVM' here.  Please standardize.

2024-01-04 21:07 UTC, kaitlin-beegle commented on FRCs/frc-xxxx.md
> +These also ensures data inclusion through PoDSI inclusion proof verification. PoDSI is described in [FRC-58 Verifiable Data Aggregation](https://github.com/filecoin-project/FIPs/blob/e913fea0f32cf412
```suggestion
These also ensures data inclusion through Proof of Data Segment Inclusion (PoDSI) proof verification. PoDSI proofs are described in [FRC-58 Verifiable Data Aggregation](https://github.com/filecoin-project/FIPs/blob/e913fea0f32cf412474f48600f29dbe9753b3d0c/FRCs/frc-0058.md) and allow aggregators to certify that the client’s data has been accurately aggregated.
```

2024-01-04 21:10 UTC, kaitlin-beegle commented on FRCs/frc-xxxx.md
> +This proposal additionally supports Renew/Replication/Repair-as-a-Service (RaaS) full interface, where clients can specify flexible RaaS term deals with aggregator to define the renew period, replica
```suggestion
This proposal additionally supports Renew/Replication/Repair-as-a-Service (RaaS) full interface, where clients can specify flexible RaaS term deals with aggregators. An aggregator would then honor the provided deal terms with associated storage providers and perform the callback/emit event when the job is completed. More details on the aggregator-implemented RaaS full interface workflow can be found [here](https://docs.google.com/presentation/d/11wurlsTFo7ojtDI3UKzU1JA9Ploy3-VduuJ5dJciW80/edit#slide=id.g253ed1e380a_1_122).
```

2024-01-04 21:11 UTC, kaitlin-beegle commented on FRCs/frc-xxxx.md
> +Standardizing these interfaces allows various aggregators to offer a set of uniform methods for submitting storage deal creation requests and storing the deal metadata. This enhances community portab
```suggestion
Standardizing these interfaces allows various aggregators to offer a set of uniform methods for submitting storage deal creation requests and storing the deal metadata. This enhances community portability across different aggregators and promotes compatibility amongst tools and libraries. 
```

2024-01-04 21:15 UTC, kaitlin-beegle commented on FRCs/frc-xxxx.md
> +Note that this FRC can be built on both FVM mainnet as well as IPC subnets. The latter can be more gas efficient, but may not feature the variety of SPs available on SP mainnet. Over time, we expect
```suggestion
Note that this FRC can be built on both FVM mainnet as well as IPC subnets. The latter can be more gas efficient, but may not feature the variety of SPs available on SP mainnet. Over time, we expect that gas costs may push more SPs and builders implementing this standard to do so on IPC subnets. 
```

2024-01-04 21:16 UTC, kaitlin-beegle commented on FRCs/frc-xxxx.md
> +Note that currently this FRC does not cover paid deals, as well as managing escrow for paid deals. However we expect that future versions of this FRC may incorporate these flows.
```suggestion
Note that currently this FRC does not currently describe a standard aggregation workflow for paid deals and/or paid deal escrow. 
```

2024-01-04 21:18 UTC, kaitlin-beegle commented on FRCs/frc-xxxx.md
> +The main audience of this standard is aggregators running in the PLN that want to leverage onchain primitives to trustlessly aggregate data. They should leverage this approach when they want to make
```suggestion
The main audience of this standard is aggregators that want to leverage onchain primitives to trustlessly aggregate data. They should leverage this approach when they want to make their operations transparent to clients, SPs and other onchain indexers. They should also leverage this standard when they want to make their aggregation composable with other data organizations (such as Dapps and DataDAOs) being built on FVM / IPC. We expect substantial adoption of this standard across these aggregators. 
```

2024-01-04 21:20 UTC, kaitlin-beegle requested changes
Preliminary editorial review completed.  Overall, structure and logic look good.

2024-01-11 10:02 UTC, jsoares submitted a review, later dismissed

2024-01-16 22:46 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +Filecoin deal-making flows for small files previously required trusted offchain aggregators to consolidate small files into a storage deal with a Filecoin Storage Provider. This FRC proposes a robust
that's correct. which part of the summary do you find confusing?

2024-01-16 22:48 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +This proposal presents the `I*DataAggregator` set of interfaces for the Filecoin Virtual Machine (FVM) along with its reference implementation. This family of interfaces manages storage deal creation
Thanks, perhaps we should use FVM for all places in this FIP? @aashidham

2024-01-18 02:02 UTC, aashidham commented
Yes that makes sense.

On Tue, Jan 16, 2024 at 5:49 PM Honghao Qiu ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In FRCs/frc-xxxx.md
> <https://github.com/filecoin-project/FIPs/pull/879#discussion_r1454165743>
> :
>
> > +author: ***@***.***, @raulk, @nonsense, @honghao"
> +discussions-to: https://github.com/filecoin-project/FIPs/discussions/866
> +status: Draft
> +type: FRC
> +created: 2023-10-07
> +---
> +
> +# FVM-Enabled Deal Aggregation
> +
> +## Simple Summary
> +
> +Filecoin deal-making flows for small files previously required trusted offchain aggregators to consolidate small files into a storage deal with a Filecoin Storage Provider. This FRC proposes a robust standard for an FEVM smart contract to act abstractly as an aggregator, enabing use cases for trustless aggregation, storage of small files on Filecoin, and composibility with other onchain data organiations on FEVM (including dapps and DataDAOs).
> +
> +## Introduction
> +
> +This proposal presents the `I*DataAggregator` set of interfaces for the Filecoin Virtual Machine (FVM) along with its reference implementation. This family of interfaces manages storage deal creation requests and (optionally) stores relevant deal metadata, including `deal_id` and`provider_id`.
>
> Thanks, perhaps we should use FVM for all places in this FIP? @aashidham
> <https://github.com/aashidham>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/filecoin-project/FIPs/pull/879#discussion_r1454165743>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAF66SJQ24NYOIXK6IAS3QDYO37WNAVCNFSM6AAAAABALKEOPKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMRVGUZTCOJWGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-01-18 05:18 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +Filecoin deal-making flows for small files previously required trusted offchain aggregators to consolidate small files into a storage deal with a Filecoin Storage Provider. This FRC proposes a robust
Fixed in new PR

2024-01-18 05:19 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +This proposal presents the `I*DataAggregator` set of interfaces for the Filecoin Virtual Machine (FVM) along with its reference implementation. This family of interfaces manages storage deal creation
Fixed in new PR

2024-01-18 05:21 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +These also ensures data inclusion through PoDSI inclusion proof verification. PoDSI is described in [FRC-58 Verifiable Data Aggregation](https://github.com/filecoin-project/FIPs/blob/e913fea0f32cf412
Fixed in new PR

2024-01-18 05:21 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +This proposal additionally supports Renew/Replication/Repair-as-a-Service (RaaS) full interface, where clients can specify flexible RaaS term deals with aggregator to define the renew period, replica
Fixed in new PR

2024-01-18 05:22 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +Standardizing these interfaces allows various aggregators to offer a set of uniform methods for submitting storage deal creation requests and storing the deal metadata. This enhances community portab
Fixed in new PR

2024-01-18 05:22 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +Note that this FRC can be built on both FVM mainnet as well as IPC subnets. The latter can be more gas efficient, but may not feature the variety of SPs available on SP mainnet. Over time, we expect
Fixed in new PR

2024-01-18 05:23 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +Note that currently this FRC does not cover paid deals, as well as managing escrow for paid deals. However we expect that future versions of this FRC may incorporate these flows.
Updated in new PR

2024-01-18 05:23 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +The main audience of this standard is aggregators running in the PLN that want to leverage onchain primitives to trustlessly aggregate data. They should leverage this approach when they want to make
Updated in new PR

2024-01-18 05:23 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +				uint64 marketActorId; // The actor ID of the storage market in which the deal representation is stored. dealId is scoped by marketActorId
Fixed in new PR

2024-01-18 05:24 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +     * @notice Function to submit a new file to the aggregator, specifing the raas parameters
Fixed in new PR

2024-01-18 05:24 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +									       uint256 memory _renew_threshold);
Fixed in new PR

2024-01-18 05:25 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +				uint64 _marketActorId,
Fixed in new PR

2024-01-18 05:25 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +				uint64 marketActorId; // The actor ID of the storage market in which the deal representation is stored. dealId is scoped by marketActorId
Fixed in new PR

2024-01-18 05:25 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +
Fixed in new PR

2024-01-18 05:26 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +     * @notice Function to submit a new file to the aggregator, specifing the raas parameters
Fixed in new PR

2024-01-18 05:27 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +
Fixed in new PR

2024-01-18 05:27 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +				uint64 _marketActorId,
Fixed in new PR

2024-01-18 23:26 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +- Retrieval gateway for IPFS retrieval: https://gateway/ipfs/<pieceCID>
Fixed in new PR

2024-01-18 23:31 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +																					uint256 _renew_threshold);
Fixed here https://github.com/filecoin-project/FIPs/pull/879/commits/522c60716af93a1972e94bd0c24b75347f3cac61

2024-01-19 23:58 UTC, honghaoq approved these changes

2024-01-25 02:55 UTC, rvagg commented on FRCs/frc-xxxx.md
> +																					uint256 _renew_threshold);
@honghaoq doesn't seem to be fixed yet, it's fixed in `IOnchainDataAggregator` but not `IOffchainDataAggregator`

2024-01-26 10:42 UTC, honghaoq commented on FRCs/frc-xxxx.md
> +																					uint256 _renew_threshold);
Done https://github.com/filecoin-project/FIPs/pull/879/commits/1d850a235730a38eaebbd80dbf478f93f12b3de5 Good catch:)

2024-02-01 16:19 UTC, kaitlin-beegle approved these changes

2024-02-01 18:32 UTC, honghaoq commented
> This looks like a reasonable reflection of how data segment indexed data is being structured and made accessible at least in boost. I am in favor of the FIP editors merging this FRC

Thanks @willscott, can you approve in the code review, looks like it needs 3 approvals to be able to merge

2024-02-02 14:53 UTC, willscott commented
> can you approve in the code review, looks like it needs 3 approvals to be able to merge

I'm not able to approve - you need two fip editors / code owners, as I understand the process.

2024-02-05 20:48 UTC, anorth commented
I'm assigning number 0087 to this FRC. Please update the header and filename, and also add an appropriate line to the table in README.md

2024-02-08 21:11 UTC, honghaoq approved these changes

2024-02-08 21:16 UTC, honghaoq approved these changes

2024-02-08 21:18 UTC, honghaoq commented
> I'm assigning number 0087 to this FRC. Please update the header and filename, and also add an appropriate line to the table in README.md

Updated: https://github.com/filecoin-project/FIPs/pull/879/commits/fdd0dc78b962bea37ee399aa27e6c3389f266887
and FIP readme PR: https://github.com/filecoin-project/FIPs/pull/937/files 

@anorth can you help approve it? my understanding is we need your approval so @aashidham can merge this PR, thanks

2024-02-08 21:26 UTC, anorth commented
Please rename the file to frc-0087. If you are able, please also change the README in this same PR so they land together.

2024-02-08 21:27 UTC, anorth commented on FRCs/frc-xxxx.md
> +# FVM-Enabled Deal Aggregation
This title doesn't match the title metadata. Please make them consistent, and also with the title listed in the README

2024-02-09 15:35 UTC, aashidham commented
Title metadata, README and file name have all been altered to reflect the latest.

@honghaoq your edits were in a separate patch branch, you have privileges to make changes directly on aggregation-frc branch. I do not have privileges to merge this PR Honghao, that is in the CODEOWNERS purview.

@anorth have a look and let me know if things are good to merge

2024-02-12 21:10 UTC, anorth approved these changes

2024-02-12 21:10 UTC, merged