Update fip-0086.md (Changes to synchronization and heaviest tipset cl…
filecoin-project/FIPs pull request #953
Opened 2024-03-05 15:51 UTC by ranchalp

…arification)

- Implemented changes to synchronization of participants (only exponential back-off atm)
- Mention to heaviest tipset not being actually about weight but blockheight suffices (clarification).

## Are you drafting a new FIP?
Please follow these guidelines to help ensure that your proposal is set up for success in the governance process.

### Open a discussion topic
Changes to the Filecoin core protocol proceed through open discussion.
Please open a new discussion topic in the FIPs repository discussion board and outline you motivation and proposal.

The FIP format is suitable for specifying a concrete protocol change for implementation, 
but your discussion post should describe more of the background and problem to be solved,
outline a range of approaches and their tradeoffs, and invite participants to explore other solutions.

Historically, failing to gain some community buy-in before submitting a FIP has often resulted in 
rejected FIPs and much wasted effort.

### Please use the template
Please draft your FIP by starting with an appropriate template file from templates directory.
Do not significantly change the header table format or section headings.

### Don't claim a FIP number
FIP numbers are allocated by the FIP editors when a draft is ready to be merged into the master branch.
The editors coordinate to ensure allocations to in-flight drafts don't collide.
Please do not allocate yourself a FIP number.

Name your file `fip-my_draft_title.md` (replacing the suffix with an abbreviated title)
and leave "to be assigned" for the FIP number in the header table.
A FIP editor will either inform you of the appropriate number, or insert it themselves when merging.

### Please add your FIP to the README
The top-level README.md file contains a table of all FIPs.
Please add yours there in the same PR that adds the FIP draft itself.
Use XXXX for the FIP number until it is assigned by an editor.

### Delete this guidance and describe your FIP
Once you've followed the guidance above and are ready to submit your FIP draft,
please delete this text and replace it with a copy of the _Abstract_ from your draft, 
and a link to the relevant discussion forum topic.

2024-03-05 15:53 UTC, ranchalp commented
@jsoares @anorth see.

Remaining changes (TODO FYI, *not* made in this PR): 
- MakeTicket including instance ID (and some other calls of pseudocode?) (See [go-f3#68](https://github.com/filecoin-project/go-f3/issues/68))
- Optimization for the first round (See [go-f3#95](https://github.com/filecoin-project/go-f3/issues/95))

2024-03-05 20:04 UTC, anorth approved these changes

2024-03-05 20:56 UTC, jsoares approved these changes
Changes look good. We could incorporate the couple of todos in this same PR, but fine to do it separately too.

2024-03-06 15:53 UTC, ranchalp commented
I will make them here directly and flag when ready.

2024-03-06 17:58 UTC, ranchalp commented
@jsoares @anorth the changes I listed above are done now (and a couple typos corrected). 
Potential TODOs (asking for your opinion). I may do a full review of the FIP in time for the audit, but that can come in a different PR to be merged in time for the audit if (i) I manage to do it and (ii) there are important changes that matter for the audit, which I do not expect.

I also noticed the following TODO in the FIP: 

- [ ] Update and move proofs of correctness and other supplemental documentation into `resources`

The only change I can think of that involves the proofs could be the 2-phase optimization, or we could have a separate section on why the 2-phase optimization does not change anything. But I think this is not a priority for the audit (lmk otherwise and I will find time for this to be done timely).

Otherwise, ready to be merged and we can give closure to FIP changes pre-audit.

2024-03-07 22:09 UTC, jsoares approved these changes

2024-03-07 22:14 UTC, jsoares commented
> Potential TODOs (asking for your opinion). I may do a full review of the FIP in time for the audit, but that can come in a different PR to be merged in time for the audit if (i) I manage to do it and (ii) there are important changes that matter for the audit, which I do not expect.

I'm actually getting a bit nervous about spec and implementation diverging but I trust you on this as you've been knee-deep in both. 

>  Update and move proofs of correctness and other supplemental documentation into resources

I think we'll probably want to review the proofs in time for the internal audit -- or at least clearly identify any deltas. It needn't happen by Monday. 

I'm okay with merging as is, pending @anorth's re-review (@anorth : please do it by EOW so that we leave this in a good state for the audit 🙏 ).

2024-03-07 22:42 UTC, ranchalp commented
anorth already approved the request, but merging is blocked until the rest also approve.

> I'm actually getting a bit nervous about spec and implementation diverging but I trust you on this as you've been knee-deep in both.

[At the time of writing multi-instance consensus is not yet merged nor finished in the code] Actually, the code is quite in line with the spec as detailed in this PR, so need not worry about it I think. But my availability for discussions with auditors could solve whatever we may be missing.

2024-03-07 22:47 UTC, jennijuju approved these changes
Editorial: LGTM

2024-03-11 22:38 UTC, anorth requested changes
This has changed significantly since I reviewed it. Please don't do that 😢 . Retracting my approval until I have time to think about the new changes here. You can get approval back quickly by reverting to only trivial changes.

2024-03-11 23:58 UTC, anorth reviewed
As technical review, I am not confident that the optimisation of skipping a phase is a good one, because I don't believe the assumptions. More https://github.com/filecoin-project/go-f3/issues/95#issuecomment-1989654998

Everything else looks ok.

2024-03-11 23:58 UTC, anorth commented on FIPS/fip-0086.md
> +* Participants set their timeout for the current round to $2*1.3^{r}$ where $r$ is the round number ($r=0$ for the first round).
```suggestion
* Participants set their timeout for the current round to $Δ*1.3^{r}$ where $r$ is the round number ($r=0$ for the first round).
```

2024-03-13 10:59 UTC, jsoares commented
@anorth I think I managed to revert the 2-phase optimisation changes without breaking anything else. Can you review & merge if OK? We should really get this in today.

2024-03-14 18:10 UTC, anorth approved these changes

2024-03-14 18:10 UTC, anorth commented on FIPS/fip-0086.md
> +if m.instance != instance                   | m must match the instance ID
I think this should have `return False` below it.

2024-03-14 18:23 UTC, jsoares commented on FIPS/fip-0086.md
> +if m.instance != instance                   | m must match the instance ID
```suggestion
if m.instance != instance                   | m must match the instance ID
  return False
```

Seems to have been missing already in the original commit, but indeed.

2024-03-14 18:25 UTC, merged