Fip0081 gradual activation
filecoin-project/FIPs pull request #967
Opened 2024-03-19 15:21 UTC by kkarrancsu

This pull request updates FIP0081 to include a ramped activation.  

Pseudocode is provided for how a ramped activation could be realized. The pseudocode is written from the perspective of how to set the Gamma value (`gamma_day`) for each day of the network. This implies that there is a controller that is setting the Gamma value for each day and that controller would be active forever. It is possible to `break` out of the loop after Gamma reaches the target value of 0.7.

This pseudocode omits several realities that need to be taken into account when implementing in the network, including:

- Absolute datetime or epoch numbers, due to the need for this to work in both testnet and mainnet
- What entity/object is computing and setting the Gamma value
- Whether Gamma changes every epoch or every day during the ramping period

2024-03-20 13:23 UTC, kkarrancsu commented on FIPS/fip-0081.md
> +update_day = (datetime(2024,6,1) - datetime.today()).days
Yep - that was what was intended here, let me update.

2024-03-21 01:14 UTC, jsoares reviewed
I might be missing something obvious but introducing a state machine here seems like unnecessary complexity and state, e.g. 
* Do we really need a pre-activation state given it's... erm... pre-activation?
* Why not compute a gamma directly from activation, length, and date, thereby avoiding not just the state but the numerical considerations you mention? Something like $\gamma=0.7+\min(\max(0.3*\frac{(FIP \textunderscore activation \textunderscore date+activation \textunderscore len \textunderscore days) -datettime.today().days}{activation \textunderscore len \textunderscore days},0),0.3)$

Also, the while loop is underspecified as it could run with any frequency, but that's a bit pedantic esp. given your note on needing to choose a period. Regardless of the granularity, this should likely all be defined in epochs (i.e. activation epoch, activation_len_epochs, ...) to not be sensitive to clocks.

2024-03-21 18:54 UTC, kkarrancsu commented
> I might be missing something obvious but introducing a state machine here seems like unnecessary complexity and state, e.g.

I don't disagree with anything you've stated, but this is just pseudocode.  It likely has no correlation to how this would actually be implemented in Lotus, since things such as absolute dates are not available. I wrote it as a state machine because I thought it would be easy to understand.

2024-03-21 21:11 UTC, kaitlin-beegle approved these changes

2024-03-21 22:31 UTC, kkarrancsu commented on FIPS/fip-0081.md
> +to the target.
yep, added, but if unclear or could use further revision lmk and I can update!

2024-04-04 19:06 UTC, anorth requested changes
Thanks. This is helpful in communicating the high level intention of a phase-in to humans. However the pseudocode as written can't function as a specification for implementers due to assuming a context for computation that doesn't match the chain's (which the PR description acknowledges). As such, I don't think we should merge this.

If we do want to merge something as a stepping stone to a full specification, I'd suggest avoiding pseudocode and just writing prose, with a TODO to actually specify how to implement that intent.

2024-04-16 09:31 UTC, ipfsforcezuofu commented
As suggested by @Lucky N. _FF. The PR is closed for now and will be reopened once the implementation details are finalized.

2024-05-07 14:12 UTC, kkarrancsu commented
I've updated the description and removed the pseudocode. Is it clearer now?

2024-05-07 21:18 UTC, anorth commented on FIPS/fip-0081.md
> -- Implementation
This is still TODO. The description of intent is clear enough, but this currently lacks specification of how to achieve it.

2024-05-07 21:23 UTC, anorth reviewed
I tried to view the attached PDF, but could only see 9 blank pages. Can someone else check this? @kkarrancsu do you want to try sending me the file by another channel too?

2024-05-08 01:07 UTC, jsoares commented
> > I tried to view the attached PDF, but could only see 9 blank pages. Can someone else check this? @kkarrancsu do you want to try sending me the file by another channel too?
> 
> Hmm, not sure what happened there but I pushed a new pdf that is hopefully uncorrupted. Will also share directly with you.

The new one works for me.

2024-05-09 19:33 UTC, anorth commented
New PDF 👍

2024-07-02 16:21 UTC, kkarrancsu commented
I've added a link to the draft implementation in the [builtin-actors](https://github.com/filecoin-project/builtin-actors/pull/1557) repository.  Is it OK to move this FIP forward for consideration, while we continue to refine the draft implementation?

2024-07-16 15:55 UTC, kkarrancsu commented
> I've added a link to the draft implementation in the [builtin-actors](https://github.com/filecoin-project/builtin-actors/pull/1557) repository. Is it OK to move this FIP forward for consideration, while we continue to refine the draft implementation?

Hi @jennijuju - gentle ping on this post Eth-CC!

2024-07-18 21:34 UTC, anorth commented
> I've added a link to the draft implementation in the [builtin-actors](https://github.com/filecoin-project/builtin-actors/pull/1557) repository. Is it OK to move this FIP forward for consideration, while we continue to refine the draft implementation?

What do you mean by move this FIP forward? 

My original objection here still stands. The FIP does not specify how to achieve its outcome. From the draft implementation, I know that it has now been worked out how this can be achieved, but it's not represented in this document. This needs to be specified in the FIP. Linking to the code doesn't suffice for this.

I can lift my objection and allow this to merge as a draft, but the FIP will still not be ready for last call, so I don't want to mislead by doing that.

2024-07-22 22:01 UTC, jennijuju commented
@kkarrancsu  - i agree with anorth, lmk if you want to do a pass tgt sometime this week!

2024-07-23 17:04 UTC, kkarrancsu commented
> @kkarrancsu - i agree with anorth, lmk if you want to do a pass tgt sometime this week!

Hi @jennijuju - I've updated the Specification section to include a description of the necessary changes.  Can you review and also help me understand how to think about Migration?

2024-07-25 19:44 UTC, anorth commented on FIPS/fip-0081.md
> +In this section, we describe the changes required to the `builtin-actors` necessary to implement this update.  The high level changes that need to occur is that the ramp configuration needs to be pas
Nit: first sentence is redundant.

2024-07-25 19:44 UTC, anorth commented on FIPS/fip-0081.md
> +1. `CurrentTotalPowerReturnParams` - Add ramp configuration parameters defined above to the `CurrentTotalPowerReturnParams` structure.
This is just a copy of the parameter/return shape defined by the power actor. I think it's sufficient to define the change for the power actor only. Clearly the actors that call into it need to use the right schema. The existence of this copy of the structure is just a code artefact.

2024-07-25 19:44 UTC, anorth commented on FIPS/fip-0081.md
> +### State Data Structures
The text below addresses both state and method parameter/return structures.

2024-07-25 19:44 UTC, anorth commented on FIPS/fip-0081.md
> +2. `CurrentTotalPowerReturn` - Add ramp configuration parameters defined above to the `CurrentTotalPowerReturn` structure.
Ditto

2024-07-25 19:44 UTC, anorth commented on FIPS/fip-0081.md
> +We recommend updating gamma from its current value of 1.0 to the target value of 0.7 over an period of 1Y. The technical reason for this recommendation is that gamma has a direct effect on pledge - c
No "we recommend" in a FIP. Just clearly define what the specification is. The fact that the FIP authors recommend it is implied.

2024-08-06 12:21 UTC, kkarrancsu commented
Hi @anorth @jennijuju  - I think that the remaining changes are completed, can you take a look to see if it's ready to move to the next step?

2024-08-06 22:06 UTC, anorth approved these changes

2024-08-07 23:01 UTC, jsoares approved these changes

2024-08-13 21:45 UTC, kkarrancsu commented on FIPS/fip-0081.md
> +SimpleConsensusPledge = PledgeLockTarget * SectorQAP / max(NetworkBaseline)
This is a pseudocode representation of the SectorInitialConsensusPledge formula given [here](https://spec.filecoin.io/#section-systems.filecoin_mining.miner_collaterals.initial-pledge-collateral).

What was intended to be conveyed here is - we take whatever is larger, either the Baseline or the current QAP to compute the SimpleConsensusPledge.  

They are both scalar values, but what is meant by "scalar and can't be maxed" - I don't think I understand what is mean't to be conveyed here.

2024-08-13 22:21 UTC, jsoares commented on FIPS/fip-0081.md
> +SimpleConsensusPledge = PledgeLockTarget * SectorQAP / max(NetworkBaseline)
The `max()` function returns the larger of _at least_ two values. Even assuming that it accepts a single value, then `max(a)=a`, so it's just visual pollution.

Unless I'm misunderstanding the type of `NetworkBaseline` but I think you confirmed my understanding.

It makes sense in line 61 (and in the original SectorInitialConsensusPledge) because there are, indeed, two arguments.

2024-08-13 23:11 UTC, kkarrancsu commented on FIPS/fip-0081.md
> +SimpleConsensusPledge = PledgeLockTarget * SectorQAP / max(NetworkBaseline)
Oh - I see my mistake now, will correct.  Thanks for the flag.

2024-08-15 19:34 UTC, merged