FIP-XXXX: Add support for legacy Ethereum transactions
filecoin-project/FIPs pull request #995
Opened 2024-04-17 15:43 UTC by aarshkshah1992

This FIP adds support for legacy Homestead Ethereum transactions to Filecoin. 

Note that only legacy Ethereum transactions with the following parameters will be supported.

```
type LegacyEthTx struct {
	Nonce int  
	To *EthAddress
	Value big.Int
	GasPrice big.Int
	GasLimit int  
	Input []byte  
	V big.Int 
	R big.Int 
	S big.Int
}

```

As legacy transactions do not have a `ChainID`, the same signed contract creation transaction can be used to create the contract on multiple chains and ensure that the address of the contract remains the same on all chains. There are some legacy contracts whose users need support for such chain agnostic transactions and contract creation.

Support for EIP-155 and EIP-2930 transactions is deferred to future FIPs.

Discussion at #962.

2024-04-18 03:11 UTC, Stebalien reviewed
This fip is really clear and well written.

2024-04-18 03:11 UTC, Stebalien commented on FIPS/fip-00xx.md
> +Note that this is only a temporary transformation for the purpose of a validating the signature of a legacy transaction and for extracting the public key of the sender from the signature. The `V` val
You know... Can we use `V` to indicate the version (it can only be one of two values right now)?

2024-04-18 03:11 UTC, Stebalien commented on FIPS/fip-00xx.md
> +Under the FVM fee market framework, when processing legacy transactions, `GasPrice` is adapted to simultaneously fulfill the roles of both `GasFeeCap` and `GasPremium`. In this adaptation, both `GasF
Hm... This strongly incentivizes SPs to hoard these transactions until the gas fee drops. Not much we can do about that, I guess...

2024-04-18 05:29 UTC, aarshkshah1992 commented on FIPS/fip-00xx.md
> +Note that this is only a temporary transformation for the purpose of a validating the signature of a legacy transaction and for extracting the public key of the sender from the signature. The `V` val
The problem is that the `V` value is signed by the user. So we can't persist the mutated `V` value to the chain state.

2024-04-18 05:32 UTC, aarshkshah1992 commented on FIPS/fip-00xx.md
> +Under the FVM fee market framework, when processing legacy transactions, `GasPrice` is adapted to simultaneously fulfill the roles of both `GasFeeCap` and `GasPremium`. In this adaptation, both `GasF
The same thing would happen in Ethereum as well for legacy transactions.

2024-04-18 05:35 UTC, aarshkshah1992 commented on FIPS/fip-00xx.md
> +Support for legacy transactions on Filecoin will be enabled by prepending an extra marker byte (arbitrarily selected as  `0x80`) to the signature of legacy transactions. This will allow Filecoin to d
Done.

2024-04-18 16:02 UTC, Stebalien commented on FIPS/fip-00xx.md
> +Note that this is only a temporary transformation for the purpose of a validating the signature of a legacy transaction and for extracting the public key of the sender from the signature. The `V` val
Well,

1. We record _a_ `V` in the signature.
2. There's a `V'` stored/signed in the transaction.

But they don't have to be the same as long as we can derive one from the other.

But... yeah, we could also say 27/28 means "legacy" (I think). I don't feel strongly about this and you're now more familiar with the code than I am, but I'm bringing this up in case it ends up being a simpler/cleaner solution.

2024-04-18 16:03 UTC, Stebalien commented on FIPS/fip-00xx.md
> +Under the FVM fee market framework, when processing legacy transactions, `GasPrice` is adapted to simultaneously fulfill the roles of both `GasFeeCap` and `GasPremium`. In this adaptation, both `GasF
Yep. But it may be worth noting it.

2024-04-18 19:44 UTC, Schwartz10 commented
Hey thanks for putting this together @aarshkshah1992 - one additional thing to note wrt "Change Motivation" - we also just generically get a lot of user's complaining about wallets not working to do simple sends of FIL. For instance, see this email from last night:

![image](https://github.com/filecoin-project/FIPs/assets/12353734/7afae1a0-2c4e-41ce-9271-27004b2af017)

Sending FIL natively from Coinbase wallet (and several others like Trust, Phantom) should "just work". This doesn't seem related to being able to deploy smart contracts, but it's still quite important to fix because many user's are stuck with their FIL in wallets that throw this same error. Their only choice right now is to import their same private keys / seed phrases into a new wallet, which is not a safe practice

2024-04-19 23:11 UTC, jsoares approved these changes
Very well drafted -- I wasn't terribly familiar with the details of eth transaction types but this makes it super clear. Nothing to point out from an editorial perspective.

2024-04-19 23:54 UTC, raulk approved these changes
Excellent write-up! LGTM, just barring some typos and getting 1599 and 1559 mixed up (recommend find & replace all).

2024-04-19 23:54 UTC, raulk commented on FIPS/fip-00xx.md
> +# FIP-00XX: Add support for legacy Homstead Ethereum Trasnactions
```suggestion
# FIP-00XX: Add support for legacy Homestead Ethereum Transactions 
```

2024-04-19 23:54 UTC, raulk commented on FIPS/fip-00xx.md
> +However, for legacy Homstead Ethereum transactions, the value of `V` was arbitrarily set to 27(corresponds to "0" in EIP-1599 transactions) or 28(corresponds to "1" in EIP-1599 transactions) and serv
```suggestion
However, for legacy Homestead Ethereum transactions, the value of `V` was arbitrarily set to 27 (corresponds to `0` in EIP-1559 transactions) or 28 (corresponds to `1` in EIP-1559 transactions) and serves the same purpose of being able to specifically determine the parity of the Y coordinate corresponding to the R component of the signature.
```

2024-04-19 23:54 UTC, raulk commented on FIPS/fip-00xx.md
> +This FIP enhances the Filecoin network by facilitating the execution of legacy Ethereum transactions, thereby bolstering Filecoin's interoperability with the Ethereum network, which already accommoda
This doesn't unlock interoperability with the Ethereum _network_ (that's orthogonal), but it does with unlock interop with this:

```suggestion
This FIP enhances the Filecoin network by facilitating the execution of legacy Ethereum transactions, thereby bolstering Filecoin's interoperability with pre-existing Ethereum tools, libraries, contract suites, and frameworks, which assume such transactions.
```

2024-04-19 23:54 UTC, raulk commented on README.md
> +|[XXXX]() | Add support for legacy Homestead Ethereum transaction | FIP | Aarsh (@aarshkshah1992)| Draft |
```suggestion
|[XXXX]() | Add support for legacy Homestead Ethereum Transactions | FIP | Aarsh (@aarshkshah1992)| Draft |
```

2024-04-19 23:54 UTC, raulk approved these changes
Excellent write-up! LGTM, just barring some typos and getting 1599 and 1559 mixed up (recommend find & replace all).

2024-04-19 23:54 UTC, raulk approved these changes
Excellent write-up! LGTM, just barring some typos and getting 1599 and 1559 mixed up (recommend find & replace all).

2024-04-19 23:54 UTC, raulk approved these changes
Excellent write-up! LGTM, just barring some typos and getting 1599 and 1559 mixed up (recommend find & replace all).

2024-04-20 11:57 UTC, raulk commented on FIPS/fip-00xx.md
> +Filecoin supports EIP-1559 transactions by converting them into standard Filecoin messages. These messages are distinguished by a unique "delegated" signature type, which encapsulates the original Et
In general, we need a subsection on Eth JSON-RPC support. We should scope exactly which methods are affected and how, I think `eth_sendRawTransaction`, `eth_getTransactionByHash`, `eth_getBlockBy*` are all affected.

2024-04-20 11:57 UTC, raulk commented on FIPS/fip-00xx.md
> +## Specification
Have you discarded the need for changes at the EVM runtime level? If so, may be worth stating that explicitly to aid implementers' understanding of scope.

2024-04-20 17:50 UTC, aarshkshah1992 commented on FIPS/fip-00xx.md
> +4. Validate the transaction parameters and signature.
@raulk You mean before verifying the signature, right ? Yes, ofcourse.

2024-04-20 17:50 UTC, aarshkshah1992 commented on FIPS/fip-00xx.md
> +4. Validate the transaction parameters and signature.
But this leading marker byte will ofcourse make it's way to the chain state.

2024-04-22 06:01 UTC, aarshkshah1992 commented on FIPS/fip-00xx.md
> +Under the FVM fee market framework, when processing legacy transactions, `GasPrice` is adapted to simultaneously fulfill the roles of both `GasFeeCap` and `GasPremium`. In this adaptation, both `GasF
Done.

2024-04-22 06:16 UTC, aarshkshah1992 commented on FIPS/fip-00xx.md
> +4. Validate the transaction parameters and signature.
Explicitly noted this.

2024-04-22 06:19 UTC, aarshkshah1992 commented on FIPS/fip-00xx.md
> +type EIP1599Tx struct {
Made this change everywhere.

2024-04-22 06:19 UTC, aarshkshah1992 commented on FIPS/fip-00xx.md
> +type EIP1599Tx struct {
Done.

2024-04-22 06:19 UTC, aarshkshah1992 commented on FIPS/fip-00xx.md
> +The Filecoin network already supports EIP-1599 transactions. These transactions have a designated transaction type of `0x02` and have the following parameters:
Done.

2024-04-22 06:19 UTC, aarshkshah1992 commented on FIPS/fip-00xx.md
> +This FIP introduces support for the Ethereum Homestead era's legacy transactions on the Filecoin network, complementing the existing support for EIP-1599 transactions. The main goal of this proposal
Done.

2024-04-22 06:21 UTC, aarshkshah1992 commented on FIPS/fip-00xx.md
> +Note that this is only a temporary transformation for the purpose of a validating the signature of a legacy transaction and for extracting the public key of the sender from the signature. The `V` val
I think we should go ahead and stick with using the marker byte in the signature to detect transaction types as it is more forward compatible and also makes it easy to add support for more transaction types down the line.

2024-04-22 06:23 UTC, aarshkshah1992 commented
@Schwartz10 Thanks for pointing that out. I have added the  point about wallet support for legacy transactions to the `Change Motivation` section

2024-04-23 00:08 UTC, jennijuju commented on FIPS/fip-00xx.md
> +fip: "XXXX"
Assigning 0091

2024-04-23 00:10 UTC, jennijuju commented on FIPS/fip-00xx.md
> +The main distinction relevant to this FIP is that legacy transactions do not contain a `ChainID` and so the transactions are not scoped to a specific chain.  This allows replaying the same signed con
```suggestion
The main distinction relevant to this FIP is that legacy transactions do not contain a `ChainID` and so the transactions are not scoped to a specific chain. This allows replaying the same signed contract creation transaction across multiple chains for deploying a contract and also enables the contract to have the same address across chains.
```

2024-04-23 00:12 UTC, jennijuju commented on FIPS/fip-00xx.md
> +The main distinction relevant to this FIP is that legacy transactions do not contain a `ChainID` and so the transactions are not scoped to a specific chain.  This allows replaying the same signed con
>  This allows replaying the same signed contract creation transaction across multiple chains

Just a question, is the risk only exposed to contract tx, but not to pure value transfer across wallet accounts (eth accounts) as well? (I'm curious how those two type of tx are differentiated

2024-04-23 00:27 UTC, jennijuju approved these changes

2024-04-23 06:46 UTC, aarshkshah1992 commented on FIPS/fip-00xx.md
> +This proposal adds support for a new transaction type to Filecoin. Since transactions form part of the chain state, this is a consensus breaking change and so all nodes will have to upgrade to suppor
I mean it's both in the sense that if you have a groups of miners who can validate TX1 and another group of miners who can't validate TX1, they will end up with different state tries.

2024-04-26 15:03 UTC, aarshkshah1992 commented on FIPS/fip-00xx.md
> +The main distinction relevant to this FIP is that legacy transactions do not contain a `ChainID` and so the transactions are not scoped to a specific chain.  This allows replaying the same signed con
You can do value transfers with this as well using legacy transactions i.e. you can use the same signed value transfer message across networks for value transfer (the nonces, state etc should align for the transaction to be considered valid).

2024-04-26 16:54 UTC, jennijuju requested changes

2024-04-26 16:54 UTC, jennijuju commented on FIPS/fip-0091.md
> +status: Accepted
DO NOT MERGE. Please don’t change main key info w/o requesting fip editors’s re-review. 
This FIP is not Accepted. Fip editors’ approval on this PR only suggests the FIP draft is content ready to be merged to FIP repo. It doesn’t imply FIP’s readiness for the network. FIP must go through core dev  and community’s review, and a last call period before it is accepted.

2024-04-27 04:28 UTC, jennijuju commented on FIPS/fip-00xx.md
> +The main distinction relevant to this FIP is that legacy transactions do not contain a `ChainID` and so the transactions are not scoped to a specific chain.  This allows replaying the same signed con
The way it is written right now seems excluded this use case

2024-04-27 18:23 UTC, aarshkshah1992 commented on FIPS/fip-0091.md
> +status: Accepted
@jennijuju Apologies, I thought having 2 approvals meant that the FIP is now accepted. I have changed it back to Draft status.

2024-04-27 18:41 UTC, jennijuju commented on FIPS/fip-0091.md
> +status: Accepted
All good! Now you are a fip process master 😆😆

2024-04-27 18:41 UTC, jennijuju approved these changes

2024-04-27 18:42 UTC, merged